(* autogenerated from social-media-library/client *)
From New.golang Require Import defn.
Module pkg_id.
Definition client : go_string := "social-media-library/client".

End pkg_id.
Export pkg_id.
Module client.

Definition Operation {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/client.Operation"%go [].

#[global] Opaque Operation.

Definition Message {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/client.Message"%go [].

#[global] Opaque Message.

Definition Client {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/client.Client"%go [].

#[global] Opaque Client.

Definition maxTwoInts {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "social-media-library/client.maxTwoInts"%go.

Definition maxTS {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "social-media-library/client.maxTS"%go.

Definition read {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "social-media-library/client.read"%go.

Definition write {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "social-media-library/client.write"%go.

Definition ProcessRequest {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "social-media-library/client.ProcessRequest"%go.

(* go: client.go:46:6 *)
Definition maxTwoIntsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "x" "y",
    exception_do (let: "y" := (GoAlloc go.uint64 "y") in
    let: "x" := (GoAlloc go.uint64 "x") in
    (if: Convert go.untyped_bool go.bool ((![go.uint64] "x") >⟨go.uint64⟩ (![go.uint64] "y"))
    then return: (![go.uint64] "x")
    else return: (![go.uint64] "y"))).

(* go: client.go:54:6 *)
Definition maxTSⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "t1" "t2",
    exception_do (let: "t2" := (GoAlloc (go.SliceType go.uint64) "t2") in
    let: "t1" := (GoAlloc (go.SliceType go.uint64) "t1") in
    let: "i" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := #(W64 0) in
    do:  ("i" <-[go.uint64] "$r0");;;
    let: "length" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (Convert go.int go.uint64 (let: "$a0" := (![go.SliceType go.uint64] "t1") in
    (FuncResolve go.len [go.SliceType go.uint64] #()) "$a0")) in
    do:  ("length" <-[go.uint64] "$r0");;;
    let: "output" := (GoAlloc (go.SliceType go.uint64) (GoZeroVal (go.SliceType go.uint64) #())) in
    let: "$r0" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) (let: "$a0" := (![go.SliceType go.uint64] "t1") in
    (FuncResolve go.len [go.SliceType go.uint64] #()) "$a0")) in
    do:  ("output" <-[go.SliceType go.uint64] "$r0");;;
    (for: (λ: <>, (![go.uint64] "i") <⟨go.uint64⟩ (![go.uint64] "length")); (λ: <>, #()) := λ: <>,
      let: "$r0" := (let: "$a0" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "t1", Convert go.uint64 go.int (![go.uint64] "i")))) in
      let: "$a1" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "t2", Convert go.uint64 go.int (![go.uint64] "i")))) in
      (FuncResolve maxTwoInts [] #()) "$a0" "$a1") in
      do:  ((IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "output", Convert go.uint64 go.int (![go.uint64] "i"))) <-[go.uint64] "$r0");;;
      do:  ("i" <-[go.uint64] ((![go.uint64] "i") +⟨go.uint64⟩ #(W64 1))));;;
    return: (![go.SliceType go.uint64] "output")).

(* go: client.go:65:6 *)
Definition readⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "client" "serverId" "keys",
    exception_do (let: "keys" := (GoAlloc (go.SliceType go.uint64) "keys") in
    let: "serverId" := (GoAlloc go.uint64 "serverId") in
    let: "client" := (GoAlloc Client "client") in
    let: "reply" := (GoAlloc Message (GoZeroVal Message #())) in
    let: "$r0" := (CompositeLiteral Message (LiteralValue [])) in
    do:  ("reply" <-[Message] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 0)) || ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 1))) || ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 2)))
    then
      let: "$r0" := #(W64 0) in
      do:  ((StructFieldRef Message "MessageType"%go "reply") <-[go.uint64] "$r0");;;
      let: "$r0" := (![go.uint64] (StructFieldRef Client "Id"%go "client")) in
      do:  ((StructFieldRef Message "C2S_Client_Id"%go "reply") <-[go.uint64] "$r0");;;
      let: "$r0" := #(W64 0) in
      do:  ((StructFieldRef Message "C2S_Client_OperationType"%go "reply") <-[go.uint64] "$r0");;;
      let: "$r0" := (![go.SliceType go.uint64] "keys") in
      do:  ((StructFieldRef Message "C2S_Client_Keys"%go "reply") <-[go.SliceType go.uint64] "$r0");;;
      let: "$r0" := (![go.uint64] "serverId") in
      do:  ((StructFieldRef Message "C2S_Server_Id"%go "reply") <-[go.uint64] "$r0");;;
      let: "$r0" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) (![go.uint64] (StructFieldRef Client "NumberOfServers"%go "client"))) in
      do:  ((StructFieldRef Message "C2S_Client_VersionVector"%go "reply") <-[go.SliceType go.uint64] "$r0")
    else
      (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 3))
      then
        let: "$r0" := #(W64 0) in
        do:  ((StructFieldRef Message "MessageType"%go "reply") <-[go.uint64] "$r0");;;
        let: "$r0" := (![go.uint64] (StructFieldRef Client "Id"%go "client")) in
        do:  ((StructFieldRef Message "C2S_Client_Id"%go "reply") <-[go.uint64] "$r0");;;
        let: "$r0" := #(W64 0) in
        do:  ((StructFieldRef Message "C2S_Client_OperationType"%go "reply") <-[go.uint64] "$r0");;;
        let: "$r0" := (![go.SliceType go.uint64] "keys") in
        do:  ((StructFieldRef Message "C2S_Client_Keys"%go "reply") <-[go.SliceType go.uint64] "$r0");;;
        let: "$r0" := (![go.uint64] "serverId") in
        do:  ((StructFieldRef Message "C2S_Server_Id"%go "reply") <-[go.uint64] "$r0");;;
        let: "$r0" := (let: "$a0" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) #(W64 0)) in
        let: "$a1" := (![go.SliceType go.uint64] (StructFieldRef Client "ReadVersionVector"%go "client")) in
        (FuncResolve go.append [go.SliceType go.uint64] #()) "$a0" "$a1") in
        do:  ((StructFieldRef Message "C2S_Client_VersionVector"%go "reply") <-[go.SliceType go.uint64] "$r0")
      else
        (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 4))
        then
          let: "$r0" := #(W64 0) in
          do:  ((StructFieldRef Message "MessageType"%go "reply") <-[go.uint64] "$r0");;;
          let: "$r0" := (![go.uint64] (StructFieldRef Client "Id"%go "client")) in
          do:  ((StructFieldRef Message "C2S_Client_Id"%go "reply") <-[go.uint64] "$r0");;;
          let: "$r0" := #(W64 0) in
          do:  ((StructFieldRef Message "C2S_Client_OperationType"%go "reply") <-[go.uint64] "$r0");;;
          let: "$r0" := (![go.SliceType go.uint64] "keys") in
          do:  ((StructFieldRef Message "C2S_Client_Keys"%go "reply") <-[go.SliceType go.uint64] "$r0");;;
          let: "$r0" := (![go.uint64] "serverId") in
          do:  ((StructFieldRef Message "C2S_Server_Id"%go "reply") <-[go.uint64] "$r0");;;
          let: "$r0" := (let: "$a0" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) #(W64 0)) in
          let: "$a1" := (![go.SliceType go.uint64] (StructFieldRef Client "WriteVersionVector"%go "client")) in
          (FuncResolve go.append [go.SliceType go.uint64] #()) "$a0" "$a1") in
          do:  ((StructFieldRef Message "C2S_Client_VersionVector"%go "reply") <-[go.SliceType go.uint64] "$r0")
        else
          (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 5))
          then
            let: "$r0" := #(W64 0) in
            do:  ((StructFieldRef Message "MessageType"%go "reply") <-[go.uint64] "$r0");;;
            let: "$r0" := (![go.uint64] (StructFieldRef Client "Id"%go "client")) in
            do:  ((StructFieldRef Message "C2S_Client_Id"%go "reply") <-[go.uint64] "$r0");;;
            let: "$r0" := #(W64 0) in
            do:  ((StructFieldRef Message "C2S_Client_OperationType"%go "reply") <-[go.uint64] "$r0");;;
            let: "$r0" := (![go.SliceType go.uint64] "keys") in
            do:  ((StructFieldRef Message "C2S_Client_Keys"%go "reply") <-[go.SliceType go.uint64] "$r0");;;
            let: "$r0" := (![go.uint64] "serverId") in
            do:  ((StructFieldRef Message "C2S_Server_Id"%go "reply") <-[go.uint64] "$r0");;;
            let: "$r0" := (let: "$a0" := (![go.SliceType go.uint64] (StructFieldRef Client "WriteVersionVector"%go "client")) in
            let: "$a1" := (![go.SliceType go.uint64] (StructFieldRef Client "ReadVersionVector"%go "client")) in
            (FuncResolve maxTS [] #()) "$a0" "$a1") in
            do:  ((StructFieldRef Message "C2S_Client_VersionVector"%go "reply") <-[go.SliceType go.uint64] "$r0")
          else do:  #()))));;;
    return: (![Message] "reply")).

(* go: client.go:100:6 *)
Definition writeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "client" "serverId" "add" "key" "val",
    exception_do (let: "val" := (GoAlloc go.uint64 "val") in
    let: "key" := (GoAlloc go.uint64 "key") in
    let: "add" := (GoAlloc go.bool "add") in
    let: "serverId" := (GoAlloc go.uint64 "serverId") in
    let: "client" := (GoAlloc Client "client") in
    let: "reply" := (GoAlloc Message (GoZeroVal Message #())) in
    let: "$r0" := (CompositeLiteral Message (LiteralValue [])) in
    do:  ("reply" <-[Message] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 0)) || ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 3))) || ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 4)))
    then
      let: "$r0" := #(W64 0) in
      do:  ((StructFieldRef Message "MessageType"%go "reply") <-[go.uint64] "$r0");;;
      let: "$r0" := (![go.uint64] (StructFieldRef Client "Id"%go "client")) in
      do:  ((StructFieldRef Message "C2S_Client_Id"%go "reply") <-[go.uint64] "$r0");;;
      let: "$r0" := #(W64 1) in
      do:  ((StructFieldRef Message "C2S_Client_OperationType"%go "reply") <-[go.uint64] "$r0");;;
      let: "$r0" := (![go.bool] "add") in
      do:  ((StructFieldRef Message "C2S_Client_Add"%go "reply") <-[go.bool] "$r0");;;
      let: "$r0" := (let: "$v0" := (![go.uint64] "key") in
      CompositeLiteral (go.SliceType go.uint64) (LiteralValue [KeyedElement None (ElementExpression go.uint64 "$v0")])) in
      do:  ((StructFieldRef Message "C2S_Client_Keys"%go "reply") <-[go.SliceType go.uint64] "$r0");;;
      let: "$r0" := (![go.uint64] "val") in
      do:  ((StructFieldRef Message "C2S_Client_Val"%go "reply") <-[go.uint64] "$r0");;;
      let: "$r0" := (![go.uint64] "serverId") in
      do:  ((StructFieldRef Message "C2S_Server_Id"%go "reply") <-[go.uint64] "$r0");;;
      let: "$r0" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) (![go.uint64] (StructFieldRef Client "NumberOfServers"%go "client"))) in
      do:  ((StructFieldRef Message "C2S_Client_VersionVector"%go "reply") <-[go.SliceType go.uint64] "$r0")
    else
      (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 1))
      then
        let: "$r0" := #(W64 0) in
        do:  ((StructFieldRef Message "MessageType"%go "reply") <-[go.uint64] "$r0");;;
        let: "$r0" := (![go.uint64] (StructFieldRef Client "Id"%go "client")) in
        do:  ((StructFieldRef Message "C2S_Client_Id"%go "reply") <-[go.uint64] "$r0");;;
        let: "$r0" := #(W64 1) in
        do:  ((StructFieldRef Message "C2S_Client_OperationType"%go "reply") <-[go.uint64] "$r0");;;
        let: "$r0" := (![go.bool] "add") in
        do:  ((StructFieldRef Message "C2S_Client_Add"%go "reply") <-[go.bool] "$r0");;;
        let: "$r0" := (let: "$v0" := (![go.uint64] "key") in
        CompositeLiteral (go.SliceType go.uint64) (LiteralValue [KeyedElement None (ElementExpression go.uint64 "$v0")])) in
        do:  ((StructFieldRef Message "C2S_Client_Keys"%go "reply") <-[go.SliceType go.uint64] "$r0");;;
        let: "$r0" := (![go.uint64] "val") in
        do:  ((StructFieldRef Message "C2S_Client_Val"%go "reply") <-[go.uint64] "$r0");;;
        let: "$r0" := (![go.uint64] "serverId") in
        do:  ((StructFieldRef Message "C2S_Server_Id"%go "reply") <-[go.uint64] "$r0");;;
        let: "$r0" := (let: "$a0" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) #(W64 0)) in
        let: "$a1" := (![go.SliceType go.uint64] (StructFieldRef Client "ReadVersionVector"%go "client")) in
        (FuncResolve go.append [go.SliceType go.uint64] #()) "$a0" "$a1") in
        do:  ((StructFieldRef Message "C2S_Client_VersionVector"%go "reply") <-[go.SliceType go.uint64] "$r0")
      else
        (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 2))
        then
          let: "$r0" := #(W64 0) in
          do:  ((StructFieldRef Message "MessageType"%go "reply") <-[go.uint64] "$r0");;;
          let: "$r0" := (![go.uint64] (StructFieldRef Client "Id"%go "client")) in
          do:  ((StructFieldRef Message "C2S_Client_Id"%go "reply") <-[go.uint64] "$r0");;;
          let: "$r0" := #(W64 1) in
          do:  ((StructFieldRef Message "C2S_Client_OperationType"%go "reply") <-[go.uint64] "$r0");;;
          let: "$r0" := (![go.bool] "add") in
          do:  ((StructFieldRef Message "C2S_Client_Add"%go "reply") <-[go.bool] "$r0");;;
          let: "$r0" := (let: "$v0" := (![go.uint64] "key") in
          CompositeLiteral (go.SliceType go.uint64) (LiteralValue [KeyedElement None (ElementExpression go.uint64 "$v0")])) in
          do:  ((StructFieldRef Message "C2S_Client_Keys"%go "reply") <-[go.SliceType go.uint64] "$r0");;;
          let: "$r0" := (![go.uint64] "val") in
          do:  ((StructFieldRef Message "C2S_Client_Val"%go "reply") <-[go.uint64] "$r0");;;
          let: "$r0" := (![go.uint64] "serverId") in
          do:  ((StructFieldRef Message "C2S_Server_Id"%go "reply") <-[go.uint64] "$r0");;;
          let: "$r0" := (let: "$a0" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) #(W64 0)) in
          let: "$a1" := (![go.SliceType go.uint64] (StructFieldRef Client "WriteVersionVector"%go "client")) in
          (FuncResolve go.append [go.SliceType go.uint64] #()) "$a0" "$a1") in
          do:  ((StructFieldRef Message "C2S_Client_VersionVector"%go "reply") <-[go.SliceType go.uint64] "$r0")
        else
          (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) =⟨go.uint64⟩ #(W64 5))
          then
            let: "$r0" := #(W64 0) in
            do:  ((StructFieldRef Message "MessageType"%go "reply") <-[go.uint64] "$r0");;;
            let: "$r0" := (![go.uint64] (StructFieldRef Client "Id"%go "client")) in
            do:  ((StructFieldRef Message "C2S_Client_Id"%go "reply") <-[go.uint64] "$r0");;;
            let: "$r0" := #(W64 1) in
            do:  ((StructFieldRef Message "C2S_Client_OperationType"%go "reply") <-[go.uint64] "$r0");;;
            let: "$r0" := (![go.bool] "add") in
            do:  ((StructFieldRef Message "C2S_Client_Add"%go "reply") <-[go.bool] "$r0");;;
            let: "$r0" := (let: "$v0" := (![go.uint64] "key") in
            CompositeLiteral (go.SliceType go.uint64) (LiteralValue [KeyedElement None (ElementExpression go.uint64 "$v0")])) in
            do:  ((StructFieldRef Message "C2S_Client_Keys"%go "reply") <-[go.SliceType go.uint64] "$r0");;;
            let: "$r0" := (![go.uint64] "val") in
            do:  ((StructFieldRef Message "C2S_Client_Val"%go "reply") <-[go.uint64] "$r0");;;
            let: "$r0" := (![go.uint64] "serverId") in
            do:  ((StructFieldRef Message "C2S_Server_Id"%go "reply") <-[go.uint64] "$r0");;;
            let: "$r0" := (let: "$a0" := (![go.SliceType go.uint64] (StructFieldRef Client "WriteVersionVector"%go "client")) in
            let: "$a1" := (![go.SliceType go.uint64] (StructFieldRef Client "ReadVersionVector"%go "client")) in
            (FuncResolve maxTS [] #()) "$a0" "$a1") in
            do:  ((StructFieldRef Message "C2S_Client_VersionVector"%go "reply") <-[go.SliceType go.uint64] "$r0")
          else do:  #()))));;;
    return: (![Message] "reply")).

(* go: client.go:143:6 *)
Definition ProcessRequestⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "client" "requestType" "serverId" "add" "keys" "val" "ackMessage",
    exception_do (let: "ackMessage" := (GoAlloc Message "ackMessage") in
    let: "val" := (GoAlloc go.uint64 "val") in
    let: "keys" := (GoAlloc (go.SliceType go.uint64) "keys") in
    let: "add" := (GoAlloc go.bool "add") in
    let: "serverId" := (GoAlloc go.uint64 "serverId") in
    let: "requestType" := (GoAlloc go.uint64 "requestType") in
    let: "client" := (GoAlloc Client "client") in
    let: "nc" := (GoAlloc Client (GoZeroVal Client #())) in
    let: "$r0" := (let: "$v0" := (![go.uint64] (StructFieldRef Client "Id"%go "client")) in
    let: "$v1" := (![go.uint64] (StructFieldRef Client "NumberOfServers"%go "client")) in
    let: "$v2" := (![go.SliceType go.uint64] (StructFieldRef Client "WriteVersionVector"%go "client")) in
    let: "$v3" := (![go.SliceType go.uint64] (StructFieldRef Client "ReadVersionVector"%go "client")) in
    let: "$v4" := (![go.uint64] (StructFieldRef Client "SessionSemantic"%go "client")) in
    let: "$v5" := (![go.bool] (StructFieldRef Client "Pending"%go "client")) in
    CompositeLiteral Client (LiteralValue [KeyedElement (Some (KeyField "Id"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "NumberOfServers"%go)) (ElementExpression go.uint64 "$v1"); KeyedElement (Some (KeyField "WriteVersionVector"%go)) (ElementExpression (go.SliceType go.uint64) "$v2"); KeyedElement (Some (KeyField "ReadVersionVector"%go)) (ElementExpression (go.SliceType go.uint64) "$v3"); KeyedElement (Some (KeyField "SessionSemantic"%go)) (ElementExpression go.uint64 "$v4"); KeyedElement (Some (KeyField "Pending"%go)) (ElementExpression go.bool "$v5")])) in
    do:  ("nc" <-[Client] "$r0");;;
    let: "msg" := (GoAlloc Message (GoZeroVal Message #())) in
    let: "$r0" := (CompositeLiteral Message (LiteralValue [])) in
    do:  ("msg" <-[Message] "$r0");;;
    let: "is_ret" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: "$r0" := #false in
    do:  ("is_ret" <-[go.bool] "$r0");;;
    let: "is_val" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: "$r0" := #false in
    do:  ("is_val" <-[go.bool] "$r0");;;
    let: "ret" := (GoAlloc (go.MapType go.uint64 (go.SliceType go.uint64)) (GoZeroVal (go.MapType go.uint64 (go.SliceType go.uint64)) #())) in
    (if: (⟨go.bool⟩! (![go.bool] (StructFieldRef Client "Pending"%go "client"))) && ((![go.uint64] "requestType") =⟨go.uint64⟩ #(W64 0))
    then
      let: "$r0" := (let: "$a0" := (![Client] "client") in
      let: "$a1" := (![go.uint64] "serverId") in
      let: "$a2" := (![go.SliceType go.uint64] "keys") in
      (FuncResolve read [] #()) "$a0" "$a1" "$a2") in
      do:  ("msg" <-[Message] "$r0");;;
      let: "$r0" := #true in
      do:  ((StructFieldRef Client "Pending"%go "nc") <-[go.bool] "$r0")
    else
      (if: (⟨go.bool⟩! (![go.bool] (StructFieldRef Client "Pending"%go "client"))) && ((![go.uint64] "requestType") =⟨go.uint64⟩ #(W64 1))
      then
        let: "$r0" := (let: "$a0" := (![Client] "client") in
        let: "$a1" := (![go.uint64] "serverId") in
        let: "$a2" := (![go.bool] "add") in
        let: "$a3" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "keys", #(W64 0)))) in
        let: "$a4" := (![go.uint64] "val") in
        (FuncResolve write [] #()) "$a0" "$a1" "$a2" "$a3" "$a4") in
        do:  ("msg" <-[Message] "$r0");;;
        let: "$r0" := #true in
        do:  ((StructFieldRef Client "Pending"%go "nc") <-[go.bool] "$r0")
      else
        (if: (![go.bool] (StructFieldRef Client "Pending"%go "client")) && ((![go.uint64] "requestType") =⟨go.uint64⟩ #(W64 2))
        then
          let: "$r0" := #true in
          do:  ("is_ret" <-[go.bool] "$r0");;;
          (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef Message "MessageType"%go "ackMessage")) =⟨go.uint64⟩ #(W64 4))
          then
            let: "$r0" := #true in
            do:  ("is_ret" <-[go.bool] "$r0");;;
            (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef Message "S2C_Client_OperationType"%go "ackMessage")) =⟨go.uint64⟩ #(W64 0))
            then
              let: "$r0" := (let: "$a0" := (![go.SliceType go.uint64] (StructFieldRef Client "ReadVersionVector"%go "nc")) in
              let: "$a1" := (![go.SliceType go.uint64] (StructFieldRef Message "S2C_Client_VersionVector"%go "ackMessage")) in
              (FuncResolve maxTS [] #()) "$a0" "$a1") in
              do:  ((StructFieldRef Client "ReadVersionVector"%go "nc") <-[go.SliceType go.uint64] "$r0");;;
              let: "$r0" := #true in
              do:  ("is_val" <-[go.bool] "$r0");;;
              let: "$r0" := (![go.MapType go.uint64 (go.SliceType go.uint64)] (StructFieldRef Message "S2C_Client_Data"%go "ackMessage")) in
              do:  ("ret" <-[go.MapType go.uint64 (go.SliceType go.uint64)] "$r0")
            else do:  #());;;
            (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef Message "S2C_Client_OperationType"%go "ackMessage")) =⟨go.uint64⟩ #(W64 1))
            then
              let: "$r0" := (let: "$a0" := (![go.SliceType go.uint64] (StructFieldRef Client "WriteVersionVector"%go "nc")) in
              let: "$a1" := (![go.SliceType go.uint64] (StructFieldRef Message "S2C_Client_VersionVector"%go "ackMessage")) in
              (FuncResolve maxTS [] #()) "$a0" "$a1") in
              do:  ((StructFieldRef Client "WriteVersionVector"%go "nc") <-[go.SliceType go.uint64] "$r0")
            else do:  #());;;
            let: "$r0" := #false in
            do:  ((StructFieldRef Client "Pending"%go "nc") <-[go.bool] "$r0")
          else do:  #())
        else do:  #())));;;
    return: (![Client] "nc", ![Message] "msg", ![go.bool] "is_ret", ![go.bool] "is_val", ![go.MapType go.uint64 (go.SliceType go.uint64)] "ret")).

#[global] Instance info' : PkgInfo pkg_id.client :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.client (λ: <>,
      exception_do (do:  #())
      ).

Module Operation.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  VersionVector' : slice.t;
  Add' : bool;
  Key' : w64;
  Val' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Operation.

Definition Operation'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "VersionVector"%go (go.SliceType go.uint64));
  (go.FieldDecl "Add"%go go.bool);
  (go.FieldDecl "Key"%go go.uint64);
  (go.FieldDecl "Val"%go go.uint64)
].
Program Definition Operation'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Operation'fds_unsealed).
Global Instance equals_unfold_Operation {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Operation'fds =→ Operation'fds_unsealed.
Proof. rewrite /Operation'fds seal_eq //. Qed.

Definition Operationⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Operation'fds).

Class Operation_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Operation_type_repr  :: go.TypeReprUnderlying Operationⁱᵐᵖˡ Operation.t;
  #[global] Operation_underlying :: (Operation) <u (Operationⁱᵐᵖˡ);
  #[global] Operation_get_VersionVector (x : Operation.t) :: ⟦StructFieldGet (Operationⁱᵐᵖˡ) "VersionVector", #x⟧ ⤳[under] #x.(Operation.VersionVector');
  #[global] Operation_set_VersionVector (x : Operation.t) y :: ⟦StructFieldSet (Operationⁱᵐᵖˡ) "VersionVector", (#x, #y)⟧ ⤳[under] #(x <|Operation.VersionVector' := y|>);
  #[global] Operation_get_Add (x : Operation.t) :: ⟦StructFieldGet (Operationⁱᵐᵖˡ) "Add", #x⟧ ⤳[under] #x.(Operation.Add');
  #[global] Operation_set_Add (x : Operation.t) y :: ⟦StructFieldSet (Operationⁱᵐᵖˡ) "Add", (#x, #y)⟧ ⤳[under] #(x <|Operation.Add' := y|>);
  #[global] Operation_get_Key (x : Operation.t) :: ⟦StructFieldGet (Operationⁱᵐᵖˡ) "Key", #x⟧ ⤳[under] #x.(Operation.Key');
  #[global] Operation_set_Key (x : Operation.t) y :: ⟦StructFieldSet (Operationⁱᵐᵖˡ) "Key", (#x, #y)⟧ ⤳[under] #(x <|Operation.Key' := y|>);
  #[global] Operation_get_Val (x : Operation.t) :: ⟦StructFieldGet (Operationⁱᵐᵖˡ) "Val", #x⟧ ⤳[under] #x.(Operation.Val');
  #[global] Operation_set_Val (x : Operation.t) y :: ⟦StructFieldSet (Operationⁱᵐᵖˡ) "Val", (#x, #y)⟧ ⤳[under] #(x <|Operation.Val' := y|>);
}.

Module Message.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  MessageType' : w64;
  C2S_Client_Id' : w64;
  C2S_Server_Id' : w64;
  C2S_Client_OperationType' : w64;
  C2S_Client_Add' : bool;
  C2S_Client_Keys' : slice.t;
  C2S_Client_Val' : w64;
  C2S_Client_VersionVector' : slice.t;
  S2S_Gossip_Sending_ServerId' : w64;
  S2S_Gossip_Receiving_ServerId' : w64;
  S2S_Gossip_Operations' : slice.t;
  S2S_Gossip_Index' : w64;
  S2S_Acknowledge_Gossip_Sending_ServerId' : w64;
  S2S_Acknowledge_Gossip_Receiving_ServerId' : w64;
  S2S_Acknowledge_Gossip_Index' : w64;
  S2C_Client_OperationType' : w64;
  S2C_Client_Data' : map.t;
  S2C_Client_VersionVector' : slice.t;
  S2C_Server_Id' : w64;
  S2C_Client_Number' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Message.

Definition Message'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "MessageType"%go go.uint64);
  (go.FieldDecl "C2S_Client_Id"%go go.uint64);
  (go.FieldDecl "C2S_Server_Id"%go go.uint64);
  (go.FieldDecl "C2S_Client_OperationType"%go go.uint64);
  (go.FieldDecl "C2S_Client_Add"%go go.bool);
  (go.FieldDecl "C2S_Client_Keys"%go (go.SliceType go.uint64));
  (go.FieldDecl "C2S_Client_Val"%go go.uint64);
  (go.FieldDecl "C2S_Client_VersionVector"%go (go.SliceType go.uint64));
  (go.FieldDecl "S2S_Gossip_Sending_ServerId"%go go.uint64);
  (go.FieldDecl "S2S_Gossip_Receiving_ServerId"%go go.uint64);
  (go.FieldDecl "S2S_Gossip_Operations"%go (go.SliceType Operation));
  (go.FieldDecl "S2S_Gossip_Index"%go go.uint64);
  (go.FieldDecl "S2S_Acknowledge_Gossip_Sending_ServerId"%go go.uint64);
  (go.FieldDecl "S2S_Acknowledge_Gossip_Receiving_ServerId"%go go.uint64);
  (go.FieldDecl "S2S_Acknowledge_Gossip_Index"%go go.uint64);
  (go.FieldDecl "S2C_Client_OperationType"%go go.uint64);
  (go.FieldDecl "S2C_Client_Data"%go (go.MapType go.uint64 (go.SliceType go.uint64)));
  (go.FieldDecl "S2C_Client_VersionVector"%go (go.SliceType go.uint64));
  (go.FieldDecl "S2C_Server_Id"%go go.uint64);
  (go.FieldDecl "S2C_Client_Number"%go go.uint64)
].
Program Definition Message'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Message'fds_unsealed).
Global Instance equals_unfold_Message {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Message'fds =→ Message'fds_unsealed.
Proof. rewrite /Message'fds seal_eq //. Qed.

Definition Messageⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Message'fds).

Class Message_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Message_type_repr  :: go.TypeReprUnderlying Messageⁱᵐᵖˡ Message.t;
  #[global] Message_underlying :: (Message) <u (Messageⁱᵐᵖˡ);
  #[global] Message_get_MessageType (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "MessageType", #x⟧ ⤳[under] #x.(Message.MessageType');
  #[global] Message_set_MessageType (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "MessageType", (#x, #y)⟧ ⤳[under] #(x <|Message.MessageType' := y|>);
  #[global] Message_get_C2S_Client_Id (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_Id", #x⟧ ⤳[under] #x.(Message.C2S_Client_Id');
  #[global] Message_set_C2S_Client_Id (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_Id", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_Id' := y|>);
  #[global] Message_get_C2S_Server_Id (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Server_Id", #x⟧ ⤳[under] #x.(Message.C2S_Server_Id');
  #[global] Message_set_C2S_Server_Id (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Server_Id", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Server_Id' := y|>);
  #[global] Message_get_C2S_Client_OperationType (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_OperationType", #x⟧ ⤳[under] #x.(Message.C2S_Client_OperationType');
  #[global] Message_set_C2S_Client_OperationType (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_OperationType", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_OperationType' := y|>);
  #[global] Message_get_C2S_Client_Add (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_Add", #x⟧ ⤳[under] #x.(Message.C2S_Client_Add');
  #[global] Message_set_C2S_Client_Add (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_Add", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_Add' := y|>);
  #[global] Message_get_C2S_Client_Keys (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_Keys", #x⟧ ⤳[under] #x.(Message.C2S_Client_Keys');
  #[global] Message_set_C2S_Client_Keys (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_Keys", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_Keys' := y|>);
  #[global] Message_get_C2S_Client_Val (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_Val", #x⟧ ⤳[under] #x.(Message.C2S_Client_Val');
  #[global] Message_set_C2S_Client_Val (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_Val", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_Val' := y|>);
  #[global] Message_get_C2S_Client_VersionVector (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_VersionVector", #x⟧ ⤳[under] #x.(Message.C2S_Client_VersionVector');
  #[global] Message_set_C2S_Client_VersionVector (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_VersionVector", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_VersionVector' := y|>);
  #[global] Message_get_S2S_Gossip_Sending_ServerId (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Gossip_Sending_ServerId", #x⟧ ⤳[under] #x.(Message.S2S_Gossip_Sending_ServerId');
  #[global] Message_set_S2S_Gossip_Sending_ServerId (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Gossip_Sending_ServerId", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Gossip_Sending_ServerId' := y|>);
  #[global] Message_get_S2S_Gossip_Receiving_ServerId (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Gossip_Receiving_ServerId", #x⟧ ⤳[under] #x.(Message.S2S_Gossip_Receiving_ServerId');
  #[global] Message_set_S2S_Gossip_Receiving_ServerId (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Gossip_Receiving_ServerId", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Gossip_Receiving_ServerId' := y|>);
  #[global] Message_get_S2S_Gossip_Operations (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Gossip_Operations", #x⟧ ⤳[under] #x.(Message.S2S_Gossip_Operations');
  #[global] Message_set_S2S_Gossip_Operations (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Gossip_Operations", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Gossip_Operations' := y|>);
  #[global] Message_get_S2S_Gossip_Index (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Gossip_Index", #x⟧ ⤳[under] #x.(Message.S2S_Gossip_Index');
  #[global] Message_set_S2S_Gossip_Index (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Gossip_Index", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Gossip_Index' := y|>);
  #[global] Message_get_S2S_Acknowledge_Gossip_Sending_ServerId (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Sending_ServerId", #x⟧ ⤳[under] #x.(Message.S2S_Acknowledge_Gossip_Sending_ServerId');
  #[global] Message_set_S2S_Acknowledge_Gossip_Sending_ServerId (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Sending_ServerId", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Acknowledge_Gossip_Sending_ServerId' := y|>);
  #[global] Message_get_S2S_Acknowledge_Gossip_Receiving_ServerId (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Receiving_ServerId", #x⟧ ⤳[under] #x.(Message.S2S_Acknowledge_Gossip_Receiving_ServerId');
  #[global] Message_set_S2S_Acknowledge_Gossip_Receiving_ServerId (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Receiving_ServerId", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Acknowledge_Gossip_Receiving_ServerId' := y|>);
  #[global] Message_get_S2S_Acknowledge_Gossip_Index (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Index", #x⟧ ⤳[under] #x.(Message.S2S_Acknowledge_Gossip_Index');
  #[global] Message_set_S2S_Acknowledge_Gossip_Index (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Index", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Acknowledge_Gossip_Index' := y|>);
  #[global] Message_get_S2C_Client_OperationType (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Client_OperationType", #x⟧ ⤳[under] #x.(Message.S2C_Client_OperationType');
  #[global] Message_set_S2C_Client_OperationType (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Client_OperationType", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Client_OperationType' := y|>);
  #[global] Message_get_S2C_Client_Data (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Client_Data", #x⟧ ⤳[under] #x.(Message.S2C_Client_Data');
  #[global] Message_set_S2C_Client_Data (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Client_Data", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Client_Data' := y|>);
  #[global] Message_get_S2C_Client_VersionVector (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Client_VersionVector", #x⟧ ⤳[under] #x.(Message.S2C_Client_VersionVector');
  #[global] Message_set_S2C_Client_VersionVector (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Client_VersionVector", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Client_VersionVector' := y|>);
  #[global] Message_get_S2C_Server_Id (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Server_Id", #x⟧ ⤳[under] #x.(Message.S2C_Server_Id');
  #[global] Message_set_S2C_Server_Id (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Server_Id", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Server_Id' := y|>);
  #[global] Message_get_S2C_Client_Number (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Client_Number", #x⟧ ⤳[under] #x.(Message.S2C_Client_Number');
  #[global] Message_set_S2C_Client_Number (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Client_Number", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Client_Number' := y|>);
}.

Module Client.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  Id' : w64;
  NumberOfServers' : w64;
  WriteVersionVector' : slice.t;
  ReadVersionVector' : slice.t;
  SessionSemantic' : w64;
  Pending' : bool;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Client.

Definition Client'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "Id"%go go.uint64);
  (go.FieldDecl "NumberOfServers"%go go.uint64);
  (go.FieldDecl "WriteVersionVector"%go (go.SliceType go.uint64));
  (go.FieldDecl "ReadVersionVector"%go (go.SliceType go.uint64));
  (go.FieldDecl "SessionSemantic"%go go.uint64);
  (go.FieldDecl "Pending"%go go.bool)
].
Program Definition Client'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Client'fds_unsealed).
Global Instance equals_unfold_Client {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Client'fds =→ Client'fds_unsealed.
Proof. rewrite /Client'fds seal_eq //. Qed.

Definition Clientⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Client'fds).

Class Client_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Client_type_repr  :: go.TypeReprUnderlying Clientⁱᵐᵖˡ Client.t;
  #[global] Client_underlying :: (Client) <u (Clientⁱᵐᵖˡ);
  #[global] Client_get_Id (x : Client.t) :: ⟦StructFieldGet (Clientⁱᵐᵖˡ) "Id", #x⟧ ⤳[under] #x.(Client.Id');
  #[global] Client_set_Id (x : Client.t) y :: ⟦StructFieldSet (Clientⁱᵐᵖˡ) "Id", (#x, #y)⟧ ⤳[under] #(x <|Client.Id' := y|>);
  #[global] Client_get_NumberOfServers (x : Client.t) :: ⟦StructFieldGet (Clientⁱᵐᵖˡ) "NumberOfServers", #x⟧ ⤳[under] #x.(Client.NumberOfServers');
  #[global] Client_set_NumberOfServers (x : Client.t) y :: ⟦StructFieldSet (Clientⁱᵐᵖˡ) "NumberOfServers", (#x, #y)⟧ ⤳[under] #(x <|Client.NumberOfServers' := y|>);
  #[global] Client_get_WriteVersionVector (x : Client.t) :: ⟦StructFieldGet (Clientⁱᵐᵖˡ) "WriteVersionVector", #x⟧ ⤳[under] #x.(Client.WriteVersionVector');
  #[global] Client_set_WriteVersionVector (x : Client.t) y :: ⟦StructFieldSet (Clientⁱᵐᵖˡ) "WriteVersionVector", (#x, #y)⟧ ⤳[under] #(x <|Client.WriteVersionVector' := y|>);
  #[global] Client_get_ReadVersionVector (x : Client.t) :: ⟦StructFieldGet (Clientⁱᵐᵖˡ) "ReadVersionVector", #x⟧ ⤳[under] #x.(Client.ReadVersionVector');
  #[global] Client_set_ReadVersionVector (x : Client.t) y :: ⟦StructFieldSet (Clientⁱᵐᵖˡ) "ReadVersionVector", (#x, #y)⟧ ⤳[under] #(x <|Client.ReadVersionVector' := y|>);
  #[global] Client_get_SessionSemantic (x : Client.t) :: ⟦StructFieldGet (Clientⁱᵐᵖˡ) "SessionSemantic", #x⟧ ⤳[under] #x.(Client.SessionSemantic');
  #[global] Client_set_SessionSemantic (x : Client.t) y :: ⟦StructFieldSet (Clientⁱᵐᵖˡ) "SessionSemantic", (#x, #y)⟧ ⤳[under] #(x <|Client.SessionSemantic' := y|>);
  #[global] Client_get_Pending (x : Client.t) :: ⟦StructFieldGet (Clientⁱᵐᵖˡ) "Pending", #x⟧ ⤳[under] #x.(Client.Pending');
  #[global] Client_set_Pending (x : Client.t) y :: ⟦StructFieldSet (Clientⁱᵐᵖˡ) "Pending", (#x, #y)⟧ ⤳[under] #(x <|Client.Pending' := y|>);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Operation_instance :: Operation_Assumptions;
  #[global] Message_instance :: Message_Assumptions;
  #[global] Client_instance :: Client_Assumptions;
  #[global] maxTwoInts_unfold :: FuncUnfold maxTwoInts [] (maxTwoIntsⁱᵐᵖˡ);
  #[global] maxTS_unfold :: FuncUnfold maxTS [] (maxTSⁱᵐᵖˡ);
  #[global] read_unfold :: FuncUnfold read [] (readⁱᵐᵖˡ);
  #[global] write_unfold :: FuncUnfold write [] (writeⁱᵐᵖˡ);
  #[global] ProcessRequest_unfold :: FuncUnfold ProcessRequest [] (ProcessRequestⁱᵐᵖˡ);
}.
End client.
