(* autogenerated from social-media-library/common *)
Require Export New.code.strconv.
Require Export New.code.strings.
From New.golang Require Import defn.
Module pkg_id.
Definition common : go_string := "social-media-library/common".

End pkg_id.
Export pkg_id.
Module common.

Definition Post {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/common.Post"%go [].

#[global] Opaque Post.

Definition Connection {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/common.Connection"%go [].

#[global] Opaque Connection.

Definition Operation {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/common.Operation"%go [].

#[global] Opaque Operation.

Definition Message {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/common.Message"%go [].

#[global] Opaque Message.

Definition ProcessAddressString {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "social-media-library/common.ProcessAddressString"%go.

(* go: utils.go:8:6 *)
Definition ProcessAddressStringⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "address" "n",
    exception_do (let: "n" := (GoAlloc go.uint64 "n") in
    let: "address" := (GoAlloc go.string "address") in
    let: "l" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (![go.string] "address") in
    let: "$a1" := #":"%go in
    (FuncResolve strings.Split [] #()) "$a0" "$a1") in
    do:  ("l" <-[go.SliceType go.string] "$r0");;;
    let: "i" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "l", #(W64 1)))) in
    let: "$a1" := #(W64 10) in
    let: "$a2" := #(W64 64) in
    (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("i" <-[go.uint64] "$r0");;;
    do:  "$r1";;;
    return: (((![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "l", #(W64 0)))) +⟨go.string⟩ #":"%go) +⟨go.string⟩ (let: "$a0" := (Convert go.uint64 go.int ((![go.uint64] "i") +⟨go.uint64⟩ (![go.uint64] "n"))) in
     (FuncResolve strconv.Itoa [] #()) "$a0"))).

#[global] Instance info' : PkgInfo pkg_id.common :=
{|
  pkg_imported_pkgs := [code.strconv.pkg_id.strconv; code.strings.pkg_id.strings]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.common (λ: <>,
      exception_do (do:  (strings.initialize' #());;;
      do:  (strconv.initialize' #()))
      ).

Module Post.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  ID' : w64;
  Content' : go_string;
  Author' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Post.

Definition Post'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "ID"%go go.uint64);
  (go.FieldDecl "Content"%go go.string);
  (go.FieldDecl "Author"%go go.uint64)
].
Program Definition Post'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Post'fds_unsealed).
Global Instance equals_unfold_Post {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Post'fds =→ Post'fds_unsealed.
Proof. rewrite /Post'fds seal_eq //. Qed.

Definition Postⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Post'fds).

Class Post_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Post_type_repr  :: go.TypeReprUnderlying Postⁱᵐᵖˡ Post.t;
  #[global] Post_underlying :: (Post) <u (Postⁱᵐᵖˡ);
  #[global] Post_get_ID (x : Post.t) :: ⟦StructFieldGet (Postⁱᵐᵖˡ) "ID", #x⟧ ⤳[under] #x.(Post.ID');
  #[global] Post_set_ID (x : Post.t) y :: ⟦StructFieldSet (Postⁱᵐᵖˡ) "ID", (#x, #y)⟧ ⤳[under] #(x <|Post.ID' := y|>);
  #[global] Post_get_Content (x : Post.t) :: ⟦StructFieldGet (Postⁱᵐᵖˡ) "Content", #x⟧ ⤳[under] #x.(Post.Content');
  #[global] Post_set_Content (x : Post.t) y :: ⟦StructFieldSet (Postⁱᵐᵖˡ) "Content", (#x, #y)⟧ ⤳[under] #(x <|Post.Content' := y|>);
  #[global] Post_get_Author (x : Post.t) :: ⟦StructFieldGet (Postⁱᵐᵖˡ) "Author", #x⟧ ⤳[under] #x.(Post.Author');
  #[global] Post_set_Author (x : Post.t) y :: ⟦StructFieldSet (Postⁱᵐᵖˡ) "Author", (#x, #y)⟧ ⤳[under] #(x <|Post.Author' := y|>);
}.

Module Connection.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  Network' : go_string;
  Address' : go_string;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Connection.

Definition Connection'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "Network"%go go.string);
  (go.FieldDecl "Address"%go go.string)
].
Program Definition Connection'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Connection'fds_unsealed).
Global Instance equals_unfold_Connection {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Connection'fds =→ Connection'fds_unsealed.
Proof. rewrite /Connection'fds seal_eq //. Qed.

Definition Connectionⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Connection'fds).

Class Connection_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Connection_type_repr  :: go.TypeReprUnderlying Connectionⁱᵐᵖˡ Connection.t;
  #[global] Connection_underlying :: (Connection) <u (Connectionⁱᵐᵖˡ);
  #[global] Connection_get_Network (x : Connection.t) :: ⟦StructFieldGet (Connectionⁱᵐᵖˡ) "Network", #x⟧ ⤳[under] #x.(Connection.Network');
  #[global] Connection_set_Network (x : Connection.t) y :: ⟦StructFieldSet (Connectionⁱᵐᵖˡ) "Network", (#x, #y)⟧ ⤳[under] #(x <|Connection.Network' := y|>);
  #[global] Connection_get_Address (x : Connection.t) :: ⟦StructFieldGet (Connectionⁱᵐᵖˡ) "Address", #x⟧ ⤳[under] #x.(Connection.Address');
  #[global] Connection_set_Address (x : Connection.t) y :: ⟦StructFieldSet (Connectionⁱᵐᵖˡ) "Address", (#x, #y)⟧ ⤳[under] #(x <|Connection.Address' := y|>);
}.

Module Operation.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  VersionVector' : slice.t;
  Add' : bool;
  Key' : w64;
  Val' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Operation.

Definition Operation'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "VersionVector"%go (go.SliceType go.uint64));
  (go.FieldDecl "Add"%go go.bool);
  (go.FieldDecl "Key"%go go.uint64);
  (go.FieldDecl "Val"%go go.uint64)
].
Program Definition Operation'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Operation'fds_unsealed).
Global Instance equals_unfold_Operation {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Operation'fds =→ Operation'fds_unsealed.
Proof. rewrite /Operation'fds seal_eq //. Qed.

Definition Operationⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Operation'fds).

Class Operation_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Operation_type_repr  :: go.TypeReprUnderlying Operationⁱᵐᵖˡ Operation.t;
  #[global] Operation_underlying :: (Operation) <u (Operationⁱᵐᵖˡ);
  #[global] Operation_get_VersionVector (x : Operation.t) :: ⟦StructFieldGet (Operationⁱᵐᵖˡ) "VersionVector", #x⟧ ⤳[under] #x.(Operation.VersionVector');
  #[global] Operation_set_VersionVector (x : Operation.t) y :: ⟦StructFieldSet (Operationⁱᵐᵖˡ) "VersionVector", (#x, #y)⟧ ⤳[under] #(x <|Operation.VersionVector' := y|>);
  #[global] Operation_get_Add (x : Operation.t) :: ⟦StructFieldGet (Operationⁱᵐᵖˡ) "Add", #x⟧ ⤳[under] #x.(Operation.Add');
  #[global] Operation_set_Add (x : Operation.t) y :: ⟦StructFieldSet (Operationⁱᵐᵖˡ) "Add", (#x, #y)⟧ ⤳[under] #(x <|Operation.Add' := y|>);
  #[global] Operation_get_Key (x : Operation.t) :: ⟦StructFieldGet (Operationⁱᵐᵖˡ) "Key", #x⟧ ⤳[under] #x.(Operation.Key');
  #[global] Operation_set_Key (x : Operation.t) y :: ⟦StructFieldSet (Operationⁱᵐᵖˡ) "Key", (#x, #y)⟧ ⤳[under] #(x <|Operation.Key' := y|>);
  #[global] Operation_get_Val (x : Operation.t) :: ⟦StructFieldGet (Operationⁱᵐᵖˡ) "Val", #x⟧ ⤳[under] #x.(Operation.Val');
  #[global] Operation_set_Val (x : Operation.t) y :: ⟦StructFieldSet (Operationⁱᵐᵖˡ) "Val", (#x, #y)⟧ ⤳[under] #(x <|Operation.Val' := y|>);
}.

Module Message.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  MessageType' : w64;
  C2S_Client_Id' : w64;
  C2S_Server_Id' : w64;
  C2S_Client_OperationType' : w64;
  C2S_Client_Add' : bool;
  C2S_Client_Keys' : slice.t;
  C2S_Client_Val' : w64;
  C2S_Client_VersionVector' : slice.t;
  S2S_Gossip_Sending_ServerId' : w64;
  S2S_Gossip_Receiving_ServerId' : w64;
  S2S_Gossip_Operations' : slice.t;
  S2S_Gossip_Index' : w64;
  S2S_Acknowledge_Gossip_Sending_ServerId' : w64;
  S2S_Acknowledge_Gossip_Receiving_ServerId' : w64;
  S2S_Acknowledge_Gossip_Index' : w64;
  S2C_Client_OperationType' : w64;
  S2C_Client_Data' : map.t;
  S2C_Client_VersionVector' : slice.t;
  S2C_Server_Id' : w64;
  S2C_Client_Number' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Message.

Definition Message'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "MessageType"%go go.uint64);
  (go.FieldDecl "C2S_Client_Id"%go go.uint64);
  (go.FieldDecl "C2S_Server_Id"%go go.uint64);
  (go.FieldDecl "C2S_Client_OperationType"%go go.uint64);
  (go.FieldDecl "C2S_Client_Add"%go go.bool);
  (go.FieldDecl "C2S_Client_Keys"%go (go.SliceType go.uint64));
  (go.FieldDecl "C2S_Client_Val"%go go.uint64);
  (go.FieldDecl "C2S_Client_VersionVector"%go (go.SliceType go.uint64));
  (go.FieldDecl "S2S_Gossip_Sending_ServerId"%go go.uint64);
  (go.FieldDecl "S2S_Gossip_Receiving_ServerId"%go go.uint64);
  (go.FieldDecl "S2S_Gossip_Operations"%go (go.SliceType Operation));
  (go.FieldDecl "S2S_Gossip_Index"%go go.uint64);
  (go.FieldDecl "S2S_Acknowledge_Gossip_Sending_ServerId"%go go.uint64);
  (go.FieldDecl "S2S_Acknowledge_Gossip_Receiving_ServerId"%go go.uint64);
  (go.FieldDecl "S2S_Acknowledge_Gossip_Index"%go go.uint64);
  (go.FieldDecl "S2C_Client_OperationType"%go go.uint64);
  (go.FieldDecl "S2C_Client_Data"%go (go.MapType go.uint64 (go.SliceType go.uint64)));
  (go.FieldDecl "S2C_Client_VersionVector"%go (go.SliceType go.uint64));
  (go.FieldDecl "S2C_Server_Id"%go go.uint64);
  (go.FieldDecl "S2C_Client_Number"%go go.uint64)
].
Program Definition Message'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Message'fds_unsealed).
Global Instance equals_unfold_Message {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Message'fds =→ Message'fds_unsealed.
Proof. rewrite /Message'fds seal_eq //. Qed.

Definition Messageⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Message'fds).

Class Message_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Message_type_repr  :: go.TypeReprUnderlying Messageⁱᵐᵖˡ Message.t;
  #[global] Message_underlying :: (Message) <u (Messageⁱᵐᵖˡ);
  #[global] Message_get_MessageType (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "MessageType", #x⟧ ⤳[under] #x.(Message.MessageType');
  #[global] Message_set_MessageType (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "MessageType", (#x, #y)⟧ ⤳[under] #(x <|Message.MessageType' := y|>);
  #[global] Message_get_C2S_Client_Id (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_Id", #x⟧ ⤳[under] #x.(Message.C2S_Client_Id');
  #[global] Message_set_C2S_Client_Id (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_Id", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_Id' := y|>);
  #[global] Message_get_C2S_Server_Id (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Server_Id", #x⟧ ⤳[under] #x.(Message.C2S_Server_Id');
  #[global] Message_set_C2S_Server_Id (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Server_Id", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Server_Id' := y|>);
  #[global] Message_get_C2S_Client_OperationType (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_OperationType", #x⟧ ⤳[under] #x.(Message.C2S_Client_OperationType');
  #[global] Message_set_C2S_Client_OperationType (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_OperationType", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_OperationType' := y|>);
  #[global] Message_get_C2S_Client_Add (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_Add", #x⟧ ⤳[under] #x.(Message.C2S_Client_Add');
  #[global] Message_set_C2S_Client_Add (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_Add", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_Add' := y|>);
  #[global] Message_get_C2S_Client_Keys (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_Keys", #x⟧ ⤳[under] #x.(Message.C2S_Client_Keys');
  #[global] Message_set_C2S_Client_Keys (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_Keys", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_Keys' := y|>);
  #[global] Message_get_C2S_Client_Val (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_Val", #x⟧ ⤳[under] #x.(Message.C2S_Client_Val');
  #[global] Message_set_C2S_Client_Val (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_Val", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_Val' := y|>);
  #[global] Message_get_C2S_Client_VersionVector (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "C2S_Client_VersionVector", #x⟧ ⤳[under] #x.(Message.C2S_Client_VersionVector');
  #[global] Message_set_C2S_Client_VersionVector (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "C2S_Client_VersionVector", (#x, #y)⟧ ⤳[under] #(x <|Message.C2S_Client_VersionVector' := y|>);
  #[global] Message_get_S2S_Gossip_Sending_ServerId (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Gossip_Sending_ServerId", #x⟧ ⤳[under] #x.(Message.S2S_Gossip_Sending_ServerId');
  #[global] Message_set_S2S_Gossip_Sending_ServerId (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Gossip_Sending_ServerId", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Gossip_Sending_ServerId' := y|>);
  #[global] Message_get_S2S_Gossip_Receiving_ServerId (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Gossip_Receiving_ServerId", #x⟧ ⤳[under] #x.(Message.S2S_Gossip_Receiving_ServerId');
  #[global] Message_set_S2S_Gossip_Receiving_ServerId (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Gossip_Receiving_ServerId", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Gossip_Receiving_ServerId' := y|>);
  #[global] Message_get_S2S_Gossip_Operations (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Gossip_Operations", #x⟧ ⤳[under] #x.(Message.S2S_Gossip_Operations');
  #[global] Message_set_S2S_Gossip_Operations (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Gossip_Operations", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Gossip_Operations' := y|>);
  #[global] Message_get_S2S_Gossip_Index (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Gossip_Index", #x⟧ ⤳[under] #x.(Message.S2S_Gossip_Index');
  #[global] Message_set_S2S_Gossip_Index (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Gossip_Index", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Gossip_Index' := y|>);
  #[global] Message_get_S2S_Acknowledge_Gossip_Sending_ServerId (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Sending_ServerId", #x⟧ ⤳[under] #x.(Message.S2S_Acknowledge_Gossip_Sending_ServerId');
  #[global] Message_set_S2S_Acknowledge_Gossip_Sending_ServerId (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Sending_ServerId", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Acknowledge_Gossip_Sending_ServerId' := y|>);
  #[global] Message_get_S2S_Acknowledge_Gossip_Receiving_ServerId (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Receiving_ServerId", #x⟧ ⤳[under] #x.(Message.S2S_Acknowledge_Gossip_Receiving_ServerId');
  #[global] Message_set_S2S_Acknowledge_Gossip_Receiving_ServerId (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Receiving_ServerId", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Acknowledge_Gossip_Receiving_ServerId' := y|>);
  #[global] Message_get_S2S_Acknowledge_Gossip_Index (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Index", #x⟧ ⤳[under] #x.(Message.S2S_Acknowledge_Gossip_Index');
  #[global] Message_set_S2S_Acknowledge_Gossip_Index (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2S_Acknowledge_Gossip_Index", (#x, #y)⟧ ⤳[under] #(x <|Message.S2S_Acknowledge_Gossip_Index' := y|>);
  #[global] Message_get_S2C_Client_OperationType (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Client_OperationType", #x⟧ ⤳[under] #x.(Message.S2C_Client_OperationType');
  #[global] Message_set_S2C_Client_OperationType (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Client_OperationType", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Client_OperationType' := y|>);
  #[global] Message_get_S2C_Client_Data (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Client_Data", #x⟧ ⤳[under] #x.(Message.S2C_Client_Data');
  #[global] Message_set_S2C_Client_Data (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Client_Data", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Client_Data' := y|>);
  #[global] Message_get_S2C_Client_VersionVector (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Client_VersionVector", #x⟧ ⤳[under] #x.(Message.S2C_Client_VersionVector');
  #[global] Message_set_S2C_Client_VersionVector (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Client_VersionVector", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Client_VersionVector' := y|>);
  #[global] Message_get_S2C_Server_Id (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Server_Id", #x⟧ ⤳[under] #x.(Message.S2C_Server_Id');
  #[global] Message_set_S2C_Server_Id (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Server_Id", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Server_Id' := y|>);
  #[global] Message_get_S2C_Client_Number (x : Message.t) :: ⟦StructFieldGet (Messageⁱᵐᵖˡ) "S2C_Client_Number", #x⟧ ⤳[under] #x.(Message.S2C_Client_Number');
  #[global] Message_set_S2C_Client_Number (x : Message.t) y :: ⟦StructFieldSet (Messageⁱᵐᵖˡ) "S2C_Client_Number", (#x, #y)⟧ ⤳[under] #(x <|Message.S2C_Client_Number' := y|>);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Post_instance :: Post_Assumptions;
  #[global] Connection_instance :: Connection_Assumptions;
  #[global] Operation_instance :: Operation_Assumptions;
  #[global] Message_instance :: Message_Assumptions;
  #[global] ProcessAddressString_unfold :: FuncUnfold ProcessAddressString [] (ProcessAddressStringⁱᵐᵖˡ);
  #[global] import_strconv_Assumption :: strconv.Assumptions;
  #[global] import_strings_Assumption :: strings.Assumptions;
}.
End common.
