(* autogenerated from social-media-library/wrappers *)
Require Export New.code.social_media_library.client.
Require Export New.code.social_media_library.common.
From New.golang Require Import defn.
Module pkg_id.
Definition wrappers : go_string := "social-media-library/wrappers".

End pkg_id.
Export pkg_id.
Module wrappers.

Definition Wrapper {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/wrappers.Wrapper"%go [].

#[global] Opaque Wrapper.

Definition WrapInput {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/wrappers.WrapInput"%go [].

#[global] Opaque WrapInput.

Definition WrapRequest {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "social-media-library/wrappers.WrapRequest"%go [].

#[global] Opaque WrapRequest.

Definition NewWrapper {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "social-media-library/wrappers.NewWrapper"%go.

(* go: wrapper.go:38:6 *)
Definition NewWrapperⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "id" "sessionSemantic" "servers",
    exception_do (let: "servers" := (GoAlloc (go.SliceType (go.PointerType common.Connection)) "servers") in
    let: "sessionSemantic" := (GoAlloc go.uint64 "sessionSemantic") in
    let: "id" := (GoAlloc go.uint64 "id") in
    return: (GoAlloc Wrapper (let: "$v0" := (let: "$v0" := (![go.uint64] "id") in
     let: "$v1" := (Convert go.int go.uint64 (let: "$a0" := (![go.SliceType (go.PointerType common.Connection)] "servers") in
     (FuncResolve go.len [go.SliceType (go.PointerType common.Connection)] #()) "$a0")) in
     let: "$v2" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) (let: "$a0" := (![go.SliceType (go.PointerType common.Connection)] "servers") in
     (FuncResolve go.len [go.SliceType (go.PointerType common.Connection)] #()) "$a0")) in
     let: "$v3" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) (let: "$a0" := (![go.SliceType (go.PointerType common.Connection)] "servers") in
     (FuncResolve go.len [go.SliceType (go.PointerType common.Connection)] #()) "$a0")) in
     let: "$v4" := (![go.uint64] "sessionSemantic") in
     let: "$v5" := #false in
     CompositeLiteral client.Client (LiteralValue [KeyedElement (Some (KeyField "Id"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "NumberOfServers"%go)) (ElementExpression go.uint64 "$v1"); KeyedElement (Some (KeyField "WriteVersionVector"%go)) (ElementExpression (go.SliceType go.uint64) "$v2"); KeyedElement (Some (KeyField "ReadVersionVector"%go)) (ElementExpression (go.SliceType go.uint64) "$v3"); KeyedElement (Some (KeyField "SessionSemantic"%go)) (ElementExpression go.uint64 "$v4"); KeyedElement (Some (KeyField "Pending"%go)) (ElementExpression go.bool "$v5")])) in
     CompositeLiteral Wrapper (LiteralValue [KeyedElement (Some (KeyField "Client"%go)) (ElementExpression client.Client "$v0")])))).

(* go: wrapper.go:51:19 *)
Definition Wrapper__Pcⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "w" <>,
    exception_do (let: "w" := (GoAlloc (go.PointerType Wrapper) "w") in
    (if: ![go.bool] (StructFieldRef client.Client "Pending"%go (StructFieldRef Wrapper "Client"%go (![go.PointerType Wrapper] "w")))
    then
      (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef client.Message "MessageType"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")))) =⟨go.uint64⟩ #(W64 0))
      then
        (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef client.Message "C2S_Client_OperationType"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")))) =⟨go.uint64⟩ #(W64 0))
        then
          return: (let: "$v0" := #(W64 1) in
           let: "$v1" := (![go.uint64] (StructFieldRef client.Message "C2S_Server_Id"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")))) in
           let: "$v2" := (![go.SliceType go.uint64] (StructFieldRef client.Message "C2S_Client_Keys"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")))) in
           CompositeLiteral WrapRequest (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "ReadServer"%go)) (ElementExpression go.uint64 "$v1"); KeyedElement (Some (KeyField "ReadKeys"%go)) (ElementExpression (go.SliceType go.uint64) "$v2")]))
        else
          (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef client.Message "C2S_Client_OperationType"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")))) =⟨go.uint64⟩ #(W64 1))
          then
            let: "writeKey" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
            (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.uint64] (StructFieldRef client.Message "C2S_Client_Keys"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")))) in
            (FuncResolve go.len [go.SliceType go.uint64] #()) "$a0") >⟨go.int⟩ #(W64 0))
            then
              let: "$r0" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] (StructFieldRef client.Message "C2S_Client_Keys"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w"))), #(W64 0)))) in
              do:  ("writeKey" <-[go.uint64] "$r0")
            else do:  #());;;
            return: (let: "$v0" := #(W64 2) in
             let: "$v1" := (![go.uint64] (StructFieldRef client.Message "C2S_Server_Id"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")))) in
             let: "$v2" := (![go.bool] (StructFieldRef client.Message "C2S_Client_Add"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")))) in
             let: "$v3" := (![go.uint64] "writeKey") in
             let: "$v4" := (![go.uint64] (StructFieldRef client.Message "C2S_Client_Val"%go (StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")))) in
             CompositeLiteral WrapRequest (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "WriteServer"%go)) (ElementExpression go.uint64 "$v1"); KeyedElement (Some (KeyField "WriteAdd"%go)) (ElementExpression go.bool "$v2"); KeyedElement (Some (KeyField "WriteKey"%go)) (ElementExpression go.uint64 "$v3"); KeyedElement (Some (KeyField "WriteValue"%go)) (ElementExpression go.uint64 "$v4")]))
          else do:  #()))
      else do:  #())
    else do:  #());;;
    return: (let: "$v0" := #(W64 0) in
     CompositeLiteral WrapRequest (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0")]))).

(* go: wrapper.go:79:19 *)
Definition Wrapper__Doⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "w" "inp",
    exception_do (let: "w" := (GoAlloc (go.PointerType Wrapper) "w") in
    let: "inp" := (GoAlloc WrapInput "inp") in
    let: "reqType" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "serverId" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "add" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: "keys" := (GoAlloc (go.SliceType go.uint64) (GoZeroVal (go.SliceType go.uint64) #())) in
    let: "val" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "ackMsg" := (GoAlloc client.Message (GoZeroVal client.Message #())) in
    (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef WrapInput "Type"%go "inp")) =⟨go.uint64⟩ #(W64 1))
    then
      let: "$r0" := #(W64 0) in
      do:  ("reqType" <-[go.uint64] "$r0");;;
      let: "$r0" := (![go.SliceType go.uint64] (StructFieldRef WrapInput "RdRqKeys"%go "inp")) in
      do:  ("keys" <-[go.SliceType go.uint64] "$r0");;;
      let: "$r0" := ((![go.uint64] (StructFieldRef client.Client "Id"%go (StructFieldRef Wrapper "Client"%go (![go.PointerType Wrapper] "w")))) %⟨go.uint64⟩ (![go.uint64] (StructFieldRef client.Client "NumberOfServers"%go (StructFieldRef Wrapper "Client"%go (![go.PointerType Wrapper] "w"))))) in
      do:  ("serverId" <-[go.uint64] "$r0")
    else
      (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef WrapInput "Type"%go "inp")) =⟨go.uint64⟩ #(W64 2))
      then
        let: "$r0" := #(W64 1) in
        do:  ("reqType" <-[go.uint64] "$r0");;;
        let: "$r0" := (![go.bool] (StructFieldRef WrapInput "WrRqAdd"%go "inp")) in
        do:  ("add" <-[go.bool] "$r0");;;
        let: "$r0" := (let: "$v0" := (![go.uint64] (StructFieldRef WrapInput "WrRqKey"%go "inp")) in
        CompositeLiteral (go.SliceType go.uint64) (LiteralValue [KeyedElement None (ElementExpression go.uint64 "$v0")])) in
        do:  ("keys" <-[go.SliceType go.uint64] "$r0");;;
        let: "$r0" := (![go.uint64] (StructFieldRef WrapInput "WrRqVal"%go "inp")) in
        do:  ("val" <-[go.uint64] "$r0");;;
        let: "$r0" := ((![go.uint64] (StructFieldRef client.Client "Id"%go (StructFieldRef Wrapper "Client"%go (![go.PointerType Wrapper] "w")))) %⟨go.uint64⟩ (![go.uint64] (StructFieldRef client.Client "NumberOfServers"%go (StructFieldRef Wrapper "Client"%go (![go.PointerType Wrapper] "w"))))) in
        do:  ("serverId" <-[go.uint64] "$r0")
      else
        (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef WrapInput "Type"%go "inp")) =⟨go.uint64⟩ #(W64 3))
        then
          let: "$r0" := #(W64 2) in
          do:  ("reqType" <-[go.uint64] "$r0");;;
          let: "$r0" := (let: "$v0" := #(W64 4) in
          let: "$v1" := #(W64 0) in
          let: "$v2" := (![go.MapType go.uint64 (go.SliceType go.uint64)] (StructFieldRef WrapInput "RdRsVal"%go "inp")) in
          let: "$v3" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) (![go.uint64] (StructFieldRef client.Client "NumberOfServers"%go (StructFieldRef Wrapper "Client"%go (![go.PointerType Wrapper] "w"))))) in
          CompositeLiteral client.Message (LiteralValue [KeyedElement (Some (KeyField "MessageType"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "S2C_Client_OperationType"%go)) (ElementExpression go.uint64 "$v1"); KeyedElement (Some (KeyField "S2C_Client_Data"%go)) (ElementExpression (go.MapType go.uint64 (go.SliceType go.uint64)) "$v2"); KeyedElement (Some (KeyField "S2C_Client_VersionVector"%go)) (ElementExpression (go.SliceType go.uint64) "$v3")])) in
          do:  ("ackMsg" <-[client.Message] "$r0")
        else
          (if: Convert go.untyped_bool go.bool ((![go.uint64] (StructFieldRef WrapInput "Type"%go "inp")) =⟨go.uint64⟩ #(W64 4))
          then
            let: "$r0" := #(W64 2) in
            do:  ("reqType" <-[go.uint64] "$r0");;;
            let: "$r0" := (let: "$v0" := #(W64 4) in
            let: "$v1" := #(W64 1) in
            let: "$v2" := ((FuncResolve go.make2 [go.SliceType go.uint64] #()) (![go.uint64] (StructFieldRef client.Client "NumberOfServers"%go (StructFieldRef Wrapper "Client"%go (![go.PointerType Wrapper] "w"))))) in
            CompositeLiteral client.Message (LiteralValue [KeyedElement (Some (KeyField "MessageType"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "S2C_Client_OperationType"%go)) (ElementExpression go.uint64 "$v1"); KeyedElement (Some (KeyField "S2C_Client_VersionVector"%go)) (ElementExpression (go.SliceType go.uint64) "$v2")])) in
            do:  ("ackMsg" <-[client.Message] "$r0")
          else return: (![go.PointerType Wrapper] "w", #false, #false, Convert go.untyped_nil (go.MapType go.uint64 (go.SliceType go.uint64)) UntypedNil)))));;;
    let: "ret" := (GoAlloc (go.MapType go.uint64 (go.SliceType go.uint64)) (GoZeroVal (go.MapType go.uint64 (go.SliceType go.uint64)) #())) in
    let: "is_val" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: "is_ret" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: "msg" := (GoAlloc client.Message (GoZeroVal client.Message #())) in
    let: "nc" := (GoAlloc client.Client (GoZeroVal client.Client #())) in
    let: (((("$ret0", "$ret1"), "$ret2"), "$ret3"), "$ret4") := (let: "$a0" := (![client.Client] (StructFieldRef Wrapper "Client"%go (![go.PointerType Wrapper] "w"))) in
    let: "$a1" := (![go.uint64] "reqType") in
    let: "$a2" := (![go.uint64] "serverId") in
    let: "$a3" := (![go.bool] "add") in
    let: "$a4" := (![go.SliceType go.uint64] "keys") in
    let: "$a5" := (![go.uint64] "val") in
    let: "$a6" := (![client.Message] "ackMsg") in
    (FuncResolve client.ProcessRequest [] #()) "$a0" "$a1" "$a2" "$a3" "$a4" "$a5" "$a6") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    let: "$r2" := "$ret2" in
    let: "$r3" := "$ret3" in
    let: "$r4" := "$ret4" in
    do:  ("nc" <-[client.Client] "$r0");;;
    do:  ("msg" <-[client.Message] "$r1");;;
    do:  ("is_ret" <-[go.bool] "$r2");;;
    do:  ("is_val" <-[go.bool] "$r3");;;
    do:  ("ret" <-[go.MapType go.uint64 (go.SliceType go.uint64)] "$r4");;;
    let: "$r0" := (![client.Client] "nc") in
    do:  ((StructFieldRef Wrapper "Client"%go (![go.PointerType Wrapper] "w")) <-[client.Client] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.uint64] "reqType") ≠⟨go.uint64⟩ #(W64 2))
    then
      let: "$r0" := (![client.Message] "msg") in
      do:  ((StructFieldRef Wrapper "Msg"%go (![go.PointerType Wrapper] "w")) <-[client.Message] "$r0")
    else do:  #());;;
    return: (![go.PointerType Wrapper] "w", ![go.bool] "is_ret", ![go.bool] "is_val", ![go.MapType go.uint64 (go.SliceType go.uint64)] "ret")).

#[global] Instance info' : PkgInfo pkg_id.wrappers :=
{|
  pkg_imported_pkgs := [code.social_media_library.client.pkg_id.client; code.social_media_library.common.pkg_id.common]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.wrappers (λ: <>,
      exception_do (do:  (common.initialize' #());;;
      do:  (client.initialize' #()))
      ).

Module Wrapper.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  Client' : client.Client.t;
  Msg' : client.Message.t;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Wrapper.

Definition Wrapper'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "Client"%go client.Client);
  (go.FieldDecl "Msg"%go client.Message)
].
Program Definition Wrapper'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Wrapper'fds_unsealed).
Global Instance equals_unfold_Wrapper {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Wrapper'fds =→ Wrapper'fds_unsealed.
Proof. rewrite /Wrapper'fds seal_eq //. Qed.

Definition Wrapperⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Wrapper'fds).

Class Wrapper_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Wrapper_type_repr  :: go.TypeReprUnderlying Wrapperⁱᵐᵖˡ Wrapper.t;
  #[global] Wrapper_underlying :: (Wrapper) <u (Wrapperⁱᵐᵖˡ);
  #[global] Wrapper_get_Client (x : Wrapper.t) :: ⟦StructFieldGet (Wrapperⁱᵐᵖˡ) "Client", #x⟧ ⤳[under] #x.(Wrapper.Client');
  #[global] Wrapper_set_Client (x : Wrapper.t) y :: ⟦StructFieldSet (Wrapperⁱᵐᵖˡ) "Client", (#x, #y)⟧ ⤳[under] #(x <|Wrapper.Client' := y|>);
  #[global] Wrapper_get_Msg (x : Wrapper.t) :: ⟦StructFieldGet (Wrapperⁱᵐᵖˡ) "Msg", #x⟧ ⤳[under] #x.(Wrapper.Msg');
  #[global] Wrapper_set_Msg (x : Wrapper.t) y :: ⟦StructFieldSet (Wrapperⁱᵐᵖˡ) "Msg", (#x, #y)⟧ ⤳[under] #(x <|Wrapper.Msg' := y|>);
  #[global] Wrapper'ptr_Do_unfold :: MethodUnfold (go.PointerType (Wrapper)) "Do" (Wrapper__Doⁱᵐᵖˡ);
  #[global] Wrapper'ptr_Pc_unfold :: MethodUnfold (go.PointerType (Wrapper)) "Pc" (Wrapper__Pcⁱᵐᵖˡ);
}.

Module WrapInput.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  Type' : w64;
  RdRqKeys' : slice.t;
  WrRqAdd' : bool;
  WrRqKey' : w64;
  WrRqVal' : w64;
  RdRsVal' : map.t;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End WrapInput.

Definition WrapInput'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "Type"%go go.uint64);
  (go.FieldDecl "RdRqKeys"%go (go.SliceType go.uint64));
  (go.FieldDecl "WrRqAdd"%go go.bool);
  (go.FieldDecl "WrRqKey"%go go.uint64);
  (go.FieldDecl "WrRqVal"%go go.uint64);
  (go.FieldDecl "RdRsVal"%go (go.MapType go.uint64 (go.SliceType go.uint64)))
].
Program Definition WrapInput'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (WrapInput'fds_unsealed).
Global Instance equals_unfold_WrapInput {ext : ffi_syntax} {go_gctx : GoGlobalContext} : WrapInput'fds =→ WrapInput'fds_unsealed.
Proof. rewrite /WrapInput'fds seal_eq //. Qed.

Definition WrapInputⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (WrapInput'fds).

Class WrapInput_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] WrapInput_type_repr  :: go.TypeReprUnderlying WrapInputⁱᵐᵖˡ WrapInput.t;
  #[global] WrapInput_underlying :: (WrapInput) <u (WrapInputⁱᵐᵖˡ);
  #[global] WrapInput_get_Type (x : WrapInput.t) :: ⟦StructFieldGet (WrapInputⁱᵐᵖˡ) "Type", #x⟧ ⤳[under] #x.(WrapInput.Type');
  #[global] WrapInput_set_Type (x : WrapInput.t) y :: ⟦StructFieldSet (WrapInputⁱᵐᵖˡ) "Type", (#x, #y)⟧ ⤳[under] #(x <|WrapInput.Type' := y|>);
  #[global] WrapInput_get_RdRqKeys (x : WrapInput.t) :: ⟦StructFieldGet (WrapInputⁱᵐᵖˡ) "RdRqKeys", #x⟧ ⤳[under] #x.(WrapInput.RdRqKeys');
  #[global] WrapInput_set_RdRqKeys (x : WrapInput.t) y :: ⟦StructFieldSet (WrapInputⁱᵐᵖˡ) "RdRqKeys", (#x, #y)⟧ ⤳[under] #(x <|WrapInput.RdRqKeys' := y|>);
  #[global] WrapInput_get_WrRqAdd (x : WrapInput.t) :: ⟦StructFieldGet (WrapInputⁱᵐᵖˡ) "WrRqAdd", #x⟧ ⤳[under] #x.(WrapInput.WrRqAdd');
  #[global] WrapInput_set_WrRqAdd (x : WrapInput.t) y :: ⟦StructFieldSet (WrapInputⁱᵐᵖˡ) "WrRqAdd", (#x, #y)⟧ ⤳[under] #(x <|WrapInput.WrRqAdd' := y|>);
  #[global] WrapInput_get_WrRqKey (x : WrapInput.t) :: ⟦StructFieldGet (WrapInputⁱᵐᵖˡ) "WrRqKey", #x⟧ ⤳[under] #x.(WrapInput.WrRqKey');
  #[global] WrapInput_set_WrRqKey (x : WrapInput.t) y :: ⟦StructFieldSet (WrapInputⁱᵐᵖˡ) "WrRqKey", (#x, #y)⟧ ⤳[under] #(x <|WrapInput.WrRqKey' := y|>);
  #[global] WrapInput_get_WrRqVal (x : WrapInput.t) :: ⟦StructFieldGet (WrapInputⁱᵐᵖˡ) "WrRqVal", #x⟧ ⤳[under] #x.(WrapInput.WrRqVal');
  #[global] WrapInput_set_WrRqVal (x : WrapInput.t) y :: ⟦StructFieldSet (WrapInputⁱᵐᵖˡ) "WrRqVal", (#x, #y)⟧ ⤳[under] #(x <|WrapInput.WrRqVal' := y|>);
  #[global] WrapInput_get_RdRsVal (x : WrapInput.t) :: ⟦StructFieldGet (WrapInputⁱᵐᵖˡ) "RdRsVal", #x⟧ ⤳[under] #x.(WrapInput.RdRsVal');
  #[global] WrapInput_set_RdRsVal (x : WrapInput.t) y :: ⟦StructFieldSet (WrapInputⁱᵐᵖˡ) "RdRsVal", (#x, #y)⟧ ⤳[under] #(x <|WrapInput.RdRsVal' := y|>);
}.

Module WrapRequest.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  Type' : w64;
  ReadServer' : w64;
  WriteServer' : w64;
  WriteValue' : w64;
  ReadKeys' : slice.t;
  WriteAdd' : bool;
  WriteKey' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End WrapRequest.

Definition WrapRequest'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "Type"%go go.uint64);
  (go.FieldDecl "ReadServer"%go go.uint64);
  (go.FieldDecl "WriteServer"%go go.uint64);
  (go.FieldDecl "WriteValue"%go go.uint64);
  (go.FieldDecl "ReadKeys"%go (go.SliceType go.uint64));
  (go.FieldDecl "WriteAdd"%go go.bool);
  (go.FieldDecl "WriteKey"%go go.uint64)
].
Program Definition WrapRequest'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (WrapRequest'fds_unsealed).
Global Instance equals_unfold_WrapRequest {ext : ffi_syntax} {go_gctx : GoGlobalContext} : WrapRequest'fds =→ WrapRequest'fds_unsealed.
Proof. rewrite /WrapRequest'fds seal_eq //. Qed.

Definition WrapRequestⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (WrapRequest'fds).

Class WrapRequest_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] WrapRequest_type_repr  :: go.TypeReprUnderlying WrapRequestⁱᵐᵖˡ WrapRequest.t;
  #[global] WrapRequest_underlying :: (WrapRequest) <u (WrapRequestⁱᵐᵖˡ);
  #[global] WrapRequest_get_Type (x : WrapRequest.t) :: ⟦StructFieldGet (WrapRequestⁱᵐᵖˡ) "Type", #x⟧ ⤳[under] #x.(WrapRequest.Type');
  #[global] WrapRequest_set_Type (x : WrapRequest.t) y :: ⟦StructFieldSet (WrapRequestⁱᵐᵖˡ) "Type", (#x, #y)⟧ ⤳[under] #(x <|WrapRequest.Type' := y|>);
  #[global] WrapRequest_get_ReadServer (x : WrapRequest.t) :: ⟦StructFieldGet (WrapRequestⁱᵐᵖˡ) "ReadServer", #x⟧ ⤳[under] #x.(WrapRequest.ReadServer');
  #[global] WrapRequest_set_ReadServer (x : WrapRequest.t) y :: ⟦StructFieldSet (WrapRequestⁱᵐᵖˡ) "ReadServer", (#x, #y)⟧ ⤳[under] #(x <|WrapRequest.ReadServer' := y|>);
  #[global] WrapRequest_get_WriteServer (x : WrapRequest.t) :: ⟦StructFieldGet (WrapRequestⁱᵐᵖˡ) "WriteServer", #x⟧ ⤳[under] #x.(WrapRequest.WriteServer');
  #[global] WrapRequest_set_WriteServer (x : WrapRequest.t) y :: ⟦StructFieldSet (WrapRequestⁱᵐᵖˡ) "WriteServer", (#x, #y)⟧ ⤳[under] #(x <|WrapRequest.WriteServer' := y|>);
  #[global] WrapRequest_get_WriteValue (x : WrapRequest.t) :: ⟦StructFieldGet (WrapRequestⁱᵐᵖˡ) "WriteValue", #x⟧ ⤳[under] #x.(WrapRequest.WriteValue');
  #[global] WrapRequest_set_WriteValue (x : WrapRequest.t) y :: ⟦StructFieldSet (WrapRequestⁱᵐᵖˡ) "WriteValue", (#x, #y)⟧ ⤳[under] #(x <|WrapRequest.WriteValue' := y|>);
  #[global] WrapRequest_get_ReadKeys (x : WrapRequest.t) :: ⟦StructFieldGet (WrapRequestⁱᵐᵖˡ) "ReadKeys", #x⟧ ⤳[under] #x.(WrapRequest.ReadKeys');
  #[global] WrapRequest_set_ReadKeys (x : WrapRequest.t) y :: ⟦StructFieldSet (WrapRequestⁱᵐᵖˡ) "ReadKeys", (#x, #y)⟧ ⤳[under] #(x <|WrapRequest.ReadKeys' := y|>);
  #[global] WrapRequest_get_WriteAdd (x : WrapRequest.t) :: ⟦StructFieldGet (WrapRequestⁱᵐᵖˡ) "WriteAdd", #x⟧ ⤳[under] #x.(WrapRequest.WriteAdd');
  #[global] WrapRequest_set_WriteAdd (x : WrapRequest.t) y :: ⟦StructFieldSet (WrapRequestⁱᵐᵖˡ) "WriteAdd", (#x, #y)⟧ ⤳[under] #(x <|WrapRequest.WriteAdd' := y|>);
  #[global] WrapRequest_get_WriteKey (x : WrapRequest.t) :: ⟦StructFieldGet (WrapRequestⁱᵐᵖˡ) "WriteKey", #x⟧ ⤳[under] #x.(WrapRequest.WriteKey');
  #[global] WrapRequest_set_WriteKey (x : WrapRequest.t) y :: ⟦StructFieldSet (WrapRequestⁱᵐᵖˡ) "WriteKey", (#x, #y)⟧ ⤳[under] #(x <|WrapRequest.WriteKey' := y|>);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Wrapper_instance :: Wrapper_Assumptions;
  #[global] WrapInput_instance :: WrapInput_Assumptions;
  #[global] WrapRequest_instance :: WrapRequest_Assumptions;
  #[global] NewWrapper_unfold :: FuncUnfold NewWrapper [] (NewWrapperⁱᵐᵖˡ);
  #[global] import_client_Assumption :: client.Assumptions;
  #[global] import_common_Assumption :: common.Assumptions;
}.
End wrappers.
