(* autogenerated from github.com/goose-lang/goose/testdata/examples/wal *)
Require Export New.code.sync.
Require Export New.code.github_com.goose_lang.primitive.
Require Export New.code.github_com.goose_lang.primitive.disk.
From New.golang Require Import defn.
From New Require Import disk_prelude.
Module pkg_id.
Definition awol : go_string := "github.com/goose-lang/goose/testdata/examples/wal".

End pkg_id.
Export pkg_id.
Module awol.

Definition Log {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/goose-lang/goose/testdata/examples/wal.Log"%go [].

(* 10 is completely arbitrary *)
Definition MaxTxnWrites {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 10).

Definition logLength {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 21).

Definition intToBlock {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/goose-lang/goose/testdata/examples/wal.intToBlock"%go.

Definition blockToInt {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/goose-lang/goose/testdata/examples/wal.blockToInt"%go.

Definition New {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/goose-lang/goose/testdata/examples/wal.New"%go.

Definition getLogEntry {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/goose-lang/goose/testdata/examples/wal.getLogEntry"%go.

Definition applyLog {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/goose-lang/goose/testdata/examples/wal.applyLog"%go.

Definition clearLog {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/goose-lang/goose/testdata/examples/wal.clearLog"%go.

Definition Open {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/goose-lang/goose/testdata/examples/wal.Open"%go.

(* go: log.go:25:6 *)
Definition intToBlockⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "a",
    exception_do (let: "a" := (GoAlloc go.uint64 "a") in
    let: "b" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "$r0" := ((FuncResolve go.make2 [go.SliceType go.byte] #()) disk.BlockSize) in
    do:  ("b" <-[go.SliceType go.byte] "$r0");;;
    do:  (let: "$a0" := (![go.SliceType go.byte] "b") in
    let: "$a1" := (![go.uint64] "a") in
    (FuncResolve primitive.UInt64Put [] #()) "$a0" "$a1");;;
    return: (![go.SliceType go.byte] "b")).

(* go: log.go:31:6 *)
Definition blockToIntⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "v",
    exception_do (let: "v" := (GoAlloc disk.Block "v") in
    let: "a" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (let: "$a0" := (![disk.Block] "v") in
    (FuncResolve primitive.UInt64Get [] #()) "$a0") in
    do:  ("a" <-[go.uint64] "$r0");;;
    return: (![go.uint64] "a")).

(* New initializes a fresh log

   go: log.go:37:6 *)
Definition Newⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "d" := (GoAlloc disk.Disk (GoZeroVal disk.Disk #())) in
    let: "$r0" := ((FuncResolve disk.Get [] #()) #()) in
    do:  ("d" <-[disk.Disk] "$r0");;;
    let: "diskSize" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := ((MethodResolve disk.Disk "Size"%go (![disk.Disk] "d")) #()) in
    do:  ("diskSize" <-[go.uint64] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.uint64] "diskSize") ≤⟨go.uint64⟩ logLength)
    then
      do:  (let: "$a0" := (Convert go.string (go.InterfaceType []) #"disk is too small to host log"%go) in
      (FuncResolve go.panic [] #()) "$a0")
    else do:  #());;;
    let: "cache" := (GoAlloc (go.MapType go.uint64 disk.Block) (GoZeroVal (go.MapType go.uint64 disk.Block) #())) in
    let: "$r0" := ((FuncResolve go.make1 [go.MapType go.uint64 disk.Block] #()) #()) in
    do:  ("cache" <-[go.MapType go.uint64 disk.Block] "$r0");;;
    let: "header" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
    let: "$r0" := (let: "$a0" := #(W64 0) in
    (FuncResolve intToBlock [] #()) "$a0") in
    do:  ("header" <-[disk.Block] "$r0");;;
    do:  (let: "$a0" := #(W64 0) in
    let: "$a1" := (![disk.Block] "header") in
    (MethodResolve disk.Disk "Write"%go (![disk.Disk] "d")) "$a0" "$a1");;;
    let: "lengthPtr" := (GoAlloc (go.PointerType go.uint64) (GoZeroVal (go.PointerType go.uint64) #())) in
    let: "$r0" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    do:  ("lengthPtr" <-[go.PointerType go.uint64] "$r0");;;
    let: "$r0" := #(W64 0) in
    do:  ((![go.PointerType go.uint64] "lengthPtr") <-[go.uint64] "$r0");;;
    let: "l" := (GoAlloc (go.PointerType sync.Mutex) (GoZeroVal (go.PointerType sync.Mutex) #())) in
    let: "$r0" := (GoAlloc sync.Mutex (GoZeroVal sync.Mutex #())) in
    do:  ("l" <-[go.PointerType sync.Mutex] "$r0");;;
    return: (CompositeLiteral Log (LiteralValue [KeyedElement (Some (KeyField "d"%go)) (ElementExpression disk.Disk (![disk.Disk] "d")); KeyedElement (Some (KeyField "cache"%go)) (ElementExpression (go.MapType go.uint64 disk.Block) (![go.MapType go.uint64 disk.Block] "cache")); KeyedElement (Some (KeyField "length"%go)) (ElementExpression (go.PointerType go.uint64) (![go.PointerType go.uint64] "lengthPtr")); KeyedElement (Some (KeyField "l"%go)) (ElementExpression (go.PointerType sync.Mutex) (![go.PointerType sync.Mutex] "l"))]))).

(* go: log.go:52:14 *)
Definition Log__lockⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" <>,
    exception_do (let: "l" := (GoAlloc Log "l") in
    do:  ((MethodResolve (go.PointerType sync.Mutex) "Lock"%go (![go.PointerType sync.Mutex] (StructFieldRef Log "l"%go "l"))) #());;;
    return: #()).

(* go: log.go:56:14 *)
Definition Log__unlockⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" <>,
    exception_do (let: "l" := (GoAlloc Log "l") in
    do:  ((MethodResolve (go.PointerType sync.Mutex) "Unlock"%go (![go.PointerType sync.Mutex] (StructFieldRef Log "l"%go "l"))) #());;;
    return: #()).

(* BeginTxn allocates space for a new transaction in the log.

   Returns true if the allocation succeeded.

   go: log.go:63:14 *)
Definition Log__BeginTxnⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" <>,
    exception_do (let: "l" := (GoAlloc Log "l") in
    do:  ((MethodResolve Log "lock"%go (![Log] "l")) #());;;
    let: "length" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (![go.uint64] (![go.PointerType go.uint64] (StructFieldRef Log "length"%go "l"))) in
    do:  ("length" <-[go.uint64] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.uint64] "length") =⟨go.uint64⟩ #(W64 0))
    then
      do:  ((MethodResolve Log "unlock"%go (![Log] "l")) #());;;
      return: (#true)
    else do:  #());;;
    do:  ((MethodResolve Log "unlock"%go (![Log] "l")) #());;;
    return: (#false)).

(* Read from the logical disk.

   Reads must go through the log to return committed but un-applied writes.

   go: log.go:77:14 *)
Definition Log__Readⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" "a",
    exception_do (let: "l" := (GoAlloc Log "l") in
    let: "a" := (GoAlloc go.uint64 "a") in
    do:  ((MethodResolve Log "lock"%go (![Log] "l")) #());;;
    let: "ok" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: "v" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
    let: ("$ret0", "$ret1") := (map.lookup2 go.uint64 disk.Block (![go.MapType go.uint64 disk.Block] (StructFieldRef Log "cache"%go "l")) (![go.uint64] "a")) in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("v" <-[disk.Block] "$r0");;;
    do:  ("ok" <-[go.bool] "$r1");;;
    (if: ![go.bool] "ok"
    then
      do:  ((MethodResolve Log "unlock"%go (![Log] "l")) #());;;
      return: (![disk.Block] "v")
    else do:  #());;;
    do:  ((MethodResolve Log "unlock"%go (![Log] "l")) #());;;
    let: "dv" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
    let: "$r0" := (let: "$a0" := (logLength +⟨go.uint64⟩ (![go.uint64] "a")) in
    (MethodResolve disk.Disk "Read"%go (![disk.Disk] (StructFieldRef Log "d"%go "l"))) "$a0") in
    do:  ("dv" <-[disk.Block] "$r0");;;
    return: (![disk.Block] "dv")).

(* go: log.go:90:14 *)
Definition Log__Sizeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" <>,
    exception_do (let: "l" := (GoAlloc Log "l") in
    let: "sz" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := ((MethodResolve disk.Disk "Size"%go (![disk.Disk] (StructFieldRef Log "d"%go "l"))) #()) in
    do:  ("sz" <-[go.uint64] "$r0");;;
    return: ((![go.uint64] "sz") -⟨go.uint64⟩ logLength)).

(* Write to the disk through the log.

   go: log.go:97:14 *)
Definition Log__Writeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" "a" "v",
    exception_do (let: "l" := (GoAlloc Log "l") in
    let: "v" := (GoAlloc disk.Block "v") in
    let: "a" := (GoAlloc go.uint64 "a") in
    do:  ((MethodResolve Log "lock"%go (![Log] "l")) #());;;
    let: "length" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (![go.uint64] (![go.PointerType go.uint64] (StructFieldRef Log "length"%go "l"))) in
    do:  ("length" <-[go.uint64] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.uint64] "length") ≥⟨go.uint64⟩ MaxTxnWrites)
    then
      do:  (let: "$a0" := (Convert go.string (go.InterfaceType []) #"transaction is at capacity"%go) in
      (FuncResolve go.panic [] #()) "$a0")
    else do:  #());;;
    let: "aBlock" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
    let: "$r0" := (let: "$a0" := (![go.uint64] "a") in
    (FuncResolve intToBlock [] #()) "$a0") in
    do:  ("aBlock" <-[disk.Block] "$r0");;;
    let: "nextAddr" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (#(W64 1) +⟨go.uint64⟩ (#(W64 2) *⟨go.uint64⟩ (![go.uint64] "length"))) in
    do:  ("nextAddr" <-[go.uint64] "$r0");;;
    do:  (let: "$a0" := (![go.uint64] "nextAddr") in
    let: "$a1" := (![disk.Block] "aBlock") in
    (MethodResolve disk.Disk "Write"%go (![disk.Disk] (StructFieldRef Log "d"%go "l"))) "$a0" "$a1");;;
    do:  (let: "$a0" := ((![go.uint64] "nextAddr") +⟨go.uint64⟩ #(W64 1)) in
    let: "$a1" := (![disk.Block] "v") in
    (MethodResolve disk.Disk "Write"%go (![disk.Disk] (StructFieldRef Log "d"%go "l"))) "$a0" "$a1");;;
    let: "$r0" := (![disk.Block] "v") in
    do:  (map.insert go.uint64 (![go.MapType go.uint64 disk.Block] (StructFieldRef Log "cache"%go "l")) (![go.uint64] "a") "$r0");;;
    let: "$r0" := ((![go.uint64] "length") +⟨go.uint64⟩ #(W64 1)) in
    do:  ((![go.PointerType go.uint64] (StructFieldRef Log "length"%go "l")) <-[go.uint64] "$r0");;;
    do:  ((MethodResolve Log "unlock"%go (![Log] "l")) #());;;
    return: #()).

(* Commit the current transaction.

   go: log.go:113:14 *)
Definition Log__Commitⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" <>,
    exception_do (let: "l" := (GoAlloc Log "l") in
    do:  ((MethodResolve Log "lock"%go (![Log] "l")) #());;;
    let: "length" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (![go.uint64] (![go.PointerType go.uint64] (StructFieldRef Log "length"%go "l"))) in
    do:  ("length" <-[go.uint64] "$r0");;;
    do:  ((MethodResolve Log "unlock"%go (![Log] "l")) #());;;
    let: "header" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
    let: "$r0" := (let: "$a0" := (![go.uint64] "length") in
    (FuncResolve intToBlock [] #()) "$a0") in
    do:  ("header" <-[disk.Block] "$r0");;;
    do:  (let: "$a0" := #(W64 0) in
    let: "$a1" := (![disk.Block] "header") in
    (MethodResolve disk.Disk "Write"%go (![disk.Disk] (StructFieldRef Log "d"%go "l"))) "$a0" "$a1");;;
    return: #()).

(* go: log.go:122:6 *)
Definition getLogEntryⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "d" "logOffset",
    exception_do (let: "logOffset" := (GoAlloc go.uint64 "logOffset") in
    let: "d" := (GoAlloc disk.Disk "d") in
    let: "diskAddr" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (#(W64 1) +⟨go.uint64⟩ (#(W64 2) *⟨go.uint64⟩ (![go.uint64] "logOffset"))) in
    do:  ("diskAddr" <-[go.uint64] "$r0");;;
    let: "aBlock" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
    let: "$r0" := (let: "$a0" := (![go.uint64] "diskAddr") in
    (MethodResolve disk.Disk "Read"%go (![disk.Disk] "d")) "$a0") in
    do:  ("aBlock" <-[disk.Block] "$r0");;;
    let: "a" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (let: "$a0" := (![disk.Block] "aBlock") in
    (FuncResolve blockToInt [] #()) "$a0") in
    do:  ("a" <-[go.uint64] "$r0");;;
    let: "v" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
    let: "$r0" := (let: "$a0" := ((![go.uint64] "diskAddr") +⟨go.uint64⟩ #(W64 1)) in
    (MethodResolve disk.Disk "Read"%go (![disk.Disk] "d")) "$a0") in
    do:  ("v" <-[disk.Block] "$r0");;;
    return: (![go.uint64] "a", ![disk.Block] "v")).

(* applyLog assumes we are running sequentially

   go: log.go:131:6 *)
Definition applyLogⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "d" "length",
    exception_do (let: "length" := (GoAlloc go.uint64 "length") in
    let: "d" := (GoAlloc disk.Disk "d") in
    (let: "i" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := #(W64 0) in
    do:  ("i" <-[go.uint64] "$r0");;;
    (for: (λ: <>, #true); (λ: <>, #()) := λ: <>,
      (if: Convert go.untyped_bool go.bool ((![go.uint64] "i") <⟨go.uint64⟩ (![go.uint64] "length"))
      then
        let: "v" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
        let: "a" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
        let: ("$ret0", "$ret1") := (let: "$a0" := (![disk.Disk] "d") in
        let: "$a1" := (![go.uint64] "i") in
        (FuncResolve getLogEntry [] #()) "$a0" "$a1") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("a" <-[go.uint64] "$r0");;;
        do:  ("v" <-[disk.Block] "$r1");;;
        do:  (let: "$a0" := (logLength +⟨go.uint64⟩ (![go.uint64] "a")) in
        let: "$a1" := (![disk.Block] "v") in
        (MethodResolve disk.Disk "Write"%go (![disk.Disk] "d")) "$a0" "$a1");;;
        let: "$r0" := ((![go.uint64] "i") +⟨go.uint64⟩ #(W64 1)) in
        do:  ("i" <-[go.uint64] "$r0");;;
        continue: #()
      else do:  #());;;
      break: #()));;;
    return: #()).

(* go: log.go:142:6 *)
Definition clearLogⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "d",
    exception_do (let: "d" := (GoAlloc disk.Disk "d") in
    let: "header" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
    let: "$r0" := (let: "$a0" := #(W64 0) in
    (FuncResolve intToBlock [] #()) "$a0") in
    do:  ("header" <-[disk.Block] "$r0");;;
    do:  (let: "$a0" := #(W64 0) in
    let: "$a1" := (![disk.Block] "header") in
    (MethodResolve disk.Disk "Write"%go (![disk.Disk] "d")) "$a0" "$a1");;;
    return: #()).

(* Apply all the committed transactions.

   Frees all the space in the log.

   go: log.go:150:14 *)
Definition Log__Applyⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" <>,
    exception_do (let: "l" := (GoAlloc Log "l") in
    do:  ((MethodResolve Log "lock"%go (![Log] "l")) #());;;
    let: "length" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (![go.uint64] (![go.PointerType go.uint64] (StructFieldRef Log "length"%go "l"))) in
    do:  ("length" <-[go.uint64] "$r0");;;
    do:  (let: "$a0" := (![disk.Disk] (StructFieldRef Log "d"%go "l")) in
    let: "$a1" := (![go.uint64] "length") in
    (FuncResolve applyLog [] #()) "$a0" "$a1");;;
    do:  (let: "$a0" := (![disk.Disk] (StructFieldRef Log "d"%go "l")) in
    (FuncResolve clearLog [] #()) "$a0");;;
    let: "$r0" := #(W64 0) in
    do:  ((![go.PointerType go.uint64] (StructFieldRef Log "length"%go "l")) <-[go.uint64] "$r0");;;
    do:  ((MethodResolve Log "unlock"%go (![Log] "l")) #());;;
    return: #()).

(* Open recovers the log following a crash or shutdown

   go: log.go:163:6 *)
Definition Openⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "d" := (GoAlloc disk.Disk (GoZeroVal disk.Disk #())) in
    let: "$r0" := ((FuncResolve disk.Get [] #()) #()) in
    do:  ("d" <-[disk.Disk] "$r0");;;
    let: "header" := (GoAlloc disk.Block (GoZeroVal disk.Block #())) in
    let: "$r0" := (let: "$a0" := #(W64 0) in
    (MethodResolve disk.Disk "Read"%go (![disk.Disk] "d")) "$a0") in
    do:  ("header" <-[disk.Block] "$r0");;;
    let: "length" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := (let: "$a0" := (![disk.Block] "header") in
    (FuncResolve blockToInt [] #()) "$a0") in
    do:  ("length" <-[go.uint64] "$r0");;;
    do:  (let: "$a0" := (![disk.Disk] "d") in
    let: "$a1" := (![go.uint64] "length") in
    (FuncResolve applyLog [] #()) "$a0" "$a1");;;
    do:  (let: "$a0" := (![disk.Disk] "d") in
    (FuncResolve clearLog [] #()) "$a0");;;
    let: "cache" := (GoAlloc (go.MapType go.uint64 disk.Block) (GoZeroVal (go.MapType go.uint64 disk.Block) #())) in
    let: "$r0" := ((FuncResolve go.make1 [go.MapType go.uint64 disk.Block] #()) #()) in
    do:  ("cache" <-[go.MapType go.uint64 disk.Block] "$r0");;;
    let: "lengthPtr" := (GoAlloc (go.PointerType go.uint64) (GoZeroVal (go.PointerType go.uint64) #())) in
    let: "$r0" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    do:  ("lengthPtr" <-[go.PointerType go.uint64] "$r0");;;
    let: "$r0" := #(W64 0) in
    do:  ((![go.PointerType go.uint64] "lengthPtr") <-[go.uint64] "$r0");;;
    let: "l" := (GoAlloc (go.PointerType sync.Mutex) (GoZeroVal (go.PointerType sync.Mutex) #())) in
    let: "$r0" := (GoAlloc sync.Mutex (GoZeroVal sync.Mutex #())) in
    do:  ("l" <-[go.PointerType sync.Mutex] "$r0");;;
    return: (CompositeLiteral Log (LiteralValue [KeyedElement (Some (KeyField "d"%go)) (ElementExpression disk.Disk (![disk.Disk] "d")); KeyedElement (Some (KeyField "cache"%go)) (ElementExpression (go.MapType go.uint64 disk.Block) (![go.MapType go.uint64 disk.Block] "cache")); KeyedElement (Some (KeyField "length"%go)) (ElementExpression (go.PointerType go.uint64) (![go.PointerType go.uint64] "lengthPtr")); KeyedElement (Some (KeyField "l"%go)) (ElementExpression (go.PointerType sync.Mutex) (![go.PointerType sync.Mutex] "l"))]))).

#[global] Instance info' : PkgInfo pkg_id.awol :=
{|
  pkg_imported_pkgs := [code.sync.pkg_id.sync; code.github_com.goose_lang.primitive.pkg_id.primitive; code.github_com.goose_lang.primitive.disk.pkg_id.disk]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.awol (λ: <>,
      exception_do (do:  (disk.initialize' #());;;
      do:  (primitive.initialize' #());;;
      do:  (sync.initialize' #()))
      ).

Module Log.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  d' : disk.Disk.t;
  l' : loc;
  cache' : loc;
  length' : loc;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.

End Log.

Definition Logⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType [
  (go.FieldDecl "d"%go disk.Disk);
  (go.FieldDecl "l"%go (go.PointerType sync.Mutex));
  (go.FieldDecl "cache"%go (go.MapType go.uint64 disk.Block));
  (go.FieldDecl "length"%go (go.PointerType go.uint64))
].

Class Log_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Log_type_repr  :: go.TypeRepr Log Log.t;
  #[global] Log_underlying :: (Log) <u (Logⁱᵐᵖˡ);
  #[global] Log_get_d (x : Log.t) :: go.IsGoStepPureDet (StructFieldGet (Log) "d") #x #x.(Log.d');
  #[global] Log_set_d (x : Log.t) y :: go.IsGoStepPureDet (StructFieldSet (Log) "d") (#x, #y) #(x <|Log.d' := y|>);
  #[global] Log_get_l (x : Log.t) :: go.IsGoStepPureDet (StructFieldGet (Log) "l") #x #x.(Log.l');
  #[global] Log_set_l (x : Log.t) y :: go.IsGoStepPureDet (StructFieldSet (Log) "l") (#x, #y) #(x <|Log.l' := y|>);
  #[global] Log_get_cache (x : Log.t) :: go.IsGoStepPureDet (StructFieldGet (Log) "cache") #x #x.(Log.cache');
  #[global] Log_set_cache (x : Log.t) y :: go.IsGoStepPureDet (StructFieldSet (Log) "cache") (#x, #y) #(x <|Log.cache' := y|>);
  #[global] Log_get_length (x : Log.t) :: go.IsGoStepPureDet (StructFieldGet (Log) "length") #x #x.(Log.length');
  #[global] Log_set_length (x : Log.t) y :: go.IsGoStepPureDet (StructFieldSet (Log) "length") (#x, #y) #(x <|Log.length' := y|>);
  #[global] Log_Apply_unfold :: MethodUnfold (Log) "Apply" (Log__Applyⁱᵐᵖˡ);
  #[global] Log_BeginTxn_unfold :: MethodUnfold (Log) "BeginTxn" (Log__BeginTxnⁱᵐᵖˡ);
  #[global] Log_Commit_unfold :: MethodUnfold (Log) "Commit" (Log__Commitⁱᵐᵖˡ);
  #[global] Log_Read_unfold :: MethodUnfold (Log) "Read" (Log__Readⁱᵐᵖˡ);
  #[global] Log_Size_unfold :: MethodUnfold (Log) "Size" (Log__Sizeⁱᵐᵖˡ);
  #[global] Log_Write_unfold :: MethodUnfold (Log) "Write" (Log__Writeⁱᵐᵖˡ);
  #[global] Log_lock_unfold :: MethodUnfold (Log) "lock" (Log__lockⁱᵐᵖˡ);
  #[global] Log_unlock_unfold :: MethodUnfold (Log) "unlock" (Log__unlockⁱᵐᵖˡ);
  #[global] Log'ptr_Apply_unfold :: MethodUnfold (go.PointerType (Log)) "Apply" (λ: "$r", MethodResolve (Log) "Apply" #() (![(Log)] "$r"));
  #[global] Log'ptr_BeginTxn_unfold :: MethodUnfold (go.PointerType (Log)) "BeginTxn" (λ: "$r", MethodResolve (Log) "BeginTxn" #() (![(Log)] "$r"));
  #[global] Log'ptr_Commit_unfold :: MethodUnfold (go.PointerType (Log)) "Commit" (λ: "$r", MethodResolve (Log) "Commit" #() (![(Log)] "$r"));
  #[global] Log'ptr_Read_unfold :: MethodUnfold (go.PointerType (Log)) "Read" (λ: "$r", MethodResolve (Log) "Read" #() (![(Log)] "$r"));
  #[global] Log'ptr_Size_unfold :: MethodUnfold (go.PointerType (Log)) "Size" (λ: "$r", MethodResolve (Log) "Size" #() (![(Log)] "$r"));
  #[global] Log'ptr_Write_unfold :: MethodUnfold (go.PointerType (Log)) "Write" (λ: "$r", MethodResolve (Log) "Write" #() (![(Log)] "$r"));
  #[global] Log'ptr_lock_unfold :: MethodUnfold (go.PointerType (Log)) "lock" (λ: "$r", MethodResolve (Log) "lock" #() (![(Log)] "$r"));
  #[global] Log'ptr_unlock_unfold :: MethodUnfold (go.PointerType (Log)) "unlock" (λ: "$r", MethodResolve (Log) "unlock" #() (![(Log)] "$r"));
}.

Class Assumptions `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Log_instance :: Log_Assumptions;
  #[global] intToBlock_unfold :: FuncUnfold intToBlock [] (intToBlockⁱᵐᵖˡ);
  #[global] blockToInt_unfold :: FuncUnfold blockToInt [] (blockToIntⁱᵐᵖˡ);
  #[global] New_unfold :: FuncUnfold New [] (Newⁱᵐᵖˡ);
  #[global] getLogEntry_unfold :: FuncUnfold getLogEntry [] (getLogEntryⁱᵐᵖˡ);
  #[global] applyLog_unfold :: FuncUnfold applyLog [] (applyLogⁱᵐᵖˡ);
  #[global] clearLog_unfold :: FuncUnfold clearLog [] (clearLogⁱᵐᵖˡ);
  #[global] Open_unfold :: FuncUnfold Open [] (Openⁱᵐᵖˡ);
  #[global] import_sync_Assumption :: sync.Assumptions;
  #[global] import_primitive_Assumption :: primitive.Assumptions;
  #[global] import_disk_Assumption :: disk.Assumptions;
}.
End awol.
