(* autogenerated from social-media-library *)
Require Export New.code.bufio.
Require Export New.code.encoding.json.
Require Export New.code.fmt.
Require Export New.code.log.
Require Export New.code.os.
Require Export New.code.runtime.debug.
Require Export New.code.strconv.
Require Export New.code.strings.
Require Export New.code.social_media_library.common.
Require Export New.code.social_media_library.manager.
Require Export New.code.social_media_library.storage.
Require Export New.code.social_media_library.user.
Require Export New.code.social_media_library.wrappers.
From New.golang Require Import defn.
Module pkg_id.
Definition main : go_string := "social-media-library".

End pkg_id.
Export pkg_id.
Module main.

Definition main {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "social-media-library.main"%go.

Definition runCLI {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "social-media-library.runCLI"%go.

(* go: main.go:20:6 *)
Definition mainⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (do:  (let: "$a0" := (Convert go.untyped_int go.int (⟨go.untyped_int⟩- #1)) in
    (FuncResolve debug.SetGCPercent [] #()) "$a0");;;
    (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] (GlobalVarAddr os.Args #())) in
    (FuncResolve go.len [go.SliceType go.string] #()) "$a0") <⟨go.int⟩ #(W64 3))
    then
      do:  (let: "$a0" := #"usage: go run main.go [portOffset] [mode] ..."%go in
      let: "$a1" := #slice.nil in
      (FuncResolve log.Fatalf [] #()) "$a0" "$a1")
    else do:  #());;;
    let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "config" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := #"config.json"%go in
    (FuncResolve os.ReadFile [] #()) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("config" <-[go.SliceType go.byte] "$r0");;;
    do:  ("err" <-[go.error] "$r1");;;
    (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
    then
      do:  (let: "$a0" := #"Failed to read config.json: %v"%go in
      let: "$a1" := ((let: "$sl0" := (Convert go.error go.any (![go.error] "err")) in
      CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
      (FuncResolve log.Fatalf [] #()) "$a0" "$a1")
    else do:  #());;;
    let: "portOffSet" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] (GlobalVarAddr os.Args #()), #(W64 1)))) in
    let: "$a1" := #(W64 10) in
    let: "$a2" := #(W64 64) in
    (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("portOffSet" <-[go.uint64] "$r0");;;
    do:  "$r1";;;
    let: "data" := (GoAlloc (go.MapType go.string (go.InterfaceType [])) (GoZeroVal (go.MapType go.string (go.InterfaceType [])) #())) in
    do:  (let: "$a0" := (![go.SliceType go.byte] "config") in
    let: "$a1" := (Convert (go.PointerType (go.MapType go.string (go.InterfaceType []))) go.any "data") in
    (FuncResolve json.Unmarshal [] #()) "$a0" "$a1");;;
    let: "parseServers" := (GoAlloc (go.FunctionType (go.Signature [go.string] false [go.SliceType (go.PointerType common.Connection)])) (GoZeroVal (go.FunctionType (go.Signature [go.string] false [go.SliceType (go.PointerType common.Connection)])) #())) in
    let: "$r0" := (λ: "key",
      exception_do (let: "key" := (GoAlloc go.string "key") in
      let: "list" := (GoAlloc (go.SliceType (go.InterfaceType [])) (GoZeroVal (go.SliceType (go.InterfaceType [])) #())) in
      let: "$r0" := (TypeAssert (go.SliceType (go.InterfaceType [])) (map.lookup1 go.string (go.InterfaceType []) (![go.MapType go.string (go.InterfaceType [])] "data") (![go.string] "key"))) in
      do:  ("list" <-[go.SliceType (go.InterfaceType [])] "$r0");;;
      let: "srvs" := (GoAlloc (go.SliceType (go.PointerType common.Connection)) (GoZeroVal (go.SliceType (go.PointerType common.Connection)) #())) in
      let: "$r0" := ((FuncResolve go.make2 [go.SliceType (go.PointerType common.Connection)] #()) (let: "$a0" := (![go.SliceType (go.InterfaceType [])] "list") in
      (FuncResolve go.len [go.SliceType (go.InterfaceType [])] #()) "$a0")) in
      do:  ("srvs" <-[go.SliceType (go.PointerType common.Connection)] "$r0");;;
      let: "$range" := (![go.SliceType (go.InterfaceType [])] "list") in
      (let: "s" := (GoAlloc (go.InterfaceType []) (GoZeroVal (go.InterfaceType []) #())) in
      let: "i" := (GoAlloc go.int (GoZeroVal go.int #())) in
      slice.for_range (go.InterfaceType []) "$range" (λ: "$key" "$value",
        do:  ("s" <-[go.InterfaceType []] "$value");;;
        do:  ("i" <-[go.int] "$key");;;
        let: "conn" := (GoAlloc (go.MapType go.string (go.InterfaceType [])) (GoZeroVal (go.MapType go.string (go.InterfaceType [])) #())) in
        let: ("$ret0", "$ret1") := (TypeAssert2 (go.MapType go.string (go.InterfaceType [])) (![go.InterfaceType []] "s")) in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("conn" <-[go.MapType go.string (go.InterfaceType [])] "$r0");;;
        do:  "$r1";;;
        let: "network" := (GoAlloc go.string (GoZeroVal go.string #())) in
        let: ("$ret0", "$ret1") := (TypeAssert2 go.string (map.lookup1 go.string (go.InterfaceType []) (![go.MapType go.string (go.InterfaceType [])] "conn") #"network"%go)) in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("network" <-[go.string] "$r0");;;
        do:  "$r1";;;
        let: "address" := (GoAlloc go.string (GoZeroVal go.string #())) in
        let: ("$ret0", "$ret1") := (TypeAssert2 go.string (map.lookup1 go.string (go.InterfaceType []) (![go.MapType go.string (go.InterfaceType [])] "conn") #"address"%go)) in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("address" <-[go.string] "$r0");;;
        do:  "$r1";;;
        let: "$r0" := (GoAlloc common.Connection (let: "$v0" := (![go.string] "network") in
        let: "$v1" := (let: "$a0" := (![go.string] "address") in
        let: "$a1" := (![go.uint64] "portOffSet") in
        (FuncResolve common.ProcessAddressString [] #()) "$a0" "$a1") in
        CompositeLiteral common.Connection (LiteralValue [KeyedElement (Some (KeyField "Network"%go)) (ElementExpression go.string "$v0"); KeyedElement (Some (KeyField "Address"%go)) (ElementExpression go.string "$v1")]))) in
        do:  ((IndexRef (go.SliceType (go.PointerType common.Connection)) (![go.SliceType (go.PointerType common.Connection)] "srvs", ![go.int] "i")) <-[go.PointerType common.Connection] "$r0")));;;
      return: (![go.SliceType (go.PointerType common.Connection)] "srvs"))
      ) in
    do:  ("parseServers" <-[go.FunctionType (go.Signature [go.string] false [go.SliceType (go.PointerType common.Connection)])] "$r0");;;
    let: "userServers" := (GoAlloc (go.SliceType (go.PointerType common.Connection)) (GoZeroVal (go.SliceType (go.PointerType common.Connection)) #())) in
    let: "$r0" := (let: "$a0" := #"user"%go in
    (![go.FunctionType (go.Signature [go.string] false [go.SliceType (go.PointerType common.Connection)])] "parseServers") "$a0") in
    do:  ("userServers" <-[go.SliceType (go.PointerType common.Connection)] "$r0");;;
    let: "postServers" := (GoAlloc (go.SliceType (go.PointerType common.Connection)) (GoZeroVal (go.SliceType (go.PointerType common.Connection)) #())) in
    let: "$r0" := (let: "$a0" := #"post"%go in
    (![go.FunctionType (go.Signature [go.string] false [go.SliceType (go.PointerType common.Connection)])] "parseServers") "$a0") in
    do:  ("postServers" <-[go.SliceType (go.PointerType common.Connection)] "$r0");;;
    let: "timelineServers" := (GoAlloc (go.SliceType (go.PointerType common.Connection)) (GoZeroVal (go.SliceType (go.PointerType common.Connection)) #())) in
    let: "$r0" := (let: "$a0" := #"timeline"%go in
    (![go.FunctionType (go.Signature [go.string] false [go.SliceType (go.PointerType common.Connection)])] "parseServers") "$a0") in
    do:  ("timelineServers" <-[go.SliceType (go.PointerType common.Connection)] "$r0");;;
    let: "graphServers" := (GoAlloc (go.SliceType (go.PointerType common.Connection)) (GoZeroVal (go.SliceType (go.PointerType common.Connection)) #())) in
    let: "$r0" := (let: "$a0" := #"graph"%go in
    (![go.FunctionType (go.Signature [go.string] false [go.SliceType (go.PointerType common.Connection)])] "parseServers") "$a0") in
    do:  ("graphServers" <-[go.SliceType (go.PointerType common.Connection)] "$r0");;;
    let: "$sw" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] (GlobalVarAddr os.Args #()), #(W64 2)))) in
    (if: "$sw" =⟨go.string⟩ #"client"%go
    then
      let: "targetServerId" := (GoAlloc go.int (GoZeroVal go.int #())) in
      let: "$r0" := #(W64 0) in
      do:  ("targetServerId" <-[go.int] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] (GlobalVarAddr os.Args #())) in
      (FuncResolve go.len [go.SliceType go.string] #()) "$a0") >⟨go.int⟩ #(W64 3))
      then
        let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] (GlobalVarAddr os.Args #()), #(W64 3)))) in
        (FuncResolve strconv.Atoi [] #()) "$a0") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("targetServerId" <-[go.int] "$r0");;;
        do:  "$r1"
      else do:  #());;;
      let: "sessionSemantic" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
      let: "$r0" := #(W64 0) in
      do:  ("sessionSemantic" <-[go.uint64] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] (GlobalVarAddr os.Args #())) in
      (FuncResolve go.len [go.SliceType go.string] #()) "$a0") >⟨go.int⟩ #(W64 4))
      then
        let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] (GlobalVarAddr os.Args #()), #(W64 4)))) in
        let: "$a1" := #(W64 10) in
        let: "$a2" := #(W64 64) in
        (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("sessionSemantic" <-[go.uint64] "$r0");;;
        do:  "$r1"
      else do:  #());;;
      (if: Convert go.untyped_bool go.bool ((![go.int] "targetServerId") ≥⟨go.int⟩ (let: "$a0" := (![go.SliceType (go.PointerType common.Connection)] "userServers") in
      (FuncResolve go.len [go.SliceType (go.PointerType common.Connection)] #()) "$a0"))
      then
        do:  (let: "$a0" := #"Invalid target server ID: %d"%go in
        let: "$a1" := ((let: "$sl0" := (Convert go.int go.any (![go.int] "targetServerId")) in
        CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
        (FuncResolve log.Fatalf [] #()) "$a0" "$a1")
      else do:  #());;;
      let: "targetAddr" := (GoAlloc go.string (GoZeroVal go.string #())) in
      let: "$r0" := (![go.string] (StructFieldRef common.Connection "Address"%go (![go.PointerType common.Connection] (IndexRef (go.SliceType (go.PointerType common.Connection)) (![go.SliceType (go.PointerType common.Connection)] "userServers", ![go.int] "targetServerId"))))) in
      do:  ("targetAddr" <-[go.string] "$r0");;;
      do:  (let: "$a0" := #"Starting Client connecting to User Server %s with Session Semantic %d
      "%go in
      let: "$a1" := ((let: "$sl0" := (Convert go.string go.any (![go.string] "targetAddr")) in
      let: "$sl1" := (Convert go.uint64 go.any (![go.uint64] "sessionSemantic")) in
      CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0"); KeyedElement None (ElementExpression go.any "$sl1")]))) in
      (FuncResolve fmt.Printf [] #()) "$a0" "$a1");;;
      let: "clientID" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
      let: "$r0" := (Convert go.int go.uint64 ((FuncResolve os.Getpid [] #()) #())) in
      do:  ("clientID" <-[go.uint64] "$r0");;;
      let: "userWrapper" := (GoAlloc (go.PointerType wrappers.Wrapper) (GoZeroVal (go.PointerType wrappers.Wrapper) #())) in
      let: "$r0" := (let: "$a0" := (![go.uint64] "clientID") in
      let: "$a1" := (![go.uint64] "sessionSemantic") in
      let: "$a2" := (![go.SliceType (go.PointerType common.Connection)] "userServers") in
      (FuncResolve wrappers.NewWrapper [] #()) "$a0" "$a1" "$a2") in
      do:  ("userWrapper" <-[go.PointerType wrappers.Wrapper] "$r0");;;
      let: "postWrapper" := (GoAlloc (go.PointerType wrappers.Wrapper) (GoZeroVal (go.PointerType wrappers.Wrapper) #())) in
      let: "$r0" := (let: "$a0" := (![go.uint64] "clientID") in
      let: "$a1" := (![go.uint64] "sessionSemantic") in
      let: "$a2" := (![go.SliceType (go.PointerType common.Connection)] "postServers") in
      (FuncResolve wrappers.NewWrapper [] #()) "$a0" "$a1" "$a2") in
      do:  ("postWrapper" <-[go.PointerType wrappers.Wrapper] "$r0");;;
      let: "TimelineWrapper" := (GoAlloc (go.PointerType wrappers.Wrapper) (GoZeroVal (go.PointerType wrappers.Wrapper) #())) in
      let: "$r0" := (let: "$a0" := (![go.uint64] "clientID") in
      let: "$a1" := (![go.uint64] "sessionSemantic") in
      let: "$a2" := (![go.SliceType (go.PointerType common.Connection)] "timelineServers") in
      (FuncResolve wrappers.NewWrapper [] #()) "$a0" "$a1" "$a2") in
      do:  ("TimelineWrapper" <-[go.PointerType wrappers.Wrapper] "$r0");;;
      let: "graphWrapper" := (GoAlloc (go.PointerType wrappers.Wrapper) (GoZeroVal (go.PointerType wrappers.Wrapper) #())) in
      let: "$r0" := (let: "$a0" := (![go.uint64] "clientID") in
      let: "$a1" := (![go.uint64] "sessionSemantic") in
      let: "$a2" := (![go.SliceType (go.PointerType common.Connection)] "graphServers") in
      (FuncResolve wrappers.NewWrapper [] #()) "$a0" "$a1" "$a2") in
      do:  ("graphWrapper" <-[go.PointerType wrappers.Wrapper] "$r0");;;
      let: "mgr" := (GoAlloc (go.PointerType manager.CSLManager) (GoZeroVal (go.PointerType manager.CSLManager) #())) in
      let: "$r0" := (let: "$a0" := #(W64 0) in
      (FuncResolve manager.NewCSLManager [] #()) "$a0") in
      do:  ("mgr" <-[go.PointerType manager.CSLManager] "$r0");;;
      let: "lib" := (GoAlloc (go.PointerType user.Lib) (GoZeroVal (go.PointerType user.Lib) #())) in
      let: "$r0" := (let: "$a0" := (![go.PointerType manager.CSLManager] "mgr") in
      let: "$a1" := (![go.PointerType wrappers.Wrapper] "userWrapper") in
      let: "$a2" := (![go.PointerType wrappers.Wrapper] "postWrapper") in
      let: "$a3" := (![go.PointerType wrappers.Wrapper] "TimelineWrapper") in
      let: "$a4" := (![go.PointerType wrappers.Wrapper] "graphWrapper") in
      (FuncResolve user.NewLib [] #()) "$a0" "$a1" "$a2" "$a3" "$a4") in
      do:  ("lib" <-[go.PointerType user.Lib] "$r0");;;
      let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
      let: "$r0" := (let: "$a0" := (![go.SliceType (go.PointerType common.Connection)] "userServers") in
      let: "$a1" := (![go.SliceType (go.PointerType common.Connection)] "postServers") in
      let: "$a2" := (![go.SliceType (go.PointerType common.Connection)] "timelineServers") in
      let: "$a3" := (![go.SliceType (go.PointerType common.Connection)] "graphServers") in
      (MethodResolve (go.PointerType user.Lib) "Connect"%go (![go.PointerType user.Lib] "lib")) "$a0" "$a1" "$a2" "$a3") in
      do:  ("err" <-[go.error] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
      then
        do:  (let: "$a0" := #"Failed to connect to servers: %v"%go in
        let: "$a1" := ((let: "$sl0" := (Convert go.error go.any (![go.error] "err")) in
        CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
        (FuncResolve log.Fatalf [] #()) "$a0" "$a1")
      else do:  #());;;
      do:  (let: "$a0" := ((let: "$sl0" := (Convert go.string go.any #"Lib initialized and connected."%go) in
      CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
      (FuncResolve fmt.Println [] #()) "$a0");;;
      do:  (let: "$a0" := (![go.PointerType user.Lib] "lib") in
      (FuncResolve runCLI [] #()) "$a0")
    else
      (if: "$sw" =⟨go.string⟩ #"server"%go
      then
        (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] (GlobalVarAddr os.Args #())) in
        (FuncResolve go.len [go.SliceType go.string] #()) "$a0") <⟨go.int⟩ #(W64 6))
        then
          do:  (let: "$a0" := #"usage: go run main.go [portOffset] server [type] [id] [gossip_interval]"%go in
          let: "$a1" := #slice.nil in
          (FuncResolve log.Fatalf [] #()) "$a0" "$a1")
        else do:  #());;;
        let: "serverType" := (GoAlloc go.string (GoZeroVal go.string #())) in
        let: "$r0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] (GlobalVarAddr os.Args #()), #(W64 3)))) in
        do:  ("serverType" <-[go.string] "$r0");;;
        let: "id" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
        let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] (GlobalVarAddr os.Args #()), #(W64 4)))) in
        let: "$a1" := #(W64 10) in
        let: "$a2" := #(W64 64) in
        (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("id" <-[go.uint64] "$r0");;;
        do:  "$r1";;;
        let: "gossipInterval" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
        let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] (GlobalVarAddr os.Args #()), #(W64 5)))) in
        let: "$a1" := #(W64 10) in
        let: "$a2" := #(W64 64) in
        (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("gossipInterval" <-[go.uint64] "$r0");;;
        do:  "$r1";;;
        let: "servers" := (GoAlloc (go.SliceType (go.PointerType common.Connection)) (GoZeroVal (go.SliceType (go.PointerType common.Connection)) #())) in
        let: "$sw" := (![go.string] "serverType") in
        (if: "$sw" =⟨go.string⟩ #"user"%go
        then
          let: "$r0" := (![go.SliceType (go.PointerType common.Connection)] "userServers") in
          do:  ("servers" <-[go.SliceType (go.PointerType common.Connection)] "$r0")
        else
          (if: "$sw" =⟨go.string⟩ #"post"%go
          then
            let: "$r0" := (![go.SliceType (go.PointerType common.Connection)] "postServers") in
            do:  ("servers" <-[go.SliceType (go.PointerType common.Connection)] "$r0")
          else
            (if: "$sw" =⟨go.string⟩ #"timeline"%go
            then
              let: "$r0" := (![go.SliceType (go.PointerType common.Connection)] "timelineServers") in
              do:  ("servers" <-[go.SliceType (go.PointerType common.Connection)] "$r0")
            else
              (if: "$sw" =⟨go.string⟩ #"graph"%go
              then
                let: "$r0" := (![go.SliceType (go.PointerType common.Connection)] "graphServers") in
                do:  ("servers" <-[go.SliceType (go.PointerType common.Connection)] "$r0")
              else
                do:  (let: "$a0" := #"Unknown server type: %s"%go in
                let: "$a1" := ((let: "$sl0" := (Convert go.string go.any (![go.string] "serverType")) in
                CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                (FuncResolve log.Fatalf [] #()) "$a0" "$a1")))));;;
        (if: Convert go.untyped_bool go.bool ((![go.uint64] "id") ≥⟨go.uint64⟩ (Convert go.int go.uint64 (let: "$a0" := (![go.SliceType (go.PointerType common.Connection)] "servers") in
        (FuncResolve go.len [go.SliceType (go.PointerType common.Connection)] #()) "$a0")))
        then
          do:  (let: "$a0" := #"Server ID %d out of range (0-%d)"%go in
          let: "$a1" := ((let: "$sl0" := (Convert go.uint64 go.any (![go.uint64] "id")) in
          let: "$sl1" := (Convert go.int go.any ((let: "$a0" := (![go.SliceType (go.PointerType common.Connection)] "servers") in
          (FuncResolve go.len [go.SliceType (go.PointerType common.Connection)] #()) "$a0") -⟨go.int⟩ #(W64 1))) in
          CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0"); KeyedElement None (ElementExpression go.any "$sl1")]))) in
          (FuncResolve log.Fatalf [] #()) "$a0" "$a1")
        else do:  #());;;
        do:  (let: "$a0" := #"Starting %s Server %d at %s with gossip interval %d
        "%go in
        let: "$a1" := ((let: "$sl0" := (Convert go.string go.any (![go.string] "serverType")) in
        let: "$sl1" := (Convert go.uint64 go.any (![go.uint64] "id")) in
        let: "$sl2" := (Convert go.string go.any (![go.string] (StructFieldRef common.Connection "Address"%go (![go.PointerType common.Connection] (IndexRef (go.SliceType (go.PointerType common.Connection)) (![go.SliceType (go.PointerType common.Connection)] "servers", Convert go.uint64 go.int (![go.uint64] "id"))))))) in
        let: "$sl3" := (Convert go.uint64 go.any (![go.uint64] "gossipInterval")) in
        CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0"); KeyedElement None (ElementExpression go.any "$sl1"); KeyedElement None (ElementExpression go.any "$sl2"); KeyedElement None (ElementExpression go.any "$sl3")]))) in
        (FuncResolve fmt.Printf [] #()) "$a0" "$a1");;;
        do:  (let: "$a0" := (let: "$a0" := (![go.uint64] "id") in
        let: "$a1" := (![go.PointerType common.Connection] (IndexRef (go.SliceType (go.PointerType common.Connection)) (![go.SliceType (go.PointerType common.Connection)] "servers", Convert go.uint64 go.int (![go.uint64] "id")))) in
        let: "$a2" := (![go.SliceType (go.PointerType common.Connection)] "servers") in
        let: "$a3" := (![go.uint64] "gossipInterval") in
        (FuncResolve server.New [] #()) "$a0" "$a1" "$a2" "$a3") in
        (FuncResolve server.Start [] #()) "$a0")
      else
        do:  (let: "$a0" := #"unknown command: %s"%go in
        let: "$a1" := ((let: "$sl0" := (Convert go.string go.any (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] (GlobalVarAddr os.Args #()), #(W64 2))))) in
        CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
        (FuncResolve log.Fatalf [] #()) "$a0" "$a1")));;;
    return: #()).

(* go: main.go:130:6 *)
Definition runCLIⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "lib",
    exception_do (let: "lib" := (GoAlloc (go.PointerType user.Lib) "lib") in
    let: "scanner" := (GoAlloc (go.PointerType bufio.Scanner) (GoZeroVal (go.PointerType bufio.Scanner) #())) in
    let: "$r0" := (let: "$a0" := (Convert (go.PointerType os.File) io.Reader (![go.PointerType os.File] (GlobalVarAddr os.Stdin #()))) in
    (FuncResolve bufio.NewScanner [] #()) "$a0") in
    do:  ("scanner" <-[go.PointerType bufio.Scanner] "$r0");;;
    (for: (λ: <>, #true); (λ: <>, #()) := λ: <>,
      do:  (let: "$a0" := ((let: "$sl0" := (Convert go.string go.any #"> "%go) in
      CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
      (FuncResolve fmt.Print [] #()) "$a0");;;
      (if: (⟨go.bool⟩! ((MethodResolve (go.PointerType bufio.Scanner) "Scan"%go (![go.PointerType bufio.Scanner] "scanner")) #()))
      then break: #()
      else do:  #());;;
      let: "line" := (GoAlloc go.string (GoZeroVal go.string #())) in
      let: "$r0" := ((MethodResolve (go.PointerType bufio.Scanner) "Text"%go (![go.PointerType bufio.Scanner] "scanner")) #()) in
      do:  ("line" <-[go.string] "$r0");;;
      let: "parts" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
      let: "$r0" := (let: "$a0" := (![go.string] "line") in
      (FuncResolve strings.Fields [] #()) "$a0") in
      do:  ("parts" <-[go.SliceType go.string] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "parts") in
      (FuncResolve go.len [go.SliceType go.string] #()) "$a0") =⟨go.int⟩ #(W64 0))
      then continue: #()
      else do:  #());;;
      let: "cmd" := (GoAlloc go.string (GoZeroVal go.string #())) in
      let: "$r0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "parts", #(W64 0)))) in
      do:  ("cmd" <-[go.string] "$r0");;;
      let: "$sw" := (![go.string] "cmd") in
      (if: "$sw" =⟨go.string⟩ #"login"%go
      then
        (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "parts") in
        (FuncResolve go.len [go.SliceType go.string] #()) "$a0") <⟨go.int⟩ #(W64 3))
        then
          do:  (let: "$a0" := ((let: "$sl0" := (Convert go.string go.any #"Usage: login <uid> <pswd>"%go) in
          CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
          (FuncResolve fmt.Println [] #()) "$a0");;;
          continue: #()
        else do:  #());;;
        let: "uid" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
        let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "parts", #(W64 1)))) in
        let: "$a1" := #(W64 10) in
        let: "$a2" := #(W64 64) in
        (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("uid" <-[go.uint64] "$r0");;;
        do:  "$r1";;;
        let: "pswd" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
        let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "parts", #(W64 2)))) in
        let: "$a1" := #(W64 10) in
        let: "$a2" := #(W64 64) in
        (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("pswd" <-[go.uint64] "$r0");;;
        do:  "$r1";;;
        let: "res" := (GoAlloc manager.Res (GoZeroVal manager.Res #())) in
        let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$v0" := #(W64 5) in
        let: "$v1" := (![go.uint64] "uid") in
        let: "$v2" := (![go.uint64] "pswd") in
        CompositeLiteral user.Method (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "LoginUid"%go)) (ElementExpression go.uint64 "$v1"); KeyedElement (Some (KeyField "LoginPswd"%go)) (ElementExpression go.uint64 "$v2")])) in
        (MethodResolve (go.PointerType user.Lib) "Run"%go (![go.PointerType user.Lib] "lib")) "$a0") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  "$r0";;;
        do:  ("res" <-[manager.Res] "$r1");;;
        do:  (let: "$a0" := #"Result: %+v
        "%go in
        let: "$a1" := ((let: "$sl0" := (Convert manager.Res go.any (![manager.Res] "res")) in
        CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
        (FuncResolve fmt.Printf [] #()) "$a0" "$a1")
      else
        (if: "$sw" =⟨go.string⟩ #"signup"%go
        then
          (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "parts") in
          (FuncResolve go.len [go.SliceType go.string] #()) "$a0") <⟨go.int⟩ #(W64 3))
          then
            do:  (let: "$a0" := ((let: "$sl0" := (Convert go.string go.any #"Usage: signup <uid> <pswd>"%go) in
            CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
            (FuncResolve fmt.Println [] #()) "$a0");;;
            continue: #()
          else do:  #());;;
          let: "uid" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
          let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "parts", #(W64 1)))) in
          let: "$a1" := #(W64 10) in
          let: "$a2" := #(W64 64) in
          (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
          let: "$r0" := "$ret0" in
          let: "$r1" := "$ret1" in
          do:  ("uid" <-[go.uint64] "$r0");;;
          do:  "$r1";;;
          let: "pswd" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
          let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "parts", #(W64 2)))) in
          let: "$a1" := #(W64 10) in
          let: "$a2" := #(W64 64) in
          (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
          let: "$r0" := "$ret0" in
          let: "$r1" := "$ret1" in
          do:  ("pswd" <-[go.uint64] "$r0");;;
          do:  "$r1";;;
          let: "res" := (GoAlloc manager.Res (GoZeroVal manager.Res #())) in
          let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$v0" := #(W64 6) in
          let: "$v1" := (![go.uint64] "uid") in
          let: "$v2" := (![go.uint64] "pswd") in
          CompositeLiteral user.Method (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "SignUpUid"%go)) (ElementExpression go.uint64 "$v1"); KeyedElement (Some (KeyField "SignUpPswd"%go)) (ElementExpression go.uint64 "$v2")])) in
          (MethodResolve (go.PointerType user.Lib) "Run"%go (![go.PointerType user.Lib] "lib")) "$a0") in
          let: "$r0" := "$ret0" in
          let: "$r1" := "$ret1" in
          do:  "$r0";;;
          do:  ("res" <-[manager.Res] "$r1");;;
          do:  (let: "$a0" := #"Result: %+v
          "%go in
          let: "$a1" := ((let: "$sl0" := (Convert manager.Res go.any (![manager.Res] "res")) in
          CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
          (FuncResolve fmt.Printf [] #()) "$a0" "$a1")
        else
          (if: "$sw" =⟨go.string⟩ #"post"%go
          then
            let: "res" := (GoAlloc manager.Res (GoZeroVal manager.Res #())) in
            let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$v0" := #(W64 2) in
            CompositeLiteral user.Method (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0")])) in
            (MethodResolve (go.PointerType user.Lib) "Run"%go (![go.PointerType user.Lib] "lib")) "$a0") in
            let: "$r0" := "$ret0" in
            let: "$r1" := "$ret1" in
            do:  "$r0";;;
            do:  ("res" <-[manager.Res] "$r1");;;
            do:  (let: "$a0" := #"Result: %+v
            "%go in
            let: "$a1" := ((let: "$sl0" := (Convert manager.Res go.any (![manager.Res] "res")) in
            CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
            (FuncResolve fmt.Printf [] #()) "$a0" "$a1")
          else
            (if: "$sw" =⟨go.string⟩ #"home"%go
            then
              let: "res" := (GoAlloc manager.Res (GoZeroVal manager.Res #())) in
              let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$v0" := #(W64 3) in
              CompositeLiteral user.Method (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0")])) in
              (MethodResolve (go.PointerType user.Lib) "Run"%go (![go.PointerType user.Lib] "lib")) "$a0") in
              let: "$r0" := "$ret0" in
              let: "$r1" := "$ret1" in
              do:  "$r0";;;
              do:  ("res" <-[manager.Res] "$r1");;;
              do:  (let: "$a0" := #"Result: %+v
              "%go in
              let: "$a1" := ((let: "$sl0" := (Convert manager.Res go.any (![manager.Res] "res")) in
              CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
              (FuncResolve fmt.Printf [] #()) "$a0" "$a1")
            else
              (if: "$sw" =⟨go.string⟩ #"timeline"%go
              then
                (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "parts") in
                (FuncResolve go.len [go.SliceType go.string] #()) "$a0") <⟨go.int⟩ #(W64 2))
                then
                  do:  (let: "$a0" := ((let: "$sl0" := (Convert go.string go.any #"Usage: timeline <uid>"%go) in
                  CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                  (FuncResolve fmt.Println [] #()) "$a0");;;
                  continue: #()
                else do:  #());;;
                let: "uid" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
                let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "parts", #(W64 1)))) in
                let: "$a1" := #(W64 10) in
                let: "$a2" := #(W64 64) in
                (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
                let: "$r0" := "$ret0" in
                let: "$r1" := "$ret1" in
                do:  ("uid" <-[go.uint64] "$r0");;;
                do:  "$r1";;;
                let: "res" := (GoAlloc manager.Res (GoZeroVal manager.Res #())) in
                let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$v0" := #(W64 4) in
                let: "$v1" := (![go.uint64] "uid") in
                CompositeLiteral user.Method (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "TimelineUid"%go)) (ElementExpression go.uint64 "$v1")])) in
                (MethodResolve (go.PointerType user.Lib) "Run"%go (![go.PointerType user.Lib] "lib")) "$a0") in
                let: "$r0" := "$ret0" in
                let: "$r1" := "$ret1" in
                do:  "$r0";;;
                do:  ("res" <-[manager.Res] "$r1");;;
                do:  (let: "$a0" := #"Result: %+v
                "%go in
                let: "$a1" := ((let: "$sl0" := (Convert manager.Res go.any (![manager.Res] "res")) in
                CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                (FuncResolve fmt.Printf [] #()) "$a0" "$a1")
              else
                (if: "$sw" =⟨go.string⟩ #"follow"%go
                then
                  (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "parts") in
                  (FuncResolve go.len [go.SliceType go.string] #()) "$a0") <⟨go.int⟩ #(W64 2))
                  then
                    do:  (let: "$a0" := ((let: "$sl0" := (Convert go.string go.any #"Usage: follow <uid>"%go) in
                    CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                    (FuncResolve fmt.Println [] #()) "$a0");;;
                    continue: #()
                  else do:  #());;;
                  let: "uid" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
                  let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "parts", #(W64 1)))) in
                  let: "$a1" := #(W64 10) in
                  let: "$a2" := #(W64 64) in
                  (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
                  let: "$r0" := "$ret0" in
                  let: "$r1" := "$ret1" in
                  do:  ("uid" <-[go.uint64] "$r0");;;
                  do:  "$r1";;;
                  let: "res" := (GoAlloc manager.Res (GoZeroVal manager.Res #())) in
                  let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$v0" := #(W64 0) in
                  let: "$v1" := (![go.uint64] "uid") in
                  CompositeLiteral user.Method (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "FollowUid"%go)) (ElementExpression go.uint64 "$v1")])) in
                  (MethodResolve (go.PointerType user.Lib) "Run"%go (![go.PointerType user.Lib] "lib")) "$a0") in
                  let: "$r0" := "$ret0" in
                  let: "$r1" := "$ret1" in
                  do:  "$r0";;;
                  do:  ("res" <-[manager.Res] "$r1");;;
                  do:  (let: "$a0" := #"Result: %+v
                  "%go in
                  let: "$a1" := ((let: "$sl0" := (Convert manager.Res go.any (![manager.Res] "res")) in
                  CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                  (FuncResolve fmt.Printf [] #()) "$a0" "$a1")
                else
                  (if: "$sw" =⟨go.string⟩ #"unfollow"%go
                  then
                    (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "parts") in
                    (FuncResolve go.len [go.SliceType go.string] #()) "$a0") <⟨go.int⟩ #(W64 2))
                    then
                      do:  (let: "$a0" := ((let: "$sl0" := (Convert go.string go.any #"Usage: unfollow <uid>"%go) in
                      CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                      (FuncResolve fmt.Println [] #()) "$a0");;;
                      continue: #()
                    else do:  #());;;
                    let: "uid" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
                    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "parts", #(W64 1)))) in
                    let: "$a1" := #(W64 10) in
                    let: "$a2" := #(W64 64) in
                    (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
                    let: "$r0" := "$ret0" in
                    let: "$r1" := "$ret1" in
                    do:  ("uid" <-[go.uint64] "$r0");;;
                    do:  "$r1";;;
                    let: "res" := (GoAlloc manager.Res (GoZeroVal manager.Res #())) in
                    let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$v0" := #(W64 1) in
                    let: "$v1" := (![go.uint64] "uid") in
                    CompositeLiteral user.Method (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "UnfollowUid"%go)) (ElementExpression go.uint64 "$v1")])) in
                    (MethodResolve (go.PointerType user.Lib) "Run"%go (![go.PointerType user.Lib] "lib")) "$a0") in
                    let: "$r0" := "$ret0" in
                    let: "$r1" := "$ret1" in
                    do:  "$r0";;;
                    do:  ("res" <-[manager.Res] "$r1");;;
                    do:  (let: "$a0" := #"Result: %+v
                    "%go in
                    let: "$a1" := ((let: "$sl0" := (Convert manager.Res go.any (![manager.Res] "res")) in
                    CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                    (FuncResolve fmt.Printf [] #()) "$a0" "$a1")
                  else
                    (if: "$sw" =⟨go.string⟩ #"block"%go
                    then
                      (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "parts") in
                      (FuncResolve go.len [go.SliceType go.string] #()) "$a0") <⟨go.int⟩ #(W64 2))
                      then
                        do:  (let: "$a0" := ((let: "$sl0" := (Convert go.string go.any #"Usage: block <uid>"%go) in
                        CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                        (FuncResolve fmt.Println [] #()) "$a0");;;
                        continue: #()
                      else do:  #());;;
                      let: "uid" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
                      let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "parts", #(W64 1)))) in
                      let: "$a1" := #(W64 10) in
                      let: "$a2" := #(W64 64) in
                      (FuncResolve strconv.ParseUint [] #()) "$a0" "$a1" "$a2") in
                      let: "$r0" := "$ret0" in
                      let: "$r1" := "$ret1" in
                      do:  ("uid" <-[go.uint64] "$r0");;;
                      do:  "$r1";;;
                      let: "res" := (GoAlloc manager.Res (GoZeroVal manager.Res #())) in
                      let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$v0" := #(W64 7) in
                      let: "$v1" := (![go.uint64] "uid") in
                      CompositeLiteral user.Method (LiteralValue [KeyedElement (Some (KeyField "Type"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "BlockUid"%go)) (ElementExpression go.uint64 "$v1")])) in
                      (MethodResolve (go.PointerType user.Lib) "Run"%go (![go.PointerType user.Lib] "lib")) "$a0") in
                      let: "$r0" := "$ret0" in
                      let: "$r1" := "$ret1" in
                      do:  "$r0";;;
                      do:  ("res" <-[manager.Res] "$r1");;;
                      do:  (let: "$a0" := #"Result: %+v
                      "%go in
                      let: "$a1" := ((let: "$sl0" := (Convert manager.Res go.any (![manager.Res] "res")) in
                      CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                      (FuncResolve fmt.Printf [] #()) "$a0" "$a1")
                    else
                      (if: "$sw" =⟨go.string⟩ #"exit"%go
                      then return: (#())
                      else
                        do:  (let: "$a0" := ((let: "$sl0" := (Convert go.string go.any #"Unknown command"%go) in
                        CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
                        (FuncResolve fmt.Println [] #()) "$a0")))))))))));;;
    return: #()).

#[global] Instance info' : PkgInfo pkg_id.main :=
{|
  pkg_imported_pkgs := [code.bufio.pkg_id.bufio; code.encoding.json.pkg_id.json; code.fmt.pkg_id.fmt; code.log.pkg_id.log; code.os.pkg_id.os; code.runtime.debug.pkg_id.debug; code.strconv.pkg_id.strconv; code.strings.pkg_id.strings; code.social_media_library.common.pkg_id.common; code.social_media_library.manager.pkg_id.manager; code.social_media_library.storage.pkg_id.server; code.social_media_library.user.pkg_id.user; code.social_media_library.wrappers.pkg_id.wrappers]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.main (λ: <>,
      exception_do (do:  (wrappers.initialize' #());;;
      do:  (user.initialize' #());;;
      do:  (server.initialize' #());;;
      do:  (manager.initialize' #());;;
      do:  (common.initialize' #());;;
      do:  (strings.initialize' #());;;
      do:  (strconv.initialize' #());;;
      do:  (debug.initialize' #());;;
      do:  (os.initialize' #());;;
      do:  (log.initialize' #());;;
      do:  (fmt.initialize' #());;;
      do:  (json.initialize' #());;;
      do:  (bufio.initialize' #()))
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] main_unfold :: FuncUnfold main [] (mainⁱᵐᵖˡ);
  #[global] runCLI_unfold :: FuncUnfold runCLI [] (runCLIⁱᵐᵖˡ);
  #[global] import_bufio_Assumption :: bufio.Assumptions;
  #[global] import_json_Assumption :: json.Assumptions;
  #[global] import_fmt_Assumption :: fmt.Assumptions;
  #[global] import_log_Assumption :: log.Assumptions;
  #[global] import_os_Assumption :: os.Assumptions;
  #[global] import_debug_Assumption :: debug.Assumptions;
  #[global] import_strconv_Assumption :: strconv.Assumptions;
  #[global] import_strings_Assumption :: strings.Assumptions;
  #[global] import_common_Assumption :: common.Assumptions;
  #[global] import_manager_Assumption :: manager.Assumptions;
  #[global] import_server_Assumption :: server.Assumptions;
  #[global] import_user_Assumption :: user.Assumptions;
  #[global] import_wrappers_Assumption :: wrappers.Assumptions;
}.
End main.
