(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.go_opentelemetry_io.otel.attribute.

Set Default Proof Using "Type".

Module attribute.
Module Encoder.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Encoder_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.Encoder.t). Admitted.

#[global] Instance Encoder_into_val_typed
   :
  IntoValTypedUnderlying (attribute.Encoder.t) (attribute.Encoderⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Encoder.

Module EncoderID.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance EncoderID_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.EncoderID.t). Admitted.

#[global] Instance EncoderID_into_val_typed
   :
  IntoValTypedUnderlying (attribute.EncoderID.t) (attribute.EncoderIDⁱᵐᵖˡ).
Proof. Admitted.

End def.
End EncoderID.

Module defaultAttrEncoder.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance defaultAttrEncoder_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.defaultAttrEncoder.t). Admitted.

#[global] Instance defaultAttrEncoder_into_val_typed
   :
  IntoValTypedUnderlying (attribute.defaultAttrEncoder.t) (attribute.defaultAttrEncoderⁱᵐᵖˡ).
Proof. Admitted.

End def.
End defaultAttrEncoder.

Module Filter.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Filter_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.Filter.t). Admitted.

#[global] Instance Filter_into_val_typed
   :
  IntoValTypedUnderlying (attribute.Filter.t) (attribute.Filterⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Filter.

Module Iterator.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Iterator_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.Iterator.t). Admitted.

#[global] Instance Iterator_into_val_typed
   :
  IntoValTypedUnderlying (attribute.Iterator.t) (attribute.Iteratorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Iterator.

Module MergeIterator.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance MergeIterator_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.MergeIterator.t). Admitted.

#[global] Instance MergeIterator_into_val_typed
   :
  IntoValTypedUnderlying (attribute.MergeIterator.t) (attribute.MergeIteratorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End MergeIterator.

Module oneIterator.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance oneIterator_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.oneIterator.t). Admitted.

#[global] Instance oneIterator_into_val_typed
   :
  IntoValTypedUnderlying (attribute.oneIterator.t) (attribute.oneIteratorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End oneIterator.

Module Key.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Key_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.Key.t). Admitted.

#[global] Instance Key_into_val_typed
   :
  IntoValTypedUnderlying (attribute.Key.t) (attribute.Keyⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Key.

Module KeyValue.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance KeyValue_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.KeyValue.t). Admitted.

#[global] Instance KeyValue_into_val_typed
   :
  IntoValTypedUnderlying (attribute.KeyValue.t) (attribute.KeyValueⁱᵐᵖˡ).
Proof. Admitted.

End def.
End KeyValue.

Module Set'.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Set'_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.Set'.t). Admitted.

#[global] Instance Set'_into_val_typed
   :
  IntoValTypedUnderlying (attribute.Set'.t) (attribute.Set'ⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Set'.

Module Distinct.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Distinct_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.Distinct.t). Admitted.

#[global] Instance Distinct_into_val_typed
   :
  IntoValTypedUnderlying (attribute.Distinct.t) (attribute.Distinctⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Distinct.

Module Sortable.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Sortable_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.Sortable.t). Admitted.

#[global] Instance Sortable_into_val_typed
   :
  IntoValTypedUnderlying (attribute.Sortable.t) (attribute.Sortableⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Sortable.

Module Type'.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Type'_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.Type'.t). Admitted.

#[global] Instance Type'_into_val_typed
   :
  IntoValTypedUnderlying (attribute.Type'.t) (attribute.Type'ⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Type'.

Module Value.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Value_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.Value.t). Admitted.

#[global] Instance Value_into_val_typed
   :
  IntoValTypedUnderlying (attribute.Value.t) (attribute.Valueⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Value.

Module unknownValueType.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : attribute.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance unknownValueType_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (attribute.unknownValueType.t). Admitted.

#[global] Instance unknownValueType_into_val_typed
   :
  IntoValTypedUnderlying (attribute.unknownValueType.t) (attribute.unknownValueTypeⁱᵐᵖˡ).
Proof. Admitted.

End def.
End unknownValueType.

End attribute.
