(* autogenerated from go.etcd.io/etcd/server/v3/features *)
From New.golang Require Import defn.
Module pkg_id.
Definition features : go_string := "go.etcd.io/etcd/server/v3/features".

End pkg_id.
Export pkg_id.
Module features.

Axiom StopGRPCServiceOnDefrag : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom TxnModeWriteWithSharedBuffer : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom InitialCorruptCheck : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom CompactHashCheck : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom LeaseCheckpoint : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom LeaseCheckpointPersist : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom SetMemberLocalAddr : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom FastLeaseKeepAlive : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom PriorityRequest : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition DefaultEtcdServerFeatureGates {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/server/v3/features.DefaultEtcdServerFeatureGates"%go.

Axiom DefaultEtcdServerFeatureGates'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition NewDefaultServerFeatureGate {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/server/v3/features.NewDefaultServerFeatureGate"%go.

#[global] Instance info' : PkgInfo pkg_id.features :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.features (λ: <>,
      exception_do (do:  (DefaultEtcdServerFeatureGates'init #()))
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
}.
End features.
