(* autogenerated from github.com/goose-lang/goose/testdata/examples/async *)
Require Export New.code.github_com.goose_lang.primitive.async_disk.

From New.golang Require Import defn.
Definition async : go_string := "github.com/goose-lang/goose/testdata/examples/async".

From New Require Import async_disk_prelude.
Module async.

Section code.


Definition TakesDisk : go_string := "github.com/goose-lang/goose/testdata/examples/async.TakesDisk"%go.

(* go: async.go:6:6 *)
Definition TakesDiskⁱᵐᵖˡ : val :=
  λ: "d",
    exception_do (let: "d" := (mem.alloc "d") in
    do:  #()).

Definition UseDisk : go_string := "github.com/goose-lang/goose/testdata/examples/async.UseDisk"%go.

(* go: async.go:8:6 *)
Definition UseDiskⁱᵐᵖˡ : val :=
  λ: "d",
    exception_do (let: "d" := (mem.alloc "d") in
    let: "v" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (slice.make2 #byteT #(W64 4096)) in
    do:  ("v" <-[#sliceT] "$r0");;;
    do:  (let: "$a0" := #(W64 0) in
    let: "$a1" := (![#sliceT] "v") in
    (method_call #disk.Disk.id #"Write"%go (![#disk.Disk] "d")) "$a0" "$a1");;;
    do:  ((method_call #disk.Disk.id #"Barrier"%go (![#disk.Disk] "d")) #());;;
    return: #()).

Definition vars' : list (go_string * go_type) := [].

Definition functions' : list (go_string * val) := [(TakesDisk, TakesDiskⁱᵐᵖˡ); (UseDisk, UseDiskⁱᵐᵖˡ)].

Definition msets' : list (go_string * (list (go_string * val))) := [].

#[global] Instance info' : PkgInfo async.async :=
  {|
    pkg_vars := vars';
    pkg_functions := functions';
    pkg_msets := msets';
    pkg_imported_pkgs := [async_disk.async_disk];
  |}.

Definition initialize' : val :=
  λ: <>,
    package.init #async.async (λ: <>,
      exception_do (do:  (async_disk.initialize' #());;;
      do:  (package.alloc async.async #()))
      ).

End code.
End async.
