(* autogenerated from github.com/goose-lang/goose/testdata/examples/async *)
Require Export New.code.github_com.goose_lang.primitive.async_disk.

From New.golang Require Import defn.
Definition async : go_string := "github.com/goose-lang/goose/testdata/examples/async".

From New Require Import async_disk_prelude.
Module async.

Section code.


Definition TakesDisk : go_string := "github.com/goose-lang/goose/testdata/examples/async.TakesDisk"%go.

(* go: async.go:6:6 *)
Definition TakesDiskⁱᵐᵖˡ : val :=
  λ: "d",
    exception_do (let: "d" := (go.AllocValue disk.Disk "d") in
    do:  #()).

Definition UseDisk : go_string := "github.com/goose-lang/goose/testdata/examples/async.UseDisk"%go.

(* go: async.go:8:6 *)
Definition UseDiskⁱᵐᵖˡ : val :=
  λ: "d",
    exception_do (let: "d" := (go.AllocValue disk.Disk "d") in
    let: "v" := (GoAlloc (go.SliceType go.byte) #()) in
    let: "$r0" := ((FuncResolve go.make2 [go.SliceType go.byte] #()) #(W64 4096)) in
    do:  ("v" <-[go.SliceType go.byte] "$r0");;;
    do:  (let: "$a0" := #(W64 0) in
    let: "$a1" := (![go.SliceType go.byte] "v") in
    (MethodResolve disk.Disk Write #() (![disk.Disk] "d")) "$a0" "$a1");;;
    do:  ((MethodResolve disk.Disk Barrier #() (![disk.Disk] "d")) #());;;
    return: #()).

Definition functions' : list (go_string * val) := [(TakesDisk, TakesDiskⁱᵐᵖˡ); (UseDisk, UseDiskⁱᵐᵖˡ)].

#[global] Instance info' : PkgInfo async.async :=
  {|
    pkg_imported_pkgs := [code.github_com.goose_lang.primitive.async_disk.async_disk];
  |}.

Definition initialize' : val :=
  λ: <>,
    package.init async.async (λ: <>,
      exception_do (do:  (async_disk.initialize' #()))
      ).

End code.
End async.
