(* autogenerated from github.com/goose-lang/goose/testdata/examples/simpledb *)
From New.golang Require Import defn.
Require Export New.code.github_com.goose_lang.primitive.
Require Export New.code.github_com.goose_lang.primitive.filesys.
Require Export New.code.github_com.tchajed.marshal.
Require Export New.code.sync.

Definition simpledb : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb".

Module simpledb.
Section code.
Context `{ffi_syntax}.


Definition UseMarshal : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.UseMarshal"%go.

(* go: simpledb.go:20:6 *)
Definition UseMarshalⁱᵐᵖˡ : val :=
  λ: <>,
    exception_do (do:  (let: "$a0" := #(W64 0) in
    (func_call #marshal.NewEnc) "$a0");;;
    return: #()).

Definition Table : go_type := structT [
  "Index" :: mapT uint64T uint64T;
  "File" :: fileT
].

Definition Tableⁱᵈ : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.Table"%go.

Definition CreateTable : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.CreateTable"%go.

(* CreateTable creates a new, empty table.

   go: simpledb.go:32:6 *)
Definition CreateTableⁱᵐᵖˡ : val :=
  λ: "p",
    exception_do (let: "p" := (mem.alloc "p") in
    let: "index" := (mem.alloc (type.zero_val (type.mapT #uint64T #uint64T))) in
    let: "$r0" := (map.make #uint64T #uint64T) in
    do:  ("index" <-[type.mapT #uint64T #uint64T] "$r0");;;
    let: "f" := (mem.alloc (type.zero_val #fileT)) in
    let: ("$ret0", "$ret1") := (let: "$a0" := #"db"%go in
    let: "$a1" := (![#stringT] "p") in
    (func_call #filesys.Create) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("f" <-[#fileT] "$r0");;;
    do:  "$r1";;;
    do:  (let: "$a0" := (![#fileT] "f") in
    (func_call #filesys.Close) "$a0");;;
    let: "f2" := (mem.alloc (type.zero_val #fileT)) in
    let: "$r0" := (let: "$a0" := #"db"%go in
    let: "$a1" := (![#stringT] "p") in
    (func_call #filesys.Open) "$a0" "$a1") in
    do:  ("f2" <-[#fileT] "$r0");;;
    return: (let: "$Index" := (![type.mapT #uint64T #uint64T] "index") in
     let: "$File" := (![#fileT] "f2") in
     struct.make #Table [{
       "Index" ::= "$Index";
       "File" ::= "$File"
     }])).

Definition Entry : go_type := structT [
  "Key" :: uint64T;
  "Value" :: sliceT
].

Definition Entryⁱᵈ : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.Entry"%go.

Definition DecodeUInt64 : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.DecodeUInt64"%go.

(* DecodeUInt64 is a Decoder(uint64)

   All decoders have the shape func(p []byte) (T, uint64)

   The uint64 represents the number of bytes consumed; if 0,
   then decoding failed, and the value of type T should be ignored.

   go: simpledb.go:52:6 *)
Definition DecodeUInt64ⁱᵐᵖˡ : val :=
  λ: "p",
    exception_do (let: "p" := (mem.alloc "p") in
    (if: int_lt (let: "$a0" := (![#sliceT] "p") in
    slice.len "$a0") #(W64 8)
    then return: (#(W64 0), #(W64 0))
    else do:  #());;;
    let: "n" := (mem.alloc (type.zero_val #uint64T)) in
    let: "$r0" := (let: "$a0" := (![#sliceT] "p") in
    (func_call #primitive.UInt64Get) "$a0") in
    do:  ("n" <-[#uint64T] "$r0");;;
    return: (![#uint64T] "n", #(W64 8))).

Definition DecodeEntry : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.DecodeEntry"%go.

(* DecodeEntry is a Decoder(Entry)

   go: simpledb.go:61:6 *)
Definition DecodeEntryⁱᵐᵖˡ : val :=
  λ: "data",
    exception_do (let: "data" := (mem.alloc "data") in
    let: "l1" := (mem.alloc (type.zero_val #uint64T)) in
    let: "key" := (mem.alloc (type.zero_val #uint64T)) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![#sliceT] "data") in
    (func_call #DecodeUInt64) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("key" <-[#uint64T] "$r0");;;
    do:  ("l1" <-[#uint64T] "$r1");;;
    (if: (![#uint64T] "l1") = #(W64 0)
    then
      return: (let: "$Key" := #(W64 0) in
       let: "$Value" := #slice.nil in
       struct.make #Entry [{
         "Key" ::= "$Key";
         "Value" ::= "$Value"
       }], #(W64 0))
    else do:  #());;;
    let: "l2" := (mem.alloc (type.zero_val #uint64T)) in
    let: "valueLen" := (mem.alloc (type.zero_val #uint64T)) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$s" := (![#sliceT] "data") in
    slice.slice #byteT "$s" (![#uint64T] "l1") (slice.len "$s")) in
    (func_call #DecodeUInt64) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("valueLen" <-[#uint64T] "$r0");;;
    do:  ("l2" <-[#uint64T] "$r1");;;
    (if: (![#uint64T] "l2") = #(W64 0)
    then
      return: (let: "$Key" := #(W64 0) in
       let: "$Value" := #slice.nil in
       struct.make #Entry [{
         "Key" ::= "$Key";
         "Value" ::= "$Value"
       }], #(W64 0))
    else do:  #());;;
    (if: (s_to_w64 (let: "$a0" := (![#sliceT] "data") in
    slice.len "$a0")) < (((![#uint64T] "l1") + (![#uint64T] "l2")) + (![#uint64T] "valueLen"))
    then
      return: (let: "$Key" := #(W64 0) in
       let: "$Value" := #slice.nil in
       struct.make #Entry [{
         "Key" ::= "$Key";
         "Value" ::= "$Value"
       }], #(W64 0))
    else do:  #());;;
    let: "value" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$s" := (![#sliceT] "data") in
    slice.slice #byteT "$s" ((![#uint64T] "l1") + (![#uint64T] "l2")) (((![#uint64T] "l1") + (![#uint64T] "l2")) + (![#uint64T] "valueLen"))) in
    do:  ("value" <-[#sliceT] "$r0");;;
    return: (let: "$Key" := (![#uint64T] "key") in
     let: "$Value" := (![#sliceT] "value") in
     struct.make #Entry [{
       "Key" ::= "$Key";
       "Value" ::= "$Value"
     }], ((![#uint64T] "l1") + (![#uint64T] "l2")) + (![#uint64T] "valueLen"))).

Definition lazyFileBuf : go_type := structT [
  "offset" :: uint64T;
  "next" :: sliceT
].

Definition lazyFileBufⁱᵈ : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.lazyFileBuf"%go.

Definition readTableIndex : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.readTableIndex"%go.

(* readTableIndex parses a complete table on disk into a key->offset index

   go: simpledb.go:86:6 *)
Definition readTableIndexⁱᵐᵖˡ : val :=
  λ: "f" "index",
    exception_do (let: "index" := (mem.alloc "index") in
    let: "f" := (mem.alloc "f") in
    (let: "buf" := (mem.alloc (type.zero_val #lazyFileBuf)) in
    let: "$r0" := (let: "$offset" := #(W64 0) in
    let: "$next" := #slice.nil in
    struct.make #lazyFileBuf [{
      "offset" ::= "$offset";
      "next" ::= "$next"
    }]) in
    do:  ("buf" <-[#lazyFileBuf] "$r0");;;
    (for: (λ: <>, #true); (λ: <>, #()) := λ: <>,
      let: "l" := (mem.alloc (type.zero_val #uint64T)) in
      let: "e" := (mem.alloc (type.zero_val #Entry)) in
      let: ("$ret0", "$ret1") := (let: "$a0" := (![#sliceT] (struct.field_ref #lazyFileBuf #"next"%go "buf")) in
      (func_call #DecodeEntry) "$a0") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      do:  ("e" <-[#Entry] "$r0");;;
      do:  ("l" <-[#uint64T] "$r1");;;
      (if: (![#uint64T] "l") > #(W64 0)
      then
        let: "$r0" := (#(W64 8) + (![#uint64T] (struct.field_ref #lazyFileBuf #"offset"%go "buf"))) in
        do:  (map.insert (![type.mapT #uint64T #uint64T] "index") (![#uint64T] (struct.field_ref #Entry #"Key"%go "e")) "$r0");;;
        let: "$r0" := (let: "$offset" := ((![#uint64T] (struct.field_ref #lazyFileBuf #"offset"%go "buf")) + (![#uint64T] "l")) in
        let: "$next" := (let: "$s" := (![#sliceT] (struct.field_ref #lazyFileBuf #"next"%go "buf")) in
        slice.slice #byteT "$s" (![#uint64T] "l") (slice.len "$s")) in
        struct.make #lazyFileBuf [{
          "offset" ::= "$offset";
          "next" ::= "$next"
        }]) in
        do:  ("buf" <-[#lazyFileBuf] "$r0");;;
        continue: #()
      else
        let: "p" := (mem.alloc (type.zero_val #sliceT)) in
        let: "$r0" := (let: "$a0" := (![#fileT] "f") in
        let: "$a1" := ((![#uint64T] (struct.field_ref #lazyFileBuf #"offset"%go "buf")) + (s_to_w64 (let: "$a0" := (![#sliceT] (struct.field_ref #lazyFileBuf #"next"%go "buf")) in
        slice.len "$a0"))) in
        let: "$a2" := #(W64 4096) in
        (func_call #filesys.ReadAt) "$a0" "$a1" "$a2") in
        do:  ("p" <-[#sliceT] "$r0");;;
        (if: (let: "$a0" := (![#sliceT] "p") in
        slice.len "$a0") = #(W64 0)
        then break: #()
        else
          let: "newBuf" := (mem.alloc (type.zero_val #sliceT)) in
          let: "$r0" := (let: "$a0" := (![#sliceT] (struct.field_ref #lazyFileBuf #"next"%go "buf")) in
          let: "$a1" := (![#sliceT] "p") in
          (slice.append #byteT) "$a0" "$a1") in
          do:  ("newBuf" <-[#sliceT] "$r0");;;
          let: "$r0" := (let: "$offset" := (![#uint64T] (struct.field_ref #lazyFileBuf #"offset"%go "buf")) in
          let: "$next" := (![#sliceT] "newBuf") in
          struct.make #lazyFileBuf [{
            "offset" ::= "$offset";
            "next" ::= "$next"
          }]) in
          do:  ("buf" <-[#lazyFileBuf] "$r0");;;
          continue: #()))));;;
    return: #()).

Definition RecoverTable : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.RecoverTable"%go.

(* RecoverTable restores a table from disk on startup.

   go: simpledb.go:111:6 *)
Definition RecoverTableⁱᵐᵖˡ : val :=
  λ: "p",
    exception_do (let: "p" := (mem.alloc "p") in
    let: "index" := (mem.alloc (type.zero_val (type.mapT #uint64T #uint64T))) in
    let: "$r0" := (map.make #uint64T #uint64T) in
    do:  ("index" <-[type.mapT #uint64T #uint64T] "$r0");;;
    let: "f" := (mem.alloc (type.zero_val #fileT)) in
    let: "$r0" := (let: "$a0" := #"db"%go in
    let: "$a1" := (![#stringT] "p") in
    (func_call #filesys.Open) "$a0" "$a1") in
    do:  ("f" <-[#fileT] "$r0");;;
    do:  (let: "$a0" := (![#fileT] "f") in
    let: "$a1" := (![type.mapT #uint64T #uint64T] "index") in
    (func_call #readTableIndex) "$a0" "$a1");;;
    return: (let: "$Index" := (![type.mapT #uint64T #uint64T] "index") in
     let: "$File" := (![#fileT] "f") in
     struct.make #Table [{
       "Index" ::= "$Index";
       "File" ::= "$File"
     }])).

Definition CloseTable : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.CloseTable"%go.

(* CloseTable frees up the fd held by a table.

   go: simpledb.go:119:6 *)
Definition CloseTableⁱᵐᵖˡ : val :=
  λ: "t",
    exception_do (let: "t" := (mem.alloc "t") in
    do:  (let: "$a0" := (![#fileT] (struct.field_ref #Table #"File"%go "t")) in
    (func_call #filesys.Close) "$a0");;;
    return: #()).

Definition readValue : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.readValue"%go.

(* go: simpledb.go:123:6 *)
Definition readValueⁱᵐᵖˡ : val :=
  λ: "f" "off",
    exception_do (let: "off" := (mem.alloc "off") in
    let: "f" := (mem.alloc "f") in
    let: "startBuf" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (![#fileT] "f") in
    let: "$a1" := (![#uint64T] "off") in
    let: "$a2" := #(W64 512) in
    (func_call #filesys.ReadAt) "$a0" "$a1" "$a2") in
    do:  ("startBuf" <-[#sliceT] "$r0");;;
    let: "totalBytes" := (mem.alloc (type.zero_val #uint64T)) in
    let: "$r0" := (let: "$a0" := (![#sliceT] "startBuf") in
    (func_call #primitive.UInt64Get) "$a0") in
    do:  ("totalBytes" <-[#uint64T] "$r0");;;
    let: "buf" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$s" := (![#sliceT] "startBuf") in
    slice.slice #byteT "$s" #(W64 8) (slice.len "$s")) in
    do:  ("buf" <-[#sliceT] "$r0");;;
    let: "haveBytes" := (mem.alloc (type.zero_val #uint64T)) in
    let: "$r0" := (s_to_w64 (let: "$a0" := (![#sliceT] "buf") in
    slice.len "$a0")) in
    do:  ("haveBytes" <-[#uint64T] "$r0");;;
    (if: (![#uint64T] "haveBytes") < (![#uint64T] "totalBytes")
    then
      let: "buf2" := (mem.alloc (type.zero_val #sliceT)) in
      let: "$r0" := (let: "$a0" := (![#fileT] "f") in
      let: "$a1" := ((![#uint64T] "off") + #(W64 512)) in
      let: "$a2" := ((![#uint64T] "totalBytes") - (![#uint64T] "haveBytes")) in
      (func_call #filesys.ReadAt) "$a0" "$a1" "$a2") in
      do:  ("buf2" <-[#sliceT] "$r0");;;
      let: "newBuf" := (mem.alloc (type.zero_val #sliceT)) in
      let: "$r0" := (let: "$a0" := (![#sliceT] "buf") in
      let: "$a1" := (![#sliceT] "buf2") in
      (slice.append #byteT) "$a0" "$a1") in
      do:  ("newBuf" <-[#sliceT] "$r0");;;
      return: (![#sliceT] "newBuf")
    else do:  #());;;
    return: (let: "$s" := (![#sliceT] "buf") in
     slice.slice #byteT "$s" #(W64 0) (![#uint64T] "totalBytes"))).

Definition tableRead : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.tableRead"%go.

(* go: simpledb.go:137:6 *)
Definition tableReadⁱᵐᵖˡ : val :=
  λ: "t" "k",
    exception_do (let: "k" := (mem.alloc "k") in
    let: "t" := (mem.alloc "t") in
    let: "ok" := (mem.alloc (type.zero_val #boolT)) in
    let: "off" := (mem.alloc (type.zero_val #uint64T)) in
    let: ("$ret0", "$ret1") := (map.get (![type.mapT #uint64T #uint64T] (struct.field_ref #Table #"Index"%go "t")) (![#uint64T] "k")) in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("off" <-[#uint64T] "$r0");;;
    do:  ("ok" <-[#boolT] "$r1");;;
    (if: (~ (![#boolT] "ok"))
    then return: (#slice.nil, #false)
    else do:  #());;;
    let: "p" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (![#fileT] (struct.field_ref #Table #"File"%go "t")) in
    let: "$a1" := (![#uint64T] "off") in
    (func_call #readValue) "$a0" "$a1") in
    do:  ("p" <-[#sliceT] "$r0");;;
    return: (![#sliceT] "p", #true)).

Definition bufFile : go_type := structT [
  "file" :: fileT;
  "buf" :: ptrT
].

Definition bufFileⁱᵈ : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.bufFile"%go.

Definition newBuf : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.newBuf"%go.

(* go: simpledb.go:151:6 *)
Definition newBufⁱᵐᵖˡ : val :=
  λ: "f",
    exception_do (let: "f" := (mem.alloc "f") in
    let: "buf" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #sliceT)) in
    do:  ("buf" <-[#ptrT] "$r0");;;
    return: (let: "$file" := (![#fileT] "f") in
     let: "$buf" := (![#ptrT] "buf") in
     struct.make #bufFile [{
       "file" ::= "$file";
       "buf" ::= "$buf"
     }])).

Definition bufFlush : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.bufFlush"%go.

(* go: simpledb.go:159:6 *)
Definition bufFlushⁱᵐᵖˡ : val :=
  λ: "f",
    exception_do (let: "f" := (mem.alloc "f") in
    let: "buf" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (![#sliceT] (![#ptrT] (struct.field_ref #bufFile #"buf"%go "f"))) in
    do:  ("buf" <-[#sliceT] "$r0");;;
    (if: (let: "$a0" := (![#sliceT] "buf") in
    slice.len "$a0") = #(W64 0)
    then return: (#())
    else do:  #());;;
    do:  (let: "$a0" := (![#fileT] (struct.field_ref #bufFile #"file"%go "f")) in
    let: "$a1" := (![#sliceT] "buf") in
    (func_call #filesys.Append) "$a0" "$a1");;;
    let: "$r0" := #slice.nil in
    do:  ((![#ptrT] (struct.field_ref #bufFile #"buf"%go "f")) <-[#sliceT] "$r0");;;
    return: #()).

Definition bufAppend : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.bufAppend"%go.

(* go: simpledb.go:168:6 *)
Definition bufAppendⁱᵐᵖˡ : val :=
  λ: "f" "p",
    exception_do (let: "p" := (mem.alloc "p") in
    let: "f" := (mem.alloc "f") in
    let: "buf" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (![#sliceT] (![#ptrT] (struct.field_ref #bufFile #"buf"%go "f"))) in
    do:  ("buf" <-[#sliceT] "$r0");;;
    let: "buf2" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (![#sliceT] "buf") in
    let: "$a1" := (![#sliceT] "p") in
    (slice.append #byteT) "$a0" "$a1") in
    do:  ("buf2" <-[#sliceT] "$r0");;;
    let: "$r0" := (![#sliceT] "buf2") in
    do:  ((![#ptrT] (struct.field_ref #bufFile #"buf"%go "f")) <-[#sliceT] "$r0");;;
    return: #()).

Definition bufClose : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.bufClose"%go.

(* go: simpledb.go:174:6 *)
Definition bufCloseⁱᵐᵖˡ : val :=
  λ: "f",
    exception_do (let: "f" := (mem.alloc "f") in
    do:  (let: "$a0" := (![#bufFile] "f") in
    (func_call #bufFlush) "$a0");;;
    do:  (let: "$a0" := (![#fileT] (struct.field_ref #bufFile #"file"%go "f")) in
    (func_call #filesys.Close) "$a0");;;
    return: #()).

Definition tableWriter : go_type := structT [
  "index" :: mapT uint64T uint64T;
  "name" :: stringT;
  "file" :: bufFile;
  "offset" :: ptrT
].

Definition tableWriterⁱᵈ : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.tableWriter"%go.

Definition newTableWriter : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.newTableWriter"%go.

(* go: simpledb.go:186:6 *)
Definition newTableWriterⁱᵐᵖˡ : val :=
  λ: "p",
    exception_do (let: "p" := (mem.alloc "p") in
    let: "index" := (mem.alloc (type.zero_val (type.mapT #uint64T #uint64T))) in
    let: "$r0" := (map.make #uint64T #uint64T) in
    do:  ("index" <-[type.mapT #uint64T #uint64T] "$r0");;;
    let: "f" := (mem.alloc (type.zero_val #fileT)) in
    let: ("$ret0", "$ret1") := (let: "$a0" := #"db"%go in
    let: "$a1" := (![#stringT] "p") in
    (func_call #filesys.Create) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("f" <-[#fileT] "$r0");;;
    do:  "$r1";;;
    let: "buf" := (mem.alloc (type.zero_val #bufFile)) in
    let: "$r0" := (let: "$a0" := (![#fileT] "f") in
    (func_call #newBuf) "$a0") in
    do:  ("buf" <-[#bufFile] "$r0");;;
    let: "off" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #uint64T)) in
    do:  ("off" <-[#ptrT] "$r0");;;
    return: (let: "$index" := (![type.mapT #uint64T #uint64T] "index") in
     let: "$name" := (![#stringT] "p") in
     let: "$file" := (![#bufFile] "buf") in
     let: "$offset" := (![#ptrT] "off") in
     struct.make #tableWriter [{
       "index" ::= "$index";
       "name" ::= "$name";
       "file" ::= "$file";
       "offset" ::= "$offset"
     }])).

Definition tableWriterAppend : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.tableWriterAppend"%go.

(* go: simpledb.go:199:6 *)
Definition tableWriterAppendⁱᵐᵖˡ : val :=
  λ: "w" "p",
    exception_do (let: "p" := (mem.alloc "p") in
    let: "w" := (mem.alloc "w") in
    do:  (let: "$a0" := (![#bufFile] (struct.field_ref #tableWriter #"file"%go "w")) in
    let: "$a1" := (![#sliceT] "p") in
    (func_call #bufAppend) "$a0" "$a1");;;
    let: "off" := (mem.alloc (type.zero_val #uint64T)) in
    let: "$r0" := (![#uint64T] (![#ptrT] (struct.field_ref #tableWriter #"offset"%go "w"))) in
    do:  ("off" <-[#uint64T] "$r0");;;
    let: "$r0" := ((![#uint64T] "off") + (s_to_w64 (let: "$a0" := (![#sliceT] "p") in
    slice.len "$a0"))) in
    do:  ((![#ptrT] (struct.field_ref #tableWriter #"offset"%go "w")) <-[#uint64T] "$r0");;;
    return: #()).

Definition tableWriterClose : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.tableWriterClose"%go.

(* go: simpledb.go:205:6 *)
Definition tableWriterCloseⁱᵐᵖˡ : val :=
  λ: "w",
    exception_do (let: "w" := (mem.alloc "w") in
    do:  (let: "$a0" := (![#bufFile] (struct.field_ref #tableWriter #"file"%go "w")) in
    (func_call #bufClose) "$a0");;;
    let: "f" := (mem.alloc (type.zero_val #fileT)) in
    let: "$r0" := (let: "$a0" := #"db"%go in
    let: "$a1" := (![#stringT] (struct.field_ref #tableWriter #"name"%go "w")) in
    (func_call #filesys.Open) "$a0" "$a1") in
    do:  ("f" <-[#fileT] "$r0");;;
    return: (let: "$Index" := (![type.mapT #uint64T #uint64T] (struct.field_ref #tableWriter #"index"%go "w")) in
     let: "$File" := (![#fileT] "f") in
     struct.make #Table [{
       "Index" ::= "$Index";
       "File" ::= "$File"
     }])).

Definition EncodeUInt64 : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.EncodeUInt64"%go.

(* EncodeUInt64 is an Encoder(uint64)

   go: simpledb.go:215:6 *)
Definition EncodeUInt64ⁱᵐᵖˡ : val :=
  λ: "x" "p",
    exception_do (let: "p" := (mem.alloc "p") in
    let: "x" := (mem.alloc "x") in
    let: "tmp" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (slice.make2 #byteT #(W64 8)) in
    do:  ("tmp" <-[#sliceT] "$r0");;;
    do:  (let: "$a0" := (![#sliceT] "tmp") in
    let: "$a1" := (![#uint64T] "x") in
    (func_call #primitive.UInt64Put) "$a0" "$a1");;;
    let: "p2" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (![#sliceT] "p") in
    let: "$a1" := (![#sliceT] "tmp") in
    (slice.append #byteT) "$a0" "$a1") in
    do:  ("p2" <-[#sliceT] "$r0");;;
    return: (![#sliceT] "p2")).

Definition EncodeSlice : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.EncodeSlice"%go.

(* EncodeSlice is an Encoder([]byte)

   go: simpledb.go:223:6 *)
Definition EncodeSliceⁱᵐᵖˡ : val :=
  λ: "data" "p",
    exception_do (let: "p" := (mem.alloc "p") in
    let: "data" := (mem.alloc "data") in
    let: "p2" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (s_to_w64 (let: "$a0" := (![#sliceT] "data") in
    slice.len "$a0")) in
    let: "$a1" := (![#sliceT] "p") in
    (func_call #EncodeUInt64) "$a0" "$a1") in
    do:  ("p2" <-[#sliceT] "$r0");;;
    let: "p3" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (![#sliceT] "p2") in
    let: "$a1" := (![#sliceT] "data") in
    (slice.append #byteT) "$a0" "$a1") in
    do:  ("p3" <-[#sliceT] "$r0");;;
    return: (![#sliceT] "p3")).

Definition tablePut : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.tablePut"%go.

(* go: simpledb.go:229:6 *)
Definition tablePutⁱᵐᵖˡ : val :=
  λ: "w" "k" "v",
    exception_do (let: "v" := (mem.alloc "v") in
    let: "k" := (mem.alloc "k") in
    let: "w" := (mem.alloc "w") in
    let: "tmp" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (slice.make2 #byteT #(W64 0)) in
    do:  ("tmp" <-[#sliceT] "$r0");;;
    let: "tmp2" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (![#uint64T] "k") in
    let: "$a1" := (![#sliceT] "tmp") in
    (func_call #EncodeUInt64) "$a0" "$a1") in
    do:  ("tmp2" <-[#sliceT] "$r0");;;
    let: "tmp3" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (![#sliceT] "v") in
    let: "$a1" := (![#sliceT] "tmp2") in
    (func_call #EncodeSlice) "$a0" "$a1") in
    do:  ("tmp3" <-[#sliceT] "$r0");;;
    let: "off" := (mem.alloc (type.zero_val #uint64T)) in
    let: "$r0" := (![#uint64T] (![#ptrT] (struct.field_ref #tableWriter #"offset"%go "w"))) in
    do:  ("off" <-[#uint64T] "$r0");;;
    let: "$r0" := ((![#uint64T] "off") + (s_to_w64 (let: "$a0" := (![#sliceT] "tmp2") in
    slice.len "$a0"))) in
    do:  (map.insert (![type.mapT #uint64T #uint64T] (struct.field_ref #tableWriter #"index"%go "w")) (![#uint64T] "k") "$r0");;;
    do:  (let: "$a0" := (![#tableWriter] "w") in
    let: "$a1" := (![#sliceT] "tmp3") in
    (func_call #tableWriterAppend) "$a0" "$a1");;;
    return: #()).

Definition Database : go_type := structT [
  "wbuffer" :: ptrT;
  "rbuffer" :: ptrT;
  "bufferL" :: ptrT;
  "table" :: ptrT;
  "tableName" :: ptrT;
  "tableL" :: ptrT;
  "compactionL" :: ptrT
].

Definition Databaseⁱᵈ : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.Database"%go.

Definition makeValueBuffer : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.makeValueBuffer"%go.

(* go: simpledb.go:256:6 *)
Definition makeValueBufferⁱᵐᵖˡ : val :=
  λ: <>,
    exception_do (let: "buf" := (mem.alloc (type.zero_val (type.mapT #uint64T #sliceT))) in
    let: "$r0" := (map.make #uint64T #sliceT) in
    do:  ("buf" <-[type.mapT #uint64T #sliceT] "$r0");;;
    let: "bufPtr" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val (type.mapT #uint64T #sliceT))) in
    do:  ("bufPtr" <-[#ptrT] "$r0");;;
    let: "$r0" := (![type.mapT #uint64T #sliceT] "buf") in
    do:  ((![#ptrT] "bufPtr") <-[type.mapT #uint64T #sliceT] "$r0");;;
    return: (![#ptrT] "bufPtr")).

Definition NewDb : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.NewDb"%go.

(* NewDb initializes a new database on top of an empty filesys.

   go: simpledb.go:264:6 *)
Definition NewDbⁱᵐᵖˡ : val :=
  λ: <>,
    exception_do (let: "wbuf" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := ((func_call #makeValueBuffer) #()) in
    do:  ("wbuf" <-[#ptrT] "$r0");;;
    let: "rbuf" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := ((func_call #makeValueBuffer) #()) in
    do:  ("rbuf" <-[#ptrT] "$r0");;;
    let: "bufferL" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #sync.Mutex)) in
    do:  ("bufferL" <-[#ptrT] "$r0");;;
    let: "tableName" := (mem.alloc (type.zero_val #stringT)) in
    let: "$r0" := #"table.0"%go in
    do:  ("tableName" <-[#stringT] "$r0");;;
    let: "tableNameRef" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #stringT)) in
    do:  ("tableNameRef" <-[#ptrT] "$r0");;;
    let: "$r0" := (![#stringT] "tableName") in
    do:  ((![#ptrT] "tableNameRef") <-[#stringT] "$r0");;;
    let: "table" := (mem.alloc (type.zero_val #Table)) in
    let: "$r0" := (let: "$a0" := (![#stringT] "tableName") in
    (func_call #CreateTable) "$a0") in
    do:  ("table" <-[#Table] "$r0");;;
    let: "tableRef" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #Table)) in
    do:  ("tableRef" <-[#ptrT] "$r0");;;
    let: "$r0" := (![#Table] "table") in
    do:  ((![#ptrT] "tableRef") <-[#Table] "$r0");;;
    let: "tableL" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #sync.Mutex)) in
    do:  ("tableL" <-[#ptrT] "$r0");;;
    let: "compactionL" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #sync.Mutex)) in
    do:  ("compactionL" <-[#ptrT] "$r0");;;
    return: (let: "$wbuffer" := (![#ptrT] "wbuf") in
     let: "$rbuffer" := (![#ptrT] "rbuf") in
     let: "$bufferL" := (![#ptrT] "bufferL") in
     let: "$table" := (![#ptrT] "tableRef") in
     let: "$tableName" := (![#ptrT] "tableNameRef") in
     let: "$tableL" := (![#ptrT] "tableL") in
     let: "$compactionL" := (![#ptrT] "compactionL") in
     struct.make #Database [{
       "wbuffer" ::= "$wbuffer";
       "rbuffer" ::= "$rbuffer";
       "bufferL" ::= "$bufferL";
       "table" ::= "$table";
       "tableName" ::= "$tableName";
       "tableL" ::= "$tableL";
       "compactionL" ::= "$compactionL"
     }])).

Definition Read : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.Read"%go.

(* Read gets a key from the database.

   Returns a boolean indicating if the k was found and a non-nil slice with
   the value if k was in the database.

   Reflects any completed in-memory writes.

   go: simpledb.go:293:6 *)
Definition Readⁱᵐᵖˡ : val :=
  λ: "db" "k",
    exception_do (let: "k" := (mem.alloc "k") in
    let: "db" := (mem.alloc "db") in
    do:  ((method_call #sync #"Mutex'ptr" #"Lock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
    let: "buf" := (mem.alloc (type.zero_val (type.mapT #uint64T #sliceT))) in
    let: "$r0" := (![type.mapT #uint64T #sliceT] (![#ptrT] (struct.field_ref #Database #"wbuffer"%go "db"))) in
    do:  ("buf" <-[type.mapT #uint64T #sliceT] "$r0");;;
    let: "ok" := (mem.alloc (type.zero_val #boolT)) in
    let: "v" := (mem.alloc (type.zero_val #sliceT)) in
    let: ("$ret0", "$ret1") := (map.get (![type.mapT #uint64T #sliceT] "buf") (![#uint64T] "k")) in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("v" <-[#sliceT] "$r0");;;
    do:  ("ok" <-[#boolT] "$r1");;;
    (if: ![#boolT] "ok"
    then
      do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
      return: (![#sliceT] "v", #true)
    else do:  #());;;
    let: "rbuf" := (mem.alloc (type.zero_val (type.mapT #uint64T #sliceT))) in
    let: "$r0" := (![type.mapT #uint64T #sliceT] (![#ptrT] (struct.field_ref #Database #"rbuffer"%go "db"))) in
    do:  ("rbuf" <-[type.mapT #uint64T #sliceT] "$r0");;;
    let: "v2" := (mem.alloc (type.zero_val #sliceT)) in
    let: ("$ret0", "$ret1") := (map.get (![type.mapT #uint64T #sliceT] "rbuf") (![#uint64T] "k")) in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("v2" <-[#sliceT] "$r0");;;
    do:  ("ok" <-[#boolT] "$r1");;;
    (if: ![#boolT] "ok"
    then
      do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
      return: (![#sliceT] "v2", #true)
    else do:  #());;;
    do:  ((method_call #sync #"Mutex'ptr" #"Lock" (![#ptrT] (struct.field_ref #Database #"tableL"%go "db"))) #());;;
    let: "tbl" := (mem.alloc (type.zero_val #Table)) in
    let: "$r0" := (![#Table] (![#ptrT] (struct.field_ref #Database #"table"%go "db"))) in
    do:  ("tbl" <-[#Table] "$r0");;;
    let: "v3" := (mem.alloc (type.zero_val #sliceT)) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![#Table] "tbl") in
    let: "$a1" := (![#uint64T] "k") in
    (func_call #tableRead) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("v3" <-[#sliceT] "$r0");;;
    do:  ("ok" <-[#boolT] "$r1");;;
    do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"tableL"%go "db"))) #());;;
    do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
    return: (![#sliceT] "v3", ![#boolT] "ok")).

Definition Write : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.Write"%go.

(* Write sets a key to a new value.

   Creates a new key-value mapping if k is not in the database and overwrites
   the previous value if k is present.

   The new value is buffered in memory. To persist it, call db.Compact().

   go: simpledb.go:326:6 *)
Definition Writeⁱᵐᵖˡ : val :=
  λ: "db" "k" "v",
    exception_do (let: "v" := (mem.alloc "v") in
    let: "k" := (mem.alloc "k") in
    let: "db" := (mem.alloc "db") in
    do:  ((method_call #sync #"Mutex'ptr" #"Lock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
    let: "buf" := (mem.alloc (type.zero_val (type.mapT #uint64T #sliceT))) in
    let: "$r0" := (![type.mapT #uint64T #sliceT] (![#ptrT] (struct.field_ref #Database #"wbuffer"%go "db"))) in
    do:  ("buf" <-[type.mapT #uint64T #sliceT] "$r0");;;
    let: "$r0" := (![#sliceT] "v") in
    do:  (map.insert (![type.mapT #uint64T #sliceT] "buf") (![#uint64T] "k") "$r0");;;
    do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
    return: #()).

Definition freshTable : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.freshTable"%go.

(* go: simpledb.go:333:6 *)
Definition freshTableⁱᵐᵖˡ : val :=
  λ: "p",
    exception_do (let: "p" := (mem.alloc "p") in
    (if: (![#stringT] "p") = #"table.0"%go
    then return: (#"table.1"%go)
    else do:  #());;;
    (if: (![#stringT] "p") = #"table.1"%go
    then return: (#"table.0"%go)
    else do:  #());;;
    return: (![#stringT] "p")).

Definition tablePutBuffer : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.tablePutBuffer"%go.

(* go: simpledb.go:345:6 *)
Definition tablePutBufferⁱᵐᵖˡ : val :=
  λ: "w" "buf",
    exception_do (let: "buf" := (mem.alloc "buf") in
    let: "w" := (mem.alloc "w") in
    let: "$range" := (![type.mapT #uint64T #sliceT] "buf") in
    (let: "v" := (mem.alloc (type.zero_val #sliceT)) in
    let: "k" := (mem.alloc (type.zero_val #uint64T)) in
    map.for_range "$range" (λ: "$key" "value",
      do:  ("v" <-[#sliceT] "$value");;;
      do:  ("k" <-[#uint64T] "$key");;;
      do:  (let: "$a0" := (![#tableWriter] "w") in
      let: "$a1" := (![#uint64T] "k") in
      let: "$a2" := (![#sliceT] "v") in
      (func_call #tablePut) "$a0" "$a1" "$a2")));;;
    return: #()).

Definition tablePutOldTable : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.tablePutOldTable"%go.

(* add all of table t to the table w being created; skip any keys in the (read)
   buffer b since those writes overwrite old ones

   go: simpledb.go:353:6 *)
Definition tablePutOldTableⁱᵐᵖˡ : val :=
  λ: "w" "t" "b",
    exception_do (let: "b" := (mem.alloc "b") in
    let: "t" := (mem.alloc "t") in
    let: "w" := (mem.alloc "w") in
    (let: "buf" := (mem.alloc (type.zero_val #lazyFileBuf)) in
    let: "$r0" := (let: "$offset" := #(W64 0) in
    let: "$next" := #slice.nil in
    struct.make #lazyFileBuf [{
      "offset" ::= "$offset";
      "next" ::= "$next"
    }]) in
    do:  ("buf" <-[#lazyFileBuf] "$r0");;;
    (for: (λ: <>, #true); (λ: <>, #()) := λ: <>,
      let: "l" := (mem.alloc (type.zero_val #uint64T)) in
      let: "e" := (mem.alloc (type.zero_val #Entry)) in
      let: ("$ret0", "$ret1") := (let: "$a0" := (![#sliceT] (struct.field_ref #lazyFileBuf #"next"%go "buf")) in
      (func_call #DecodeEntry) "$a0") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      do:  ("e" <-[#Entry] "$r0");;;
      do:  ("l" <-[#uint64T] "$r1");;;
      (if: (![#uint64T] "l") > #(W64 0)
      then
        let: "ok" := (mem.alloc (type.zero_val #boolT)) in
        let: ("$ret0", "$ret1") := (map.get (![type.mapT #uint64T #sliceT] "b") (![#uint64T] (struct.field_ref #Entry #"Key"%go "e"))) in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  "$r0";;;
        do:  ("ok" <-[#boolT] "$r1");;;
        (if: (~ (![#boolT] "ok"))
        then
          do:  (let: "$a0" := (![#tableWriter] "w") in
          let: "$a1" := (![#uint64T] (struct.field_ref #Entry #"Key"%go "e")) in
          let: "$a2" := (![#sliceT] (struct.field_ref #Entry #"Value"%go "e")) in
          (func_call #tablePut) "$a0" "$a1" "$a2")
        else do:  #());;;
        let: "$r0" := (let: "$offset" := ((![#uint64T] (struct.field_ref #lazyFileBuf #"offset"%go "buf")) + (![#uint64T] "l")) in
        let: "$next" := (let: "$s" := (![#sliceT] (struct.field_ref #lazyFileBuf #"next"%go "buf")) in
        slice.slice #byteT "$s" (![#uint64T] "l") (slice.len "$s")) in
        struct.make #lazyFileBuf [{
          "offset" ::= "$offset";
          "next" ::= "$next"
        }]) in
        do:  ("buf" <-[#lazyFileBuf] "$r0");;;
        continue: #()
      else
        let: "p" := (mem.alloc (type.zero_val #sliceT)) in
        let: "$r0" := (let: "$a0" := (![#fileT] (struct.field_ref #Table #"File"%go "t")) in
        let: "$a1" := ((![#uint64T] (struct.field_ref #lazyFileBuf #"offset"%go "buf")) + (s_to_w64 (let: "$a0" := (![#sliceT] (struct.field_ref #lazyFileBuf #"next"%go "buf")) in
        slice.len "$a0"))) in
        let: "$a2" := #(W64 4096) in
        (func_call #filesys.ReadAt) "$a0" "$a1" "$a2") in
        do:  ("p" <-[#sliceT] "$r0");;;
        (if: (let: "$a0" := (![#sliceT] "p") in
        slice.len "$a0") = #(W64 0)
        then break: #()
        else
          let: "newBuf" := (mem.alloc (type.zero_val #sliceT)) in
          let: "$r0" := (let: "$a0" := (![#sliceT] (struct.field_ref #lazyFileBuf #"next"%go "buf")) in
          let: "$a1" := (![#sliceT] "p") in
          (slice.append #byteT) "$a0" "$a1") in
          do:  ("newBuf" <-[#sliceT] "$r0");;;
          let: "$r0" := (let: "$offset" := (![#uint64T] (struct.field_ref #lazyFileBuf #"offset"%go "buf")) in
          let: "$next" := (![#sliceT] "newBuf") in
          struct.make #lazyFileBuf [{
            "offset" ::= "$offset";
            "next" ::= "$next"
          }]) in
          do:  ("buf" <-[#lazyFileBuf] "$r0");;;
          continue: #()))));;;
    return: #()).

Definition constructNewTable : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.constructNewTable"%go.

(* Build a new shadow table that incorporates the current table and a
   (write) buffer wbuf.

   Assumes all the appropriate locks have been taken.

   Returns the old table and new table.

   go: simpledb.go:388:6 *)
Definition constructNewTableⁱᵐᵖˡ : val :=
  λ: "db" "wbuf",
    exception_do (let: "wbuf" := (mem.alloc "wbuf") in
    let: "db" := (mem.alloc "db") in
    let: "oldName" := (mem.alloc (type.zero_val #stringT)) in
    let: "$r0" := (![#stringT] (![#ptrT] (struct.field_ref #Database #"tableName"%go "db"))) in
    do:  ("oldName" <-[#stringT] "$r0");;;
    let: "name" := (mem.alloc (type.zero_val #stringT)) in
    let: "$r0" := (let: "$a0" := (![#stringT] "oldName") in
    (func_call #freshTable) "$a0") in
    do:  ("name" <-[#stringT] "$r0");;;
    let: "w" := (mem.alloc (type.zero_val #tableWriter)) in
    let: "$r0" := (let: "$a0" := (![#stringT] "name") in
    (func_call #newTableWriter) "$a0") in
    do:  ("w" <-[#tableWriter] "$r0");;;
    let: "oldTable" := (mem.alloc (type.zero_val #Table)) in
    let: "$r0" := (![#Table] (![#ptrT] (struct.field_ref #Database #"table"%go "db"))) in
    do:  ("oldTable" <-[#Table] "$r0");;;
    do:  (let: "$a0" := (![#tableWriter] "w") in
    let: "$a1" := (![#Table] "oldTable") in
    let: "$a2" := (![type.mapT #uint64T #sliceT] "wbuf") in
    (func_call #tablePutOldTable) "$a0" "$a1" "$a2");;;
    do:  (let: "$a0" := (![#tableWriter] "w") in
    let: "$a1" := (![type.mapT #uint64T #sliceT] "wbuf") in
    (func_call #tablePutBuffer) "$a0" "$a1");;;
    let: "newTable" := (mem.alloc (type.zero_val #Table)) in
    let: "$r0" := (let: "$a0" := (![#tableWriter] "w") in
    (func_call #tableWriterClose) "$a0") in
    do:  ("newTable" <-[#Table] "$r0");;;
    return: (![#Table] "oldTable", ![#Table] "newTable")).

Definition Compact : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.Compact"%go.

(* Compact persists in-memory writes to a new table.

   This simple database design must re-write all data to combine in-memory
   writes with existing writes.

   go: simpledb.go:405:6 *)
Definition Compactⁱᵐᵖˡ : val :=
  λ: "db",
    exception_do (let: "db" := (mem.alloc "db") in
    do:  ((method_call #sync #"Mutex'ptr" #"Lock" (![#ptrT] (struct.field_ref #Database #"compactionL"%go "db"))) #());;;
    do:  ((method_call #sync #"Mutex'ptr" #"Lock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
    let: "buf" := (mem.alloc (type.zero_val (type.mapT #uint64T #sliceT))) in
    let: "$r0" := (![type.mapT #uint64T #sliceT] (![#ptrT] (struct.field_ref #Database #"wbuffer"%go "db"))) in
    do:  ("buf" <-[type.mapT #uint64T #sliceT] "$r0");;;
    let: "emptyWbuffer" := (mem.alloc (type.zero_val (type.mapT #uint64T #sliceT))) in
    let: "$r0" := (map.make #uint64T #sliceT) in
    do:  ("emptyWbuffer" <-[type.mapT #uint64T #sliceT] "$r0");;;
    let: "$r0" := (![type.mapT #uint64T #sliceT] "emptyWbuffer") in
    do:  ((![#ptrT] (struct.field_ref #Database #"wbuffer"%go "db")) <-[type.mapT #uint64T #sliceT] "$r0");;;
    let: "$r0" := (![type.mapT #uint64T #sliceT] "buf") in
    do:  ((![#ptrT] (struct.field_ref #Database #"rbuffer"%go "db")) <-[type.mapT #uint64T #sliceT] "$r0");;;
    do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
    do:  ((method_call #sync #"Mutex'ptr" #"Lock" (![#ptrT] (struct.field_ref #Database #"tableL"%go "db"))) #());;;
    let: "oldTableName" := (mem.alloc (type.zero_val #stringT)) in
    let: "$r0" := (![#stringT] (![#ptrT] (struct.field_ref #Database #"tableName"%go "db"))) in
    do:  ("oldTableName" <-[#stringT] "$r0");;;
    let: "t" := (mem.alloc (type.zero_val #Table)) in
    let: "oldTable" := (mem.alloc (type.zero_val #Table)) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![#Database] "db") in
    let: "$a1" := (![type.mapT #uint64T #sliceT] "buf") in
    (func_call #constructNewTable) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("oldTable" <-[#Table] "$r0");;;
    do:  ("t" <-[#Table] "$r1");;;
    let: "newTable" := (mem.alloc (type.zero_val #stringT)) in
    let: "$r0" := (let: "$a0" := (![#stringT] "oldTableName") in
    (func_call #freshTable) "$a0") in
    do:  ("newTable" <-[#stringT] "$r0");;;
    let: "$r0" := (![#Table] "t") in
    do:  ((![#ptrT] (struct.field_ref #Database #"table"%go "db")) <-[#Table] "$r0");;;
    let: "$r0" := (![#stringT] "newTable") in
    do:  ((![#ptrT] (struct.field_ref #Database #"tableName"%go "db")) <-[#stringT] "$r0");;;
    let: "manifestData" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (string.to_bytes (![#stringT] "newTable")) in
    do:  ("manifestData" <-[#sliceT] "$r0");;;
    do:  (let: "$a0" := #"db"%go in
    let: "$a1" := #"manifest"%go in
    let: "$a2" := (![#sliceT] "manifestData") in
    (func_call #filesys.AtomicCreate) "$a0" "$a1" "$a2");;;
    do:  (let: "$a0" := (![#Table] "oldTable") in
    (func_call #CloseTable) "$a0");;;
    do:  (let: "$a0" := #"db"%go in
    let: "$a1" := (![#stringT] "oldTableName") in
    (func_call #filesys.Delete) "$a0" "$a1");;;
    do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"tableL"%go "db"))) #());;;
    do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"compactionL"%go "db"))) #());;;
    return: #()).

Definition recoverManifest : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.recoverManifest"%go.

(* go: simpledb.go:450:6 *)
Definition recoverManifestⁱᵐᵖˡ : val :=
  λ: <>,
    exception_do (let: "f" := (mem.alloc (type.zero_val #fileT)) in
    let: "$r0" := (let: "$a0" := #"db"%go in
    let: "$a1" := #"manifest"%go in
    (func_call #filesys.Open) "$a0" "$a1") in
    do:  ("f" <-[#fileT] "$r0");;;
    let: "manifestData" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (![#fileT] "f") in
    let: "$a1" := #(W64 0) in
    let: "$a2" := #(W64 4096) in
    (func_call #filesys.ReadAt) "$a0" "$a1" "$a2") in
    do:  ("manifestData" <-[#sliceT] "$r0");;;
    let: "tableName" := (mem.alloc (type.zero_val #stringT)) in
    let: "$r0" := (string.from_bytes (![#sliceT] "manifestData")) in
    do:  ("tableName" <-[#stringT] "$r0");;;
    do:  (let: "$a0" := (![#fileT] "f") in
    (func_call #filesys.Close) "$a0");;;
    return: (![#stringT] "tableName")).

Definition deleteOtherFile : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.deleteOtherFile"%go.

(* delete 'name' if it isn't tableName or "manifest"

   go: simpledb.go:464:6 *)
Definition deleteOtherFileⁱᵐᵖˡ : val :=
  λ: "name" "tableName",
    exception_do (let: "tableName" := (mem.alloc "tableName") in
    let: "name" := (mem.alloc "name") in
    (if: (![#stringT] "name") = (![#stringT] "tableName")
    then return: (#())
    else do:  #());;;
    (if: (![#stringT] "name") = #"manifest"%go
    then return: (#())
    else do:  #());;;
    do:  (let: "$a0" := #"db"%go in
    let: "$a1" := (![#stringT] "name") in
    (func_call #filesys.Delete) "$a0" "$a1");;;
    return: #()).

Definition deleteOtherFiles : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.deleteOtherFiles"%go.

(* go: simpledb.go:474:6 *)
Definition deleteOtherFilesⁱᵐᵖˡ : val :=
  λ: "tableName",
    exception_do (let: "tableName" := (mem.alloc "tableName") in
    let: "files" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := #"db"%go in
    (func_call #filesys.List) "$a0") in
    do:  ("files" <-[#sliceT] "$r0");;;
    let: "nfiles" := (mem.alloc (type.zero_val #uint64T)) in
    let: "$r0" := (s_to_w64 (let: "$a0" := (![#sliceT] "files") in
    slice.len "$a0")) in
    do:  ("nfiles" <-[#uint64T] "$r0");;;
    (let: "i" := (mem.alloc (type.zero_val #uint64T)) in
    let: "$r0" := #(W64 0) in
    do:  ("i" <-[#uint64T] "$r0");;;
    (for: (λ: <>, #true); (λ: <>, #()) := λ: <>,
      (if: (![#uint64T] "i") = (![#uint64T] "nfiles")
      then break: #()
      else do:  #());;;
      let: "name" := (mem.alloc (type.zero_val #stringT)) in
      let: "$r0" := (![#stringT] (slice.elem_ref #stringT (![#sliceT] "files") (![#uint64T] "i"))) in
      do:  ("name" <-[#stringT] "$r0");;;
      do:  (let: "$a0" := (![#stringT] "name") in
      let: "$a1" := (![#stringT] "tableName") in
      (func_call #deleteOtherFile) "$a0" "$a1");;;
      let: "$r0" := ((![#uint64T] "i") + #(W64 1)) in
      do:  ("i" <-[#uint64T] "$r0");;;
      continue: #()));;;
    return: #()).

Definition Recover : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.Recover"%go.

(* Recover restores a previously created database after a crash or shutdown.

   go: simpledb.go:489:6 *)
Definition Recoverⁱᵐᵖˡ : val :=
  λ: <>,
    exception_do (let: "tableName" := (mem.alloc (type.zero_val #stringT)) in
    let: "$r0" := ((func_call #recoverManifest) #()) in
    do:  ("tableName" <-[#stringT] "$r0");;;
    let: "table" := (mem.alloc (type.zero_val #Table)) in
    let: "$r0" := (let: "$a0" := (![#stringT] "tableName") in
    (func_call #RecoverTable) "$a0") in
    do:  ("table" <-[#Table] "$r0");;;
    let: "tableRef" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #Table)) in
    do:  ("tableRef" <-[#ptrT] "$r0");;;
    let: "$r0" := (![#Table] "table") in
    do:  ((![#ptrT] "tableRef") <-[#Table] "$r0");;;
    let: "tableNameRef" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #stringT)) in
    do:  ("tableNameRef" <-[#ptrT] "$r0");;;
    let: "$r0" := (![#stringT] "tableName") in
    do:  ((![#ptrT] "tableNameRef") <-[#stringT] "$r0");;;
    do:  (let: "$a0" := (![#stringT] "tableName") in
    (func_call #deleteOtherFiles) "$a0");;;
    let: "wbuffer" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := ((func_call #makeValueBuffer) #()) in
    do:  ("wbuffer" <-[#ptrT] "$r0");;;
    let: "rbuffer" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := ((func_call #makeValueBuffer) #()) in
    do:  ("rbuffer" <-[#ptrT] "$r0");;;
    let: "bufferL" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #sync.Mutex)) in
    do:  ("bufferL" <-[#ptrT] "$r0");;;
    let: "tableL" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #sync.Mutex)) in
    do:  ("tableL" <-[#ptrT] "$r0");;;
    let: "compactionL" := (mem.alloc (type.zero_val #ptrT)) in
    let: "$r0" := (mem.alloc (type.zero_val #sync.Mutex)) in
    do:  ("compactionL" <-[#ptrT] "$r0");;;
    return: (let: "$wbuffer" := (![#ptrT] "wbuffer") in
     let: "$rbuffer" := (![#ptrT] "rbuffer") in
     let: "$bufferL" := (![#ptrT] "bufferL") in
     let: "$table" := (![#ptrT] "tableRef") in
     let: "$tableName" := (![#ptrT] "tableNameRef") in
     let: "$tableL" := (![#ptrT] "tableL") in
     let: "$compactionL" := (![#ptrT] "compactionL") in
     struct.make #Database [{
       "wbuffer" ::= "$wbuffer";
       "rbuffer" ::= "$rbuffer";
       "bufferL" ::= "$bufferL";
       "table" ::= "$table";
       "tableName" ::= "$tableName";
       "tableL" ::= "$tableL";
       "compactionL" ::= "$compactionL"
     }])).

Definition Shutdown : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.Shutdown"%go.

(* Shutdown immediately closes the database.

   Discards any uncommitted in-memory writes; similar to a crash except for
   cleanly closing any open files.

   go: simpledb.go:520:6 *)
Definition Shutdownⁱᵐᵖˡ : val :=
  λ: "db",
    exception_do (let: "db" := (mem.alloc "db") in
    do:  ((method_call #sync #"Mutex'ptr" #"Lock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
    do:  ((method_call #sync #"Mutex'ptr" #"Lock" (![#ptrT] (struct.field_ref #Database #"compactionL"%go "db"))) #());;;
    let: "t" := (mem.alloc (type.zero_val #Table)) in
    let: "$r0" := (![#Table] (![#ptrT] (struct.field_ref #Database #"table"%go "db"))) in
    do:  ("t" <-[#Table] "$r0");;;
    do:  (let: "$a0" := (![#Table] "t") in
    (func_call #CloseTable) "$a0");;;
    do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"compactionL"%go "db"))) #());;;
    do:  ((method_call #sync #"Mutex'ptr" #"Unlock" (![#ptrT] (struct.field_ref #Database #"bufferL"%go "db"))) #());;;
    return: #()).

Definition Close : go_string := "github.com/goose-lang/goose/testdata/examples/simpledb.Close"%go.

(* Close closes an open database cleanly, flushing any in-memory writes.

   db should not be used afterward

   go: simpledb.go:534:6 *)
Definition Closeⁱᵐᵖˡ : val :=
  λ: "db",
    exception_do (let: "db" := (mem.alloc "db") in
    do:  (let: "$a0" := (![#Database] "db") in
    (func_call #Compact) "$a0");;;
    do:  (let: "$a0" := (![#Database] "db") in
    (func_call #Shutdown) "$a0");;;
    return: #()).

Definition vars' : list (go_string * go_type) := [].

Definition functions' : list (go_string * val) := [(UseMarshal, UseMarshalⁱᵐᵖˡ); (CreateTable, CreateTableⁱᵐᵖˡ); (DecodeUInt64, DecodeUInt64ⁱᵐᵖˡ); (DecodeEntry, DecodeEntryⁱᵐᵖˡ); (readTableIndex, readTableIndexⁱᵐᵖˡ); (RecoverTable, RecoverTableⁱᵐᵖˡ); (CloseTable, CloseTableⁱᵐᵖˡ); (readValue, readValueⁱᵐᵖˡ); (tableRead, tableReadⁱᵐᵖˡ); (newBuf, newBufⁱᵐᵖˡ); (bufFlush, bufFlushⁱᵐᵖˡ); (bufAppend, bufAppendⁱᵐᵖˡ); (bufClose, bufCloseⁱᵐᵖˡ); (newTableWriter, newTableWriterⁱᵐᵖˡ); (tableWriterAppend, tableWriterAppendⁱᵐᵖˡ); (tableWriterClose, tableWriterCloseⁱᵐᵖˡ); (EncodeUInt64, EncodeUInt64ⁱᵐᵖˡ); (EncodeSlice, EncodeSliceⁱᵐᵖˡ); (tablePut, tablePutⁱᵐᵖˡ); (makeValueBuffer, makeValueBufferⁱᵐᵖˡ); (NewDb, NewDbⁱᵐᵖˡ); (Read, Readⁱᵐᵖˡ); (Write, Writeⁱᵐᵖˡ); (freshTable, freshTableⁱᵐᵖˡ); (tablePutBuffer, tablePutBufferⁱᵐᵖˡ); (tablePutOldTable, tablePutOldTableⁱᵐᵖˡ); (constructNewTable, constructNewTableⁱᵐᵖˡ); (Compact, Compactⁱᵐᵖˡ); (recoverManifest, recoverManifestⁱᵐᵖˡ); (deleteOtherFile, deleteOtherFileⁱᵐᵖˡ); (deleteOtherFiles, deleteOtherFilesⁱᵐᵖˡ); (Recover, Recoverⁱᵐᵖˡ); (Shutdown, Shutdownⁱᵐᵖˡ); (Close, Closeⁱᵐᵖˡ)].

Definition msets' : list (go_string * (list (go_string * val))) := [("Table"%go, []); ("Table'ptr"%go, []); ("Entry"%go, []); ("Entry'ptr"%go, []); ("lazyFileBuf"%go, []); ("lazyFileBuf'ptr"%go, []); ("bufFile"%go, []); ("bufFile'ptr"%go, []); ("tableWriter"%go, []); ("tableWriter'ptr"%go, []); ("Database"%go, []); ("Database'ptr"%go, [])].

#[global] Instance info' : PkgInfo simpledb.simpledb :=
  {|
    pkg_vars := vars';
    pkg_functions := functions';
    pkg_msets := msets';
    pkg_imported_pkgs := [sync.sync; primitive.primitive; filesys.filesys; marshal.marshal];
  |}.

Definition initialize' : val :=
  λ: <>,
    package.init #simpledb.simpledb (λ: <>,
      exception_do (do:  (marshal.initialize' #());;;
      do:  (filesys.initialize' #());;;
      do:  (primitive.initialize' #());;;
      do:  (sync.initialize' #());;;
      do:  (package.alloc simpledb.simpledb #()))
      ).

End code.
End simpledb.
