(* autogenerated from go.opentelemetry.io/otel/attribute *)
From New.golang Require Import defn.
Module pkg_id.
Definition attribute : go_string := "go.opentelemetry.io/otel/attribute".

End pkg_id.
Export pkg_id.
Module attribute.

Definition Encoder {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.Encoder"%go [].

#[global] Opaque Encoder.

Definition EncoderID {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.EncoderID"%go [].

#[global] Opaque EncoderID.

Definition defaultAttrEncoder {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.defaultAttrEncoder"%go [].

#[global] Opaque defaultAttrEncoder.

Definition Filter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.Filter"%go [].

#[global] Opaque Filter.

Definition Iterator {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.Iterator"%go [].

#[global] Opaque Iterator.

Definition MergeIterator {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.MergeIterator"%go [].

#[global] Opaque MergeIterator.

Definition oneIterator {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.oneIterator"%go [].

#[global] Opaque oneIterator.

Definition Key {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.Key"%go [].

#[global] Opaque Key.

Definition KeyValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.KeyValue"%go [].

#[global] Opaque KeyValue.

Definition Set' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.Set"%go [].

#[global] Opaque Set'.

Definition Distinct {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.Distinct"%go [].

#[global] Opaque Distinct.

Definition Sortable {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.Sortable"%go [].

#[global] Opaque Sortable.

Definition Type' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.Type"%go [].

#[global] Opaque Type'.

Definition Value {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.Value"%go [].

#[global] Opaque Value.

Definition unknownValueType {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/attribute.unknownValueType"%go [].

#[global] Opaque unknownValueType.

Axiom Encoderⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom EncoderIDⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom defaultAttrEncoderⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Filterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Iteratorⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom MergeIteratorⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom oneIteratorⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Keyⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom KeyValueⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Set'ⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Distinctⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Sortableⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Type'ⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Valueⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom unknownValueTypeⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom escapeChar : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom boolID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom int64ID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom float64ID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom stringID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom boolSliceID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom int64SliceID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom float64SliceID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom stringSliceID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom _Type_name : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom INVALID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom BOOL : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom INT64 : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom FLOAT64 : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom STRING : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom BOOLSLICE : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom INT64SLICE : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom FLOAT64SLICE : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom STRINGSLICE : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition encoderIDCounter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.encoderIDCounter"%go.

Definition defaultEncoderOnce {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.defaultEncoderOnce"%go.

Definition defaultEncoderID {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.defaultEncoderID"%go.

Axiom defaultEncoderID'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition defaultEncoderInstance {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.defaultEncoderInstance"%go.

Definition keyValueType {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.keyValueType"%go.

Axiom keyValueType'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition emptyHash {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.emptyHash"%go.

Axiom emptyHash'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition userDefinedEmptySet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.userDefinedEmptySet"%go.

Axiom userDefinedEmptySet'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition emptySet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.emptySet"%go.

Axiom emptySet'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition _Type_index {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute._Type_index"%go.

Axiom _Type_index'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition NewEncoderID {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.NewEncoderID"%go.

Definition DefaultEncoder {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.DefaultEncoder"%go.

Definition copyAndEscape {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.copyAndEscape"%go.

Definition NewAllowKeysFilter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.NewAllowKeysFilter"%go.

Definition NewDenyKeysFilter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.NewDenyKeysFilter"%go.

Definition hashKVs {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.hashKVs"%go.

Definition hashKV {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.hashKV"%go.

Definition NewMergeIterator {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.NewMergeIterator"%go.

Definition makeOne {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.makeOne"%go.

Definition Bool {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Bool"%go.

Definition BoolSlice {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.BoolSlice"%go.

Definition Int {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Int"%go.

Definition IntSlice {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.IntSlice"%go.

Definition Int64 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Int64"%go.

Definition Int64Slice {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Int64Slice"%go.

Definition Float64 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Float64"%go.

Definition Float64Slice {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Float64Slice"%go.

Definition String {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.String"%go.

Definition StringSlice {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.StringSlice"%go.

Definition Stringer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Stringer"%go.

Definition boolToRaw {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.boolToRaw"%go.

Definition rawToBool {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.rawToBool"%go.

Definition int64ToRaw {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.int64ToRaw"%go.

Definition rawToInt64 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.rawToInt64"%go.

Definition float64ToRaw {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.float64ToRaw"%go.

Definition rawToFloat64 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.rawToFloat64"%go.

Definition isComparable {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.isComparable"%go.

Definition EmptySet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.EmptySet"%go.

Definition NewSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.NewSet"%go.

Definition NewSetWithSortable {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.NewSetWithSortable"%go.

Definition NewSetWithFiltered {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.NewSetWithFiltered"%go.

Definition NewSetWithSortableFiltered {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.NewSetWithSortableFiltered"%go.

Definition filteredToFront {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.filteredToFront"%go.

Definition newSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.newSet"%go.

Definition computeDataFixed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.computeDataFixed"%go.

Definition computeDataReflect {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.computeDataReflect"%go.

Definition BoolValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.BoolValue"%go.

Definition BoolSliceValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.BoolSliceValue"%go.

Definition IntValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.IntValue"%go.

Definition IntSliceValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.IntSliceValue"%go.

Definition Int64Value {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Int64Value"%go.

Definition Int64SliceValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Int64SliceValue"%go.

Definition Float64Value {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Float64Value"%go.

Definition Float64SliceValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.Float64SliceValue"%go.

Definition StringValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.StringValue"%go.

Definition StringSliceValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/attribute.StringSliceValue"%go.

#[global] Instance info' : PkgInfo pkg_id.attribute :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.attribute (λ: <>,
      exception_do (do:  (_'init #());;;
      do:  (defaultEncoderID'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (keyValueType'init #());;;
      do:  (emptyHash'init #());;;
      do:  (userDefinedEmptySet'init #());;;
      do:  (emptySet'init #());;;
      do:  (_Type_index'init #()))
      ).

Module Encoder.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Encoder.

Class Encoder_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Encoder_type_repr  :: go.TypeReprUnderlying Encoderⁱᵐᵖˡ Encoder.t;
  #[global] Encoder_underlying :: (Encoder) <u (Encoderⁱᵐᵖˡ);
  #[global] Encoderⁱᵐᵖˡ_underlying :: (Encoderⁱᵐᵖˡ) ↓u (Encoderⁱᵐᵖˡ);
}.

Module EncoderID.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End EncoderID.

Class EncoderID_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] EncoderID_type_repr  :: go.TypeReprUnderlying EncoderIDⁱᵐᵖˡ EncoderID.t;
  #[global] EncoderID_underlying :: (EncoderID) <u (EncoderIDⁱᵐᵖˡ);
  #[global] EncoderIDⁱᵐᵖˡ_underlying :: (EncoderIDⁱᵐᵖˡ) ↓u (EncoderIDⁱᵐᵖˡ);
}.

Module defaultAttrEncoder.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End defaultAttrEncoder.

Class defaultAttrEncoder_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] defaultAttrEncoder_type_repr  :: go.TypeReprUnderlying defaultAttrEncoderⁱᵐᵖˡ defaultAttrEncoder.t;
  #[global] defaultAttrEncoder_underlying :: (defaultAttrEncoder) <u (defaultAttrEncoderⁱᵐᵖˡ);
  #[global] defaultAttrEncoderⁱᵐᵖˡ_underlying :: (defaultAttrEncoderⁱᵐᵖˡ) ↓u (defaultAttrEncoderⁱᵐᵖˡ);
}.

Module Filter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Filter.

Class Filter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Filter_type_repr  :: go.TypeReprUnderlying Filterⁱᵐᵖˡ Filter.t;
  #[global] Filter_underlying :: (Filter) <u (Filterⁱᵐᵖˡ);
  #[global] Filterⁱᵐᵖˡ_underlying :: (Filterⁱᵐᵖˡ) ↓u (Filterⁱᵐᵖˡ);
}.

Module Iterator.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Iterator.

Class Iterator_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Iterator_type_repr  :: go.TypeReprUnderlying Iteratorⁱᵐᵖˡ Iterator.t;
  #[global] Iterator_underlying :: (Iterator) <u (Iteratorⁱᵐᵖˡ);
  #[global] Iteratorⁱᵐᵖˡ_underlying :: (Iteratorⁱᵐᵖˡ) ↓u (Iteratorⁱᵐᵖˡ);
}.

Module MergeIterator.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End MergeIterator.

Class MergeIterator_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] MergeIterator_type_repr  :: go.TypeReprUnderlying MergeIteratorⁱᵐᵖˡ MergeIterator.t;
  #[global] MergeIterator_underlying :: (MergeIterator) <u (MergeIteratorⁱᵐᵖˡ);
  #[global] MergeIteratorⁱᵐᵖˡ_underlying :: (MergeIteratorⁱᵐᵖˡ) ↓u (MergeIteratorⁱᵐᵖˡ);
}.

Module oneIterator.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End oneIterator.

Class oneIterator_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] oneIterator_type_repr  :: go.TypeReprUnderlying oneIteratorⁱᵐᵖˡ oneIterator.t;
  #[global] oneIterator_underlying :: (oneIterator) <u (oneIteratorⁱᵐᵖˡ);
  #[global] oneIteratorⁱᵐᵖˡ_underlying :: (oneIteratorⁱᵐᵖˡ) ↓u (oneIteratorⁱᵐᵖˡ);
}.

Module Key.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Key.

Class Key_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Key_type_repr  :: go.TypeReprUnderlying Keyⁱᵐᵖˡ Key.t;
  #[global] Key_underlying :: (Key) <u (Keyⁱᵐᵖˡ);
  #[global] Keyⁱᵐᵖˡ_underlying :: (Keyⁱᵐᵖˡ) ↓u (Keyⁱᵐᵖˡ);
}.

Module KeyValue.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End KeyValue.

Class KeyValue_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] KeyValue_type_repr  :: go.TypeReprUnderlying KeyValueⁱᵐᵖˡ KeyValue.t;
  #[global] KeyValue_underlying :: (KeyValue) <u (KeyValueⁱᵐᵖˡ);
  #[global] KeyValueⁱᵐᵖˡ_underlying :: (KeyValueⁱᵐᵖˡ) ↓u (KeyValueⁱᵐᵖˡ);
}.

Module Set'.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Set'.

Class Set_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Set_type_repr  :: go.TypeReprUnderlying Set'ⁱᵐᵖˡ Set'.t;
  #[global] Set_underlying :: (Set') <u (Set'ⁱᵐᵖˡ);
  #[global] Set'ⁱᵐᵖˡ_underlying :: (Set'ⁱᵐᵖˡ) ↓u (Set'ⁱᵐᵖˡ);
}.

Module Distinct.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Distinct.

Class Distinct_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Distinct_type_repr  :: go.TypeReprUnderlying Distinctⁱᵐᵖˡ Distinct.t;
  #[global] Distinct_underlying :: (Distinct) <u (Distinctⁱᵐᵖˡ);
  #[global] Distinctⁱᵐᵖˡ_underlying :: (Distinctⁱᵐᵖˡ) ↓u (Distinctⁱᵐᵖˡ);
}.

Module Sortable.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Sortable.

Class Sortable_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Sortable_type_repr  :: go.TypeReprUnderlying Sortableⁱᵐᵖˡ Sortable.t;
  #[global] Sortable_underlying :: (Sortable) <u (Sortableⁱᵐᵖˡ);
  #[global] Sortableⁱᵐᵖˡ_underlying :: (Sortableⁱᵐᵖˡ) ↓u (Sortableⁱᵐᵖˡ);
}.

Module Type'.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Type'.

Class Type_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Type_type_repr  :: go.TypeReprUnderlying Type'ⁱᵐᵖˡ Type'.t;
  #[global] Type_underlying :: (Type') <u (Type'ⁱᵐᵖˡ);
  #[global] Type'ⁱᵐᵖˡ_underlying :: (Type'ⁱᵐᵖˡ) ↓u (Type'ⁱᵐᵖˡ);
}.

Module Value.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Value.

Class Value_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Value_type_repr  :: go.TypeReprUnderlying Valueⁱᵐᵖˡ Value.t;
  #[global] Value_underlying :: (Value) <u (Valueⁱᵐᵖˡ);
  #[global] Valueⁱᵐᵖˡ_underlying :: (Valueⁱᵐᵖˡ) ↓u (Valueⁱᵐᵖˡ);
}.

Module unknownValueType.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End unknownValueType.

Class unknownValueType_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] unknownValueType_type_repr  :: go.TypeReprUnderlying unknownValueTypeⁱᵐᵖˡ unknownValueType.t;
  #[global] unknownValueType_underlying :: (unknownValueType) <u (unknownValueTypeⁱᵐᵖˡ);
  #[global] unknownValueTypeⁱᵐᵖˡ_underlying :: (unknownValueTypeⁱᵐᵖˡ) ↓u (unknownValueTypeⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Encoder_instance :: Encoder_Assumptions;
  #[global] EncoderID_instance :: EncoderID_Assumptions;
  #[global] defaultAttrEncoder_instance :: defaultAttrEncoder_Assumptions;
  #[global] Filter_instance :: Filter_Assumptions;
  #[global] Iterator_instance :: Iterator_Assumptions;
  #[global] MergeIterator_instance :: MergeIterator_Assumptions;
  #[global] oneIterator_instance :: oneIterator_Assumptions;
  #[global] Key_instance :: Key_Assumptions;
  #[global] KeyValue_instance :: KeyValue_Assumptions;
  #[global] Set_instance :: Set_Assumptions;
  #[global] Distinct_instance :: Distinct_Assumptions;
  #[global] Sortable_instance :: Sortable_Assumptions;
  #[global] Type_instance :: Type_Assumptions;
  #[global] Value_instance :: Value_Assumptions;
  #[global] unknownValueType_instance :: unknownValueType_Assumptions;
}.
End attribute.
