(* autogenerated from go.opentelemetry.io/otel/trace *)
From New.golang Require Import defn.
Module pkg_id.
Definition trace : go_string := "go.opentelemetry.io/otel/trace".

End pkg_id.
Export pkg_id.
Module trace.

Definition autoTracerProvider {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.autoTracerProvider"%go [].

#[global] Opaque autoTracerProvider.

Definition autoTracer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.autoTracer"%go [].

#[global] Opaque autoTracer.

Definition autoSpan {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.autoSpan"%go [].

#[global] Opaque autoSpan.

Definition spanLimits {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.spanLimits"%go [].

#[global] Opaque spanLimits.

Definition TracerConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.TracerConfig"%go [].

#[global] Opaque TracerConfig.

Definition TracerOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.TracerOption"%go [].

#[global] Opaque TracerOption.

Definition tracerOptionFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.tracerOptionFunc"%go [].

#[global] Opaque tracerOptionFunc.

Definition SpanConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanConfig"%go [].

#[global] Opaque SpanConfig.

Definition SpanStartOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanStartOption"%go [].

#[global] Opaque SpanStartOption.

Definition spanOptionFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.spanOptionFunc"%go [].

#[global] Opaque spanOptionFunc.

Definition SpanEndOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanEndOption"%go [].

#[global] Opaque SpanEndOption.

Definition EventConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.EventConfig"%go [].

#[global] Opaque EventConfig.

Definition EventOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.EventOption"%go [].

#[global] Opaque EventOption.

Definition SpanOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanOption"%go [].

#[global] Opaque SpanOption.

Definition SpanStartEventOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanStartEventOption"%go [].

#[global] Opaque SpanStartEventOption.

Definition SpanEndEventOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanEndEventOption"%go [].

#[global] Opaque SpanEndEventOption.

Definition attributeOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.attributeOption"%go [].

#[global] Opaque attributeOption.

Definition SpanEventOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanEventOption"%go [].

#[global] Opaque SpanEventOption.

Definition timestampOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.timestampOption"%go [].

#[global] Opaque timestampOption.

Definition stackTraceOption {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.stackTraceOption"%go [].

#[global] Opaque stackTraceOption.

Definition traceContextKeyType {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.traceContextKeyType"%go [].

#[global] Opaque traceContextKeyType.

Definition nonRecordingSpan {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.nonRecordingSpan"%go [].

#[global] Opaque nonRecordingSpan.

Definition noopTracerProvider {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.noopTracerProvider"%go [].

#[global] Opaque noopTracerProvider.

Definition noopTracer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.noopTracer"%go [].

#[global] Opaque noopTracer.

Definition noopSpan {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.noopSpan"%go [].

#[global] Opaque noopSpan.

Definition TracerProvider {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.TracerProvider"%go [].

#[global] Opaque TracerProvider.

Definition Span {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.Span"%go [].

#[global] Opaque Span.

Definition Link {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.Link"%go [].

#[global] Opaque Link.

Definition SpanKind {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanKind"%go [].

#[global] Opaque SpanKind.

Definition errorConst {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.errorConst"%go [].

#[global] Opaque errorConst.

Definition TraceID {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.TraceID"%go [].

#[global] Opaque TraceID.

Definition SpanID {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanID"%go [].

#[global] Opaque SpanID.

Definition TraceFlags {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.TraceFlags"%go [].

#[global] Opaque TraceFlags.

Definition SpanContextConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanContextConfig"%go [].

#[global] Opaque SpanContextConfig.

Definition SpanContext {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.SpanContext"%go [].

#[global] Opaque SpanContext.

Definition Tracer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.Tracer"%go [].

#[global] Opaque Tracer.

Definition member {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.member"%go [].

#[global] Opaque member.

Definition TraceState {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.opentelemetry.io/otel/trace.TraceState"%go [].

#[global] Opaque TraceState.

Axiom autoTracerProviderⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom autoTracerⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom autoSpanⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom spanLimitsⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom TracerConfigⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom TracerOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom tracerOptionFuncⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanConfigⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanStartOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom spanOptionFuncⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanEndOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom EventConfigⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom EventOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanStartEventOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanEndEventOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom attributeOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanEventOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom timestampOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom stackTraceOptionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom traceContextKeyTypeⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom nonRecordingSpanⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom noopTracerProviderⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom noopTracerⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom noopSpanⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom TracerProviderⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Spanⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Linkⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanKindⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom errorConstⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom TraceIDⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanIDⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom TraceFlagsⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanContextConfigⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SpanContextⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Tracerⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom memberⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom TraceStateⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom currentSpanKey : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom hexLU : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom hexRev : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom SpanKindUnspecified : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom SpanKindInternal : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom SpanKindServer : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom SpanKindClient : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom SpanKindProducer : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom SpanKindConsumer : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom FlagsSampled : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom FlagsRandom : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errInvalidHexID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errInvalidTraceIDLength : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errNilTraceID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errInvalidSpanIDLength : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errNilSpanID : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom maxListMembers : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom listDelimiters : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom memberDelimiter : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errInvalidKey : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errInvalidValue : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errInvalidMember : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errMemberNumber : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom errDuplicate : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition tracerProviderInstance {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.tracerProviderInstance"%go.

Axiom tracerProviderInstance'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition start {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.start"%go.

Axiom start'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ended {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.ended"%go.

Axiom ended'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition maxSpan {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.maxSpan"%go.

Axiom maxSpan'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition noopSpanInstance {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.noopSpanInstance"%go.

Axiom noopSpanInstance'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition autoInstEnabled {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.autoInstEnabled"%go.

Axiom autoInstEnabled'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition nilTraceID {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.nilTraceID"%go.

Definition nilSpanID {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.nilSpanID"%go.

Definition newAutoTracerProvider {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.newAutoTracerProvider"%go.

Definition spanKind {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.spanKind"%go.

Definition convCappedAttrs {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.convCappedAttrs"%go.

Definition convAttrs {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.convAttrs"%go.

Definition convAttrValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.convAttrValue"%go.

Definition truncate {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.truncate"%go.

Definition typeStr {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.typeStr"%go.

Definition convLinks {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.convLinks"%go.

Definition convLink {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.convLink"%go.

Definition newSpanLimits {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.newSpanLimits"%go.

Definition firstEnv {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.firstEnv"%go.

Definition NewTracerConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.NewTracerConfig"%go.

Definition NewSpanStartConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.NewSpanStartConfig"%go.

Definition NewSpanEndConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.NewSpanEndConfig"%go.

Definition NewEventConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.NewEventConfig"%go.

Definition WithAttributes {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithAttributes"%go.

Definition WithTimestamp {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithTimestamp"%go.

Definition WithStackTrace {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithStackTrace"%go.

Definition WithLinks {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithLinks"%go.

Definition WithNewRoot {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithNewRoot"%go.

Definition WithSpanKind {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithSpanKind"%go.

Definition WithInstrumentationVersion {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithInstrumentationVersion"%go.

Definition mergeSets {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.mergeSets"%go.

Definition WithInstrumentationAttributes {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithInstrumentationAttributes"%go.

Definition WithInstrumentationAttributeSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithInstrumentationAttributeSet"%go.

Definition WithSchemaURL {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.WithSchemaURL"%go.

Definition ContextWithSpan {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.ContextWithSpan"%go.

Definition ContextWithSpanContext {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.ContextWithSpanContext"%go.

Definition ContextWithRemoteSpanContext {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.ContextWithRemoteSpanContext"%go.

Definition SpanFromContext {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.SpanFromContext"%go.

Definition SpanContextFromContext {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.SpanContextFromContext"%go.

Definition NewNoopTracerProvider {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.NewNoopTracerProvider"%go.

Definition LinkFromContext {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.LinkFromContext"%go.

Definition ValidateSpanKind {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.ValidateSpanKind"%go.

Definition TraceIDFromHex {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.TraceIDFromHex"%go.

Definition SpanIDFromHex {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.SpanIDFromHex"%go.

Definition NewSpanContext {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.NewSpanContext"%go.

Definition checkValueChar {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.checkValueChar"%go.

Definition checkValueLast {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.checkValueLast"%go.

Definition checkValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.checkValue"%go.

Definition checkKeyRemain {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.checkKeyRemain"%go.

Definition checkKeyPart {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.checkKeyPart"%go.

Definition isAlphaNumASCII {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.isAlphaNumASCII"%go.

Definition checkKeyTenant {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.checkKeyTenant"%go.

Definition checkKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.checkKey"%go.

Definition newMember {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.newMember"%go.

Definition parseMember {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.parseMember"%go.

Definition ParseTraceState {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.opentelemetry.io/otel/trace.ParseTraceState"%go.

#[global] Instance info' : PkgInfo pkg_id.trace :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.trace (λ: <>,
      exception_do (do:  (tracerProviderInstance'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (start'init #());;;
      do:  (ended'init #());;;
      do:  (maxSpan'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (noopSpanInstance'init #());;;
      do:  (autoInstEnabled'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #()))
      ).

Module autoTracerProvider.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End autoTracerProvider.

Class autoTracerProvider_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] autoTracerProvider_type_repr  :: go.TypeReprUnderlying autoTracerProviderⁱᵐᵖˡ autoTracerProvider.t;
  #[global] autoTracerProvider_underlying :: (autoTracerProvider) <u (autoTracerProviderⁱᵐᵖˡ);
  #[global] autoTracerProviderⁱᵐᵖˡ_underlying :: (autoTracerProviderⁱᵐᵖˡ) ↓u (autoTracerProviderⁱᵐᵖˡ);
}.

Module autoTracer.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End autoTracer.

Class autoTracer_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] autoTracer_type_repr  :: go.TypeReprUnderlying autoTracerⁱᵐᵖˡ autoTracer.t;
  #[global] autoTracer_underlying :: (autoTracer) <u (autoTracerⁱᵐᵖˡ);
  #[global] autoTracerⁱᵐᵖˡ_underlying :: (autoTracerⁱᵐᵖˡ) ↓u (autoTracerⁱᵐᵖˡ);
}.

Module autoSpan.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End autoSpan.

Class autoSpan_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] autoSpan_type_repr  :: go.TypeReprUnderlying autoSpanⁱᵐᵖˡ autoSpan.t;
  #[global] autoSpan_underlying :: (autoSpan) <u (autoSpanⁱᵐᵖˡ);
  #[global] autoSpanⁱᵐᵖˡ_underlying :: (autoSpanⁱᵐᵖˡ) ↓u (autoSpanⁱᵐᵖˡ);
}.

Module spanLimits.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End spanLimits.

Class spanLimits_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] spanLimits_type_repr  :: go.TypeReprUnderlying spanLimitsⁱᵐᵖˡ spanLimits.t;
  #[global] spanLimits_underlying :: (spanLimits) <u (spanLimitsⁱᵐᵖˡ);
  #[global] spanLimitsⁱᵐᵖˡ_underlying :: (spanLimitsⁱᵐᵖˡ) ↓u (spanLimitsⁱᵐᵖˡ);
}.

Module TracerConfig.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End TracerConfig.

Class TracerConfig_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] TracerConfig_type_repr  :: go.TypeReprUnderlying TracerConfigⁱᵐᵖˡ TracerConfig.t;
  #[global] TracerConfig_underlying :: (TracerConfig) <u (TracerConfigⁱᵐᵖˡ);
  #[global] TracerConfigⁱᵐᵖˡ_underlying :: (TracerConfigⁱᵐᵖˡ) ↓u (TracerConfigⁱᵐᵖˡ);
}.

Module TracerOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End TracerOption.

Class TracerOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] TracerOption_type_repr  :: go.TypeReprUnderlying TracerOptionⁱᵐᵖˡ TracerOption.t;
  #[global] TracerOption_underlying :: (TracerOption) <u (TracerOptionⁱᵐᵖˡ);
  #[global] TracerOptionⁱᵐᵖˡ_underlying :: (TracerOptionⁱᵐᵖˡ) ↓u (TracerOptionⁱᵐᵖˡ);
}.

Module tracerOptionFunc.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End tracerOptionFunc.

Class tracerOptionFunc_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] tracerOptionFunc_type_repr  :: go.TypeReprUnderlying tracerOptionFuncⁱᵐᵖˡ tracerOptionFunc.t;
  #[global] tracerOptionFunc_underlying :: (tracerOptionFunc) <u (tracerOptionFuncⁱᵐᵖˡ);
  #[global] tracerOptionFuncⁱᵐᵖˡ_underlying :: (tracerOptionFuncⁱᵐᵖˡ) ↓u (tracerOptionFuncⁱᵐᵖˡ);
}.

Module SpanConfig.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanConfig.

Class SpanConfig_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanConfig_type_repr  :: go.TypeReprUnderlying SpanConfigⁱᵐᵖˡ SpanConfig.t;
  #[global] SpanConfig_underlying :: (SpanConfig) <u (SpanConfigⁱᵐᵖˡ);
  #[global] SpanConfigⁱᵐᵖˡ_underlying :: (SpanConfigⁱᵐᵖˡ) ↓u (SpanConfigⁱᵐᵖˡ);
}.

Module SpanStartOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanStartOption.

Class SpanStartOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanStartOption_type_repr  :: go.TypeReprUnderlying SpanStartOptionⁱᵐᵖˡ SpanStartOption.t;
  #[global] SpanStartOption_underlying :: (SpanStartOption) <u (SpanStartOptionⁱᵐᵖˡ);
  #[global] SpanStartOptionⁱᵐᵖˡ_underlying :: (SpanStartOptionⁱᵐᵖˡ) ↓u (SpanStartOptionⁱᵐᵖˡ);
}.

Module spanOptionFunc.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End spanOptionFunc.

Class spanOptionFunc_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] spanOptionFunc_type_repr  :: go.TypeReprUnderlying spanOptionFuncⁱᵐᵖˡ spanOptionFunc.t;
  #[global] spanOptionFunc_underlying :: (spanOptionFunc) <u (spanOptionFuncⁱᵐᵖˡ);
  #[global] spanOptionFuncⁱᵐᵖˡ_underlying :: (spanOptionFuncⁱᵐᵖˡ) ↓u (spanOptionFuncⁱᵐᵖˡ);
}.

Module SpanEndOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanEndOption.

Class SpanEndOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanEndOption_type_repr  :: go.TypeReprUnderlying SpanEndOptionⁱᵐᵖˡ SpanEndOption.t;
  #[global] SpanEndOption_underlying :: (SpanEndOption) <u (SpanEndOptionⁱᵐᵖˡ);
  #[global] SpanEndOptionⁱᵐᵖˡ_underlying :: (SpanEndOptionⁱᵐᵖˡ) ↓u (SpanEndOptionⁱᵐᵖˡ);
}.

Module EventConfig.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End EventConfig.

Class EventConfig_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] EventConfig_type_repr  :: go.TypeReprUnderlying EventConfigⁱᵐᵖˡ EventConfig.t;
  #[global] EventConfig_underlying :: (EventConfig) <u (EventConfigⁱᵐᵖˡ);
  #[global] EventConfigⁱᵐᵖˡ_underlying :: (EventConfigⁱᵐᵖˡ) ↓u (EventConfigⁱᵐᵖˡ);
}.

Module EventOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End EventOption.

Class EventOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] EventOption_type_repr  :: go.TypeReprUnderlying EventOptionⁱᵐᵖˡ EventOption.t;
  #[global] EventOption_underlying :: (EventOption) <u (EventOptionⁱᵐᵖˡ);
  #[global] EventOptionⁱᵐᵖˡ_underlying :: (EventOptionⁱᵐᵖˡ) ↓u (EventOptionⁱᵐᵖˡ);
}.

Module SpanOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanOption.

Class SpanOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanOption_type_repr  :: go.TypeReprUnderlying SpanOptionⁱᵐᵖˡ SpanOption.t;
  #[global] SpanOption_underlying :: (SpanOption) <u (SpanOptionⁱᵐᵖˡ);
  #[global] SpanOptionⁱᵐᵖˡ_underlying :: (SpanOptionⁱᵐᵖˡ) ↓u (SpanOptionⁱᵐᵖˡ);
}.

Module SpanStartEventOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanStartEventOption.

Class SpanStartEventOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanStartEventOption_type_repr  :: go.TypeReprUnderlying SpanStartEventOptionⁱᵐᵖˡ SpanStartEventOption.t;
  #[global] SpanStartEventOption_underlying :: (SpanStartEventOption) <u (SpanStartEventOptionⁱᵐᵖˡ);
  #[global] SpanStartEventOptionⁱᵐᵖˡ_underlying :: (SpanStartEventOptionⁱᵐᵖˡ) ↓u (SpanStartEventOptionⁱᵐᵖˡ);
}.

Module SpanEndEventOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanEndEventOption.

Class SpanEndEventOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanEndEventOption_type_repr  :: go.TypeReprUnderlying SpanEndEventOptionⁱᵐᵖˡ SpanEndEventOption.t;
  #[global] SpanEndEventOption_underlying :: (SpanEndEventOption) <u (SpanEndEventOptionⁱᵐᵖˡ);
  #[global] SpanEndEventOptionⁱᵐᵖˡ_underlying :: (SpanEndEventOptionⁱᵐᵖˡ) ↓u (SpanEndEventOptionⁱᵐᵖˡ);
}.

Module attributeOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End attributeOption.

Class attributeOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] attributeOption_type_repr  :: go.TypeReprUnderlying attributeOptionⁱᵐᵖˡ attributeOption.t;
  #[global] attributeOption_underlying :: (attributeOption) <u (attributeOptionⁱᵐᵖˡ);
  #[global] attributeOptionⁱᵐᵖˡ_underlying :: (attributeOptionⁱᵐᵖˡ) ↓u (attributeOptionⁱᵐᵖˡ);
}.

Module SpanEventOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanEventOption.

Class SpanEventOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanEventOption_type_repr  :: go.TypeReprUnderlying SpanEventOptionⁱᵐᵖˡ SpanEventOption.t;
  #[global] SpanEventOption_underlying :: (SpanEventOption) <u (SpanEventOptionⁱᵐᵖˡ);
  #[global] SpanEventOptionⁱᵐᵖˡ_underlying :: (SpanEventOptionⁱᵐᵖˡ) ↓u (SpanEventOptionⁱᵐᵖˡ);
}.

Module timestampOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End timestampOption.

Class timestampOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] timestampOption_type_repr  :: go.TypeReprUnderlying timestampOptionⁱᵐᵖˡ timestampOption.t;
  #[global] timestampOption_underlying :: (timestampOption) <u (timestampOptionⁱᵐᵖˡ);
  #[global] timestampOptionⁱᵐᵖˡ_underlying :: (timestampOptionⁱᵐᵖˡ) ↓u (timestampOptionⁱᵐᵖˡ);
}.

Module stackTraceOption.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End stackTraceOption.

Class stackTraceOption_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] stackTraceOption_type_repr  :: go.TypeReprUnderlying stackTraceOptionⁱᵐᵖˡ stackTraceOption.t;
  #[global] stackTraceOption_underlying :: (stackTraceOption) <u (stackTraceOptionⁱᵐᵖˡ);
  #[global] stackTraceOptionⁱᵐᵖˡ_underlying :: (stackTraceOptionⁱᵐᵖˡ) ↓u (stackTraceOptionⁱᵐᵖˡ);
}.

Module traceContextKeyType.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End traceContextKeyType.

Class traceContextKeyType_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] traceContextKeyType_type_repr  :: go.TypeReprUnderlying traceContextKeyTypeⁱᵐᵖˡ traceContextKeyType.t;
  #[global] traceContextKeyType_underlying :: (traceContextKeyType) <u (traceContextKeyTypeⁱᵐᵖˡ);
  #[global] traceContextKeyTypeⁱᵐᵖˡ_underlying :: (traceContextKeyTypeⁱᵐᵖˡ) ↓u (traceContextKeyTypeⁱᵐᵖˡ);
}.

Module nonRecordingSpan.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End nonRecordingSpan.

Class nonRecordingSpan_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] nonRecordingSpan_type_repr  :: go.TypeReprUnderlying nonRecordingSpanⁱᵐᵖˡ nonRecordingSpan.t;
  #[global] nonRecordingSpan_underlying :: (nonRecordingSpan) <u (nonRecordingSpanⁱᵐᵖˡ);
  #[global] nonRecordingSpanⁱᵐᵖˡ_underlying :: (nonRecordingSpanⁱᵐᵖˡ) ↓u (nonRecordingSpanⁱᵐᵖˡ);
}.

Module noopTracerProvider.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End noopTracerProvider.

Class noopTracerProvider_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] noopTracerProvider_type_repr  :: go.TypeReprUnderlying noopTracerProviderⁱᵐᵖˡ noopTracerProvider.t;
  #[global] noopTracerProvider_underlying :: (noopTracerProvider) <u (noopTracerProviderⁱᵐᵖˡ);
  #[global] noopTracerProviderⁱᵐᵖˡ_underlying :: (noopTracerProviderⁱᵐᵖˡ) ↓u (noopTracerProviderⁱᵐᵖˡ);
}.

Module noopTracer.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End noopTracer.

Class noopTracer_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] noopTracer_type_repr  :: go.TypeReprUnderlying noopTracerⁱᵐᵖˡ noopTracer.t;
  #[global] noopTracer_underlying :: (noopTracer) <u (noopTracerⁱᵐᵖˡ);
  #[global] noopTracerⁱᵐᵖˡ_underlying :: (noopTracerⁱᵐᵖˡ) ↓u (noopTracerⁱᵐᵖˡ);
}.

Module noopSpan.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End noopSpan.

Class noopSpan_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] noopSpan_type_repr  :: go.TypeReprUnderlying noopSpanⁱᵐᵖˡ noopSpan.t;
  #[global] noopSpan_underlying :: (noopSpan) <u (noopSpanⁱᵐᵖˡ);
  #[global] noopSpanⁱᵐᵖˡ_underlying :: (noopSpanⁱᵐᵖˡ) ↓u (noopSpanⁱᵐᵖˡ);
}.

Module TracerProvider.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End TracerProvider.

Class TracerProvider_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] TracerProvider_type_repr  :: go.TypeReprUnderlying TracerProviderⁱᵐᵖˡ TracerProvider.t;
  #[global] TracerProvider_underlying :: (TracerProvider) <u (TracerProviderⁱᵐᵖˡ);
  #[global] TracerProviderⁱᵐᵖˡ_underlying :: (TracerProviderⁱᵐᵖˡ) ↓u (TracerProviderⁱᵐᵖˡ);
}.

Module Span.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Span.

Class Span_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Span_type_repr  :: go.TypeReprUnderlying Spanⁱᵐᵖˡ Span.t;
  #[global] Span_underlying :: (Span) <u (Spanⁱᵐᵖˡ);
  #[global] Spanⁱᵐᵖˡ_underlying :: (Spanⁱᵐᵖˡ) ↓u (Spanⁱᵐᵖˡ);
}.

Module Link.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Link.

Class Link_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Link_type_repr  :: go.TypeReprUnderlying Linkⁱᵐᵖˡ Link.t;
  #[global] Link_underlying :: (Link) <u (Linkⁱᵐᵖˡ);
  #[global] Linkⁱᵐᵖˡ_underlying :: (Linkⁱᵐᵖˡ) ↓u (Linkⁱᵐᵖˡ);
}.

Module SpanKind.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanKind.

Class SpanKind_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanKind_type_repr  :: go.TypeReprUnderlying SpanKindⁱᵐᵖˡ SpanKind.t;
  #[global] SpanKind_underlying :: (SpanKind) <u (SpanKindⁱᵐᵖˡ);
  #[global] SpanKindⁱᵐᵖˡ_underlying :: (SpanKindⁱᵐᵖˡ) ↓u (SpanKindⁱᵐᵖˡ);
}.

Module errorConst.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End errorConst.

Class errorConst_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] errorConst_type_repr  :: go.TypeReprUnderlying errorConstⁱᵐᵖˡ errorConst.t;
  #[global] errorConst_underlying :: (errorConst) <u (errorConstⁱᵐᵖˡ);
  #[global] errorConstⁱᵐᵖˡ_underlying :: (errorConstⁱᵐᵖˡ) ↓u (errorConstⁱᵐᵖˡ);
}.

Module TraceID.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End TraceID.

Class TraceID_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] TraceID_type_repr  :: go.TypeReprUnderlying TraceIDⁱᵐᵖˡ TraceID.t;
  #[global] TraceID_underlying :: (TraceID) <u (TraceIDⁱᵐᵖˡ);
  #[global] TraceIDⁱᵐᵖˡ_underlying :: (TraceIDⁱᵐᵖˡ) ↓u (TraceIDⁱᵐᵖˡ);
}.

Module SpanID.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanID.

Class SpanID_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanID_type_repr  :: go.TypeReprUnderlying SpanIDⁱᵐᵖˡ SpanID.t;
  #[global] SpanID_underlying :: (SpanID) <u (SpanIDⁱᵐᵖˡ);
  #[global] SpanIDⁱᵐᵖˡ_underlying :: (SpanIDⁱᵐᵖˡ) ↓u (SpanIDⁱᵐᵖˡ);
}.

Module TraceFlags.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End TraceFlags.

Class TraceFlags_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] TraceFlags_type_repr  :: go.TypeReprUnderlying TraceFlagsⁱᵐᵖˡ TraceFlags.t;
  #[global] TraceFlags_underlying :: (TraceFlags) <u (TraceFlagsⁱᵐᵖˡ);
  #[global] TraceFlagsⁱᵐᵖˡ_underlying :: (TraceFlagsⁱᵐᵖˡ) ↓u (TraceFlagsⁱᵐᵖˡ);
}.

Module SpanContextConfig.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanContextConfig.

Class SpanContextConfig_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanContextConfig_type_repr  :: go.TypeReprUnderlying SpanContextConfigⁱᵐᵖˡ SpanContextConfig.t;
  #[global] SpanContextConfig_underlying :: (SpanContextConfig) <u (SpanContextConfigⁱᵐᵖˡ);
  #[global] SpanContextConfigⁱᵐᵖˡ_underlying :: (SpanContextConfigⁱᵐᵖˡ) ↓u (SpanContextConfigⁱᵐᵖˡ);
}.

Module SpanContext.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SpanContext.

Class SpanContext_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SpanContext_type_repr  :: go.TypeReprUnderlying SpanContextⁱᵐᵖˡ SpanContext.t;
  #[global] SpanContext_underlying :: (SpanContext) <u (SpanContextⁱᵐᵖˡ);
  #[global] SpanContextⁱᵐᵖˡ_underlying :: (SpanContextⁱᵐᵖˡ) ↓u (SpanContextⁱᵐᵖˡ);
}.

Module Tracer.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Tracer.

Class Tracer_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Tracer_type_repr  :: go.TypeReprUnderlying Tracerⁱᵐᵖˡ Tracer.t;
  #[global] Tracer_underlying :: (Tracer) <u (Tracerⁱᵐᵖˡ);
  #[global] Tracerⁱᵐᵖˡ_underlying :: (Tracerⁱᵐᵖˡ) ↓u (Tracerⁱᵐᵖˡ);
}.

Module member.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End member.

Class member_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] member_type_repr  :: go.TypeReprUnderlying memberⁱᵐᵖˡ member.t;
  #[global] member_underlying :: (member) <u (memberⁱᵐᵖˡ);
  #[global] memberⁱᵐᵖˡ_underlying :: (memberⁱᵐᵖˡ) ↓u (memberⁱᵐᵖˡ);
}.

Module TraceState.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End TraceState.

Class TraceState_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] TraceState_type_repr  :: go.TypeReprUnderlying TraceStateⁱᵐᵖˡ TraceState.t;
  #[global] TraceState_underlying :: (TraceState) <u (TraceStateⁱᵐᵖˡ);
  #[global] TraceStateⁱᵐᵖˡ_underlying :: (TraceStateⁱᵐᵖˡ) ↓u (TraceStateⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] autoTracerProvider_instance :: autoTracerProvider_Assumptions;
  #[global] autoTracer_instance :: autoTracer_Assumptions;
  #[global] autoSpan_instance :: autoSpan_Assumptions;
  #[global] spanLimits_instance :: spanLimits_Assumptions;
  #[global] TracerConfig_instance :: TracerConfig_Assumptions;
  #[global] TracerOption_instance :: TracerOption_Assumptions;
  #[global] tracerOptionFunc_instance :: tracerOptionFunc_Assumptions;
  #[global] SpanConfig_instance :: SpanConfig_Assumptions;
  #[global] SpanStartOption_instance :: SpanStartOption_Assumptions;
  #[global] spanOptionFunc_instance :: spanOptionFunc_Assumptions;
  #[global] SpanEndOption_instance :: SpanEndOption_Assumptions;
  #[global] EventConfig_instance :: EventConfig_Assumptions;
  #[global] EventOption_instance :: EventOption_Assumptions;
  #[global] SpanOption_instance :: SpanOption_Assumptions;
  #[global] SpanStartEventOption_instance :: SpanStartEventOption_Assumptions;
  #[global] SpanEndEventOption_instance :: SpanEndEventOption_Assumptions;
  #[global] attributeOption_instance :: attributeOption_Assumptions;
  #[global] SpanEventOption_instance :: SpanEventOption_Assumptions;
  #[global] timestampOption_instance :: timestampOption_Assumptions;
  #[global] stackTraceOption_instance :: stackTraceOption_Assumptions;
  #[global] traceContextKeyType_instance :: traceContextKeyType_Assumptions;
  #[global] nonRecordingSpan_instance :: nonRecordingSpan_Assumptions;
  #[global] noopTracerProvider_instance :: noopTracerProvider_Assumptions;
  #[global] noopTracer_instance :: noopTracer_Assumptions;
  #[global] noopSpan_instance :: noopSpan_Assumptions;
  #[global] TracerProvider_instance :: TracerProvider_Assumptions;
  #[global] Span_instance :: Span_Assumptions;
  #[global] Link_instance :: Link_Assumptions;
  #[global] SpanKind_instance :: SpanKind_Assumptions;
  #[global] errorConst_instance :: errorConst_Assumptions;
  #[global] TraceID_instance :: TraceID_Assumptions;
  #[global] SpanID_instance :: SpanID_Assumptions;
  #[global] TraceFlags_instance :: TraceFlags_Assumptions;
  #[global] SpanContextConfig_instance :: SpanContextConfig_Assumptions;
  #[global] SpanContext_instance :: SpanContext_Assumptions;
  #[global] Tracer_instance :: Tracer_Assumptions;
  #[global] member_instance :: member_Assumptions;
  #[global] TraceState_instance :: TraceState_Assumptions;
}.
End trace.
