(* autogenerated from github.com/goose-lang/goose/testdata/examples/interfacerecursion *)

From New.golang Require Import defn.
Definition interfacerecursion : go_string := "github.com/goose-lang/goose/testdata/examples/interfacerecursion".

Module interfacerecursion.

Section code.
Context `{ffi_syntax}.


Definition Aⁱᵐᵖˡ : go.type := go.InterfaceType [go.MethodElem #"Foo"%go (go.Signature [] #false [])].

Definition Bⁱᵐᵖˡ : go.type := go.InterfaceType [go.MethodElem #"Bar"%go (go.Signature [] #false [])].

Definition cⁱᵐᵖˡ : go.type := go.StructType [
].

Definition B : go.type := go.Named "github.com/goose-lang/goose/testdata/examples/interfacerecursion.B"%go [].

Definition c : go.type := go.Named "github.com/goose-lang/goose/testdata/examples/interfacerecursion.c"%go [].

(* go: x.go:14:13 *)
Definition c__Fooⁱᵐᵖˡ : val :=
  λ: "c" <>,
    exception_do (let: "c" := (go.AllocValue (go.PointerType c) "c") in
    let: "y" := (GoAlloc B #()) in
    let: "$r0" := (InterfaceMake (go.PointerType c) (![go.PointerType c] "c")) in
    do:  ("y" <-[B] "$r0");;;
    do:  ((MethodResolve B Bar #() (![B] "y")) #());;;
    return: #()).

Definition A : go.type := go.Named "github.com/goose-lang/goose/testdata/examples/interfacerecursion.A"%go [].

(* go: x.go:19:13 *)
Definition c__Barⁱᵐᵖˡ : val :=
  λ: "c" <>,
    exception_do (let: "c" := (go.AllocValue (go.PointerType c) "c") in
    let: "y" := (GoAlloc A #()) in
    let: "$r0" := (InterfaceMake (go.PointerType c) (![go.PointerType c] "c")) in
    do:  ("y" <-[A] "$r0");;;
    do:  ((MethodResolve A Foo #() (![A] "y")) #());;;
    return: #()).

Definition functions' : list (go_string * val) := [].

#[global] Instance info' : PkgInfo interfacerecursion.interfacerecursion :=
  {|
    pkg_imported_pkgs := [];
  |}.

Definition initialize' : val :=
  λ: <>,
    package.init interfacerecursion.interfacerecursion (λ: <>,
      exception_do (do:  #())
      ).

End code.
End interfacerecursion.
