(* autogenerated from github.com/goose-lang/goose/testdata/examples/interfacerecursion *)
From New.golang Require Import defn.
Module pkg_id.
Definition interfacerecursion : go_string := "github.com/goose-lang/goose/testdata/examples/interfacerecursion".

End pkg_id.
Export pkg_id.
Module interfacerecursion.

Definition A {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/goose-lang/goose/testdata/examples/interfacerecursion.A"%go [].

Definition B {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/goose-lang/goose/testdata/examples/interfacerecursion.B"%go [].

Definition c {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/goose-lang/goose/testdata/examples/interfacerecursion.c"%go [].

(* go: x.go:14:13 *)
Definition c__Fooⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "c" <>,
    exception_do (let: "c" := (GoAlloc (go.PointerType c) "c") in
    let: "y" := (GoAlloc B (GoZeroVal B #())) in
    let: "$r0" := (Convert (go.PointerType c) B (![go.PointerType c] "c")) in
    do:  ("y" <-[B] "$r0");;;
    do:  ((MethodResolve B "Bar"%go #() (![B] "y")) #());;;
    return: #()).

(* go: x.go:19:13 *)
Definition c__Barⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "c" <>,
    exception_do (let: "c" := (GoAlloc (go.PointerType c) "c") in
    let: "y" := (GoAlloc A (GoZeroVal A #())) in
    let: "$r0" := (Convert (go.PointerType c) A (![go.PointerType c] "c")) in
    do:  ("y" <-[A] "$r0");;;
    do:  ((MethodResolve A "Foo"%go #() (![A] "y")) #());;;
    return: #()).

#[global] Instance info' : PkgInfo pkg_id.interfacerecursion :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.interfacerecursion (λ: <>,
      exception_do (do:  #())
      ).

Module A.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Definition t : Type := interface.t.
End def.
End A.

Definition Aⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.InterfaceType [go.MethodElem "Foo"%go (go.Signature [] false [])].

Class A_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] A_type_repr  :: go.TypeRepr A A.t;
  #[global] A_underlying :: go.Underlying (A) (Aⁱᵐᵖˡ);
}.

Module B.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Definition t : Type := interface.t.
End def.
End B.

Definition Bⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.InterfaceType [go.MethodElem "Bar"%go (go.Signature [] false [])].

Class B_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] B_type_repr  :: go.TypeRepr B B.t;
  #[global] B_underlying :: go.Underlying (B) (Bⁱᵐᵖˡ);
}.

Module c.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.

End c.

Definition cⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType [
].

Class c_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] c_type_repr  :: go.TypeRepr c c.t;
  #[global] c_underlying :: go.Underlying (c) (cⁱᵐᵖˡ);
  #[global] c'ptr_Bar_unfold :: MethodUnfold (go.PointerType (c)) "Bar" (c__Barⁱᵐᵖˡ);
  #[global] c'ptr_Foo_unfold :: MethodUnfold (go.PointerType (c)) "Foo" (c__Fooⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] A_instance :: A_Assumptions;
  #[global] B_instance :: B_Assumptions;
  #[global] c_instance :: c_Assumptions;
}.
End interfacerecursion.
