(* autogenerated from go.etcd.io/etcd/cache/v3 *)
Require Export New.code.fmt.
Require Export New.code.sync.
Require Export New.code.go_etcd_io.etcd.api.v3.v3rpc.rpctypes.
Require Export New.code.k8s_io.utils.third_party.forked.golang.btree.
From New.golang Require Import defn.
Module pkg_id.
Definition cache : go_string := "go.etcd.io/etcd/cache/v3".

End pkg_id.
Export pkg_id.
Module cache.

Definition Cache {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.Cache"%go [].

#[global] Opaque Cache.

Definition Clock {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.Clock"%go [].

#[global] Opaque Clock.

Definition Timer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.Timer"%go [].

#[global] Opaque Timer.

Definition realClock {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.realClock"%go [].

#[global] Opaque realClock.

Definition realTimer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.realTimer"%go [].

#[global] Opaque realTimer.

Definition Config {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.Config"%go [].

#[global] Opaque Config.

Definition Option {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.Option"%go [].

#[global] Opaque Option.

Definition demux {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.demux"%go [].

#[global] Opaque demux.

Definition notifier {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.notifier"%go [].

#[global] Opaque notifier.

Definition Prefix {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.Prefix"%go [].

#[global] Opaque Prefix.

Definition progressNotifier {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.progressNotifier"%go [].

#[global] Opaque progressNotifier.

Definition progressRequestor {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.progressRequestor"%go [].

#[global] Opaque progressRequestor.

Definition conditionalProgressRequestor {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.conditionalProgressRequestor"%go [].

#[global] Opaque conditionalProgressRequestor.

Definition ready {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.ready"%go [].

#[global] Opaque ready.

Definition ringBuffer {ext : ffi_syntax} {go_gctx : GoGlobalContext} (T : go.type) : go.type := go.Named "go.etcd.io/etcd/cache/v3.ringBuffer"%go [T].

#[global] Opaque ringBuffer.

Definition entry {ext : ffi_syntax} {go_gctx : GoGlobalContext} (T : go.type) : go.type := go.Named "go.etcd.io/etcd/cache/v3.entry"%go [T].

#[global] Opaque entry.

Definition RevisionOf {ext : ffi_syntax} {go_gctx : GoGlobalContext} (T : go.type) : go.type := go.Named "go.etcd.io/etcd/cache/v3.RevisionOf"%go [T].

#[global] Opaque RevisionOf.

Definition IterFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} (T : go.type) : go.type := go.Named "go.etcd.io/etcd/cache/v3.IterFunc"%go [T].

#[global] Opaque IterFunc.

Definition snapshot {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.snapshot"%go [].

#[global] Opaque snapshot.

Definition store {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.store"%go [].

#[global] Opaque store.

Definition kvItem {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.kvItem"%go [].

#[global] Opaque kvItem.

Definition watcher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "go.etcd.io/etcd/cache/v3.watcher"%go [].

#[global] Opaque watcher.

Axiom Cacheⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Clockⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Timerⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom realClockⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom realTimerⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Configⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Optionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom demuxⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom notifierⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Prefixⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom progressNotifierⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom progressRequestorⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom conditionalProgressRequestorⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom readyⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ringBufferⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, ∀ (T : go.type), go.type.

Axiom entryⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, ∀ (T : go.type), go.type.

Axiom KeyPredicate : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom RevisionOfⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, ∀ (T : go.type), go.type.

Axiom IterFuncⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, ∀ (T : go.type), go.type.

Axiom kvItemⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom watcherⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom revisionPollInterval : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ErrUnsupportedRequest {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.ErrUnsupportedRequest"%go.

Axiom ErrUnsupportedRequest'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ErrKeyRangeInvalid {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.ErrKeyRangeInvalid"%go.

Axiom ErrKeyRangeInvalid'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ErrCacheTimeout {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.ErrCacheTimeout"%go.

Axiom ErrCacheTimeout'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ErrNotReady {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.ErrNotReady"%go.

Axiom ErrNotReady'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition New {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.New"%go.

Definition defaultConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.defaultConfig"%go.

Definition WithPerWatcherBufferSize {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.WithPerWatcherBufferSize"%go.

Definition WithHistoryWindowSize {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.WithHistoryWindowSize"%go.

Definition WithResyncInterval {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.WithResyncInterval"%go.

Definition WithInitialBackoff {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.WithInitialBackoff"%go.

Definition WithMaxBackoff {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.WithMaxBackoff"%go.

Definition WithGetTimeout {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.WithGetTimeout"%go.

Definition WithBTreeDegree {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.WithBTreeDegree"%go.

Definition WithProgressRequestInterval {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.WithProgressRequestInterval"%go.

Definition WithWaitTimeout {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.WithWaitTimeout"%go.

Definition NewDemux {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.NewDemux"%go.

Definition newDemux {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.newDemux"%go.

Definition newNotifier {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.newNotifier"%go.

Definition ExactKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.ExactKey"%go.

Definition FromKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.FromKey"%go.

Definition Range {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.Range"%go.

Definition KeyPredForRange {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.KeyPredForRange"%go.

Definition newConditionalProgressRequestor {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.newConditionalProgressRequestor"%go.

Definition newReady {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.newReady"%go.

Definition newRingBuffer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.newRingBuffer"%go.

Definition newClonedSnapshot {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.newClonedSnapshot"%go.

Definition isPrefixScan {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.isPrefixScan"%go.

Definition probeItemFromKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.probeItemFromKey"%go.

Definition newStore {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.newStore"%go.

Definition newKVItem {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.newKVItem"%go.

Definition kvItemLess {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.kvItemLess"%go.

Definition validateRevisions {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.validateRevisions"%go.

Definition newWatcher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "go.etcd.io/etcd/cache/v3.newWatcher"%go.

(* go: store.go:70:17 *)
Definition store__getSnapshotⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "s" "rev",
    with_defer: (let: "s" := (GoAlloc (go.PointerType store) "s") in
    let: "rev" := (GoAlloc go.int64 "rev") in
    do:  ((MethodResolve (go.PointerType sync.RWMutex) "RLock"%go (StructFieldRef store "mu"%go (![go.PointerType store] "s"))) #());;;
    do:  (let: "$f" := (MethodResolve (go.PointerType sync.RWMutex) "RUnlock"%go (StructFieldRef store "mu"%go (![go.PointerType store] "s"))) in
    "$defer" <-[deferType] (let: "$oldf" := (![deferType] "$defer") in
    (λ: <>,
      "$f" #();;
      "$oldf" #()
      )));;;
    (if: Convert go.untyped_bool go.bool ((![go.int64] (StructFieldRef snapshot "rev"%go (StructFieldRef store "latest"%go (![go.PointerType store] "s")))) =⟨go.int64⟩ #(W64 0))
    then return: (Convert go.untyped_nil (go.PointerType snapshot) UntypedNil, #(W64 0), ![go.error] (GlobalVarAddr ErrNotReady #()))
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int64] "rev") <⟨go.int64⟩ #(W64 0))
    then
      return: (Convert go.untyped_nil (go.PointerType snapshot) UntypedNil, #(W64 0), let: "$a0" := #"invalid revision: %d"%go in
       let: "$a1" := ((let: "$sl0" := (Convert go.int64 go.any (![go.int64] "rev")) in
       CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
       (FuncResolve fmt.Errorf [] #()) "$a0" "$a1")
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int64] "rev") =⟨go.int64⟩ #(W64 0))
    then
      let: "$r0" := (![go.int64] (StructFieldRef snapshot "rev"%go (StructFieldRef store "latest"%go (![go.PointerType store] "s")))) in
      do:  ("rev" <-[go.int64] "$r0")
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int64] "rev") >⟨go.int64⟩ (![go.int64] (StructFieldRef snapshot "rev"%go (StructFieldRef store "latest"%go (![go.PointerType store] "s")))))
    then return: (Convert go.untyped_nil (go.PointerType snapshot) UntypedNil, #(W64 0), ![go.error] (GlobalVarAddr rpctypes.ErrFutureRev #()))
    else do:  #());;;
    let: "oldestRev" := (GoAlloc go.int64 (GoZeroVal go.int64 #())) in
    let: "$r0" := ((MethodResolve (go.PointerType (ringBuffer (go.PointerType snapshot))) "PeekOldest"%go (StructFieldRef store "history"%go (![go.PointerType store] "s"))) #()) in
    do:  ("oldestRev" <-[go.int64] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.int64] "rev") <⟨go.int64⟩ (![go.int64] "oldestRev"))
    then return: (Convert go.untyped_nil (go.PointerType snapshot) UntypedNil, #(W64 0), ![go.error] (GlobalVarAddr rpctypes.ErrCompacted #()))
    else do:  #());;;
    let: "targetSnapshot" := (GoAlloc (go.PointerType snapshot) (GoZeroVal (go.PointerType snapshot) #())) in
    do:  (let: "$a0" := (![go.int64] "rev") in
    let: "$a1" := (λ: "rev" "snap",
      exception_do (let: "snap" := (GoAlloc (go.PointerType snapshot) "snap") in
      let: "rev" := (GoAlloc go.int64 "rev") in
      let: "$r0" := (![go.PointerType snapshot] "snap") in
      do:  ("targetSnapshot" <-[go.PointerType snapshot] "$r0");;;
      return: (#false))
      ) in
    (MethodResolve (go.PointerType (ringBuffer (go.PointerType snapshot))) "DescendLessOrEqual"%go (StructFieldRef store "history"%go (![go.PointerType store] "s"))) "$a0" "$a1");;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType snapshot] "targetSnapshot") =⟨go.PointerType snapshot⟩ (Convert go.untyped_nil (go.PointerType snapshot) UntypedNil))
    then
      let: "$r0" := (let: "$a0" := (![go.int64] "rev") in
      let: "$a1" := (![go.PointerType (btree.BTree (go.PointerType kvItem))] (StructFieldRef snapshot "tree"%go (StructFieldRef store "latest"%go (![go.PointerType store] "s")))) in
      (FuncResolve newClonedSnapshot [] #()) "$a0" "$a1") in
      do:  ("targetSnapshot" <-[go.PointerType snapshot] "$r0")
    else do:  #());;;
    return: (![go.PointerType snapshot] "targetSnapshot", ![go.int64] (StructFieldRef snapshot "rev"%go (StructFieldRef store "latest"%go (![go.PointerType store] "s"))), Convert go.untyped_nil go.error UntypedNil)).

#[global] Instance info' : PkgInfo pkg_id.cache :=
{|
  pkg_imported_pkgs := [code.fmt.pkg_id.fmt; code.sync.pkg_id.sync; code.go_etcd_io.etcd.api.v3.v3rpc.rpctypes.pkg_id.rpctypes; code.k8s_io.utils.third_party.forked.golang.btree.pkg_id.btree]
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.cache (λ: <>,
      exception_do (do:  (btree.initialize' #());;;
      do:  (rpctypes.initialize' #());;;
      do:  (sync.initialize' #());;;
      do:  (fmt.initialize' #());;;
      do:  (ErrUnsupportedRequest'init #());;;
      do:  (ErrKeyRangeInvalid'init #());;;
      do:  (ErrCacheTimeout'init #());;;
      do:  (ErrNotReady'init #()))
      ).

Module Cache.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Cache.

Class Cache_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Cache_type_repr  :: go.TypeReprUnderlying Cacheⁱᵐᵖˡ Cache.t;
  #[global] Cache_underlying :: (Cache) <u (Cacheⁱᵐᵖˡ);
  #[global] Cacheⁱᵐᵖˡ_underlying :: (Cacheⁱᵐᵖˡ) ↓u (Cacheⁱᵐᵖˡ);
}.

Module Clock.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Clock.

Class Clock_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Clock_type_repr  :: go.TypeReprUnderlying Clockⁱᵐᵖˡ Clock.t;
  #[global] Clock_underlying :: (Clock) <u (Clockⁱᵐᵖˡ);
  #[global] Clockⁱᵐᵖˡ_underlying :: (Clockⁱᵐᵖˡ) ↓u (Clockⁱᵐᵖˡ);
}.

Module Timer.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Timer.

Class Timer_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Timer_type_repr  :: go.TypeReprUnderlying Timerⁱᵐᵖˡ Timer.t;
  #[global] Timer_underlying :: (Timer) <u (Timerⁱᵐᵖˡ);
  #[global] Timerⁱᵐᵖˡ_underlying :: (Timerⁱᵐᵖˡ) ↓u (Timerⁱᵐᵖˡ);
}.

Module realClock.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End realClock.

Class realClock_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] realClock_type_repr  :: go.TypeReprUnderlying realClockⁱᵐᵖˡ realClock.t;
  #[global] realClock_underlying :: (realClock) <u (realClockⁱᵐᵖˡ);
  #[global] realClockⁱᵐᵖˡ_underlying :: (realClockⁱᵐᵖˡ) ↓u (realClockⁱᵐᵖˡ);
}.

Module realTimer.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End realTimer.

Class realTimer_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] realTimer_type_repr  :: go.TypeReprUnderlying realTimerⁱᵐᵖˡ realTimer.t;
  #[global] realTimer_underlying :: (realTimer) <u (realTimerⁱᵐᵖˡ);
  #[global] realTimerⁱᵐᵖˡ_underlying :: (realTimerⁱᵐᵖˡ) ↓u (realTimerⁱᵐᵖˡ);
}.

Module Config.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Config.

Class Config_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Config_type_repr  :: go.TypeReprUnderlying Configⁱᵐᵖˡ Config.t;
  #[global] Config_underlying :: (Config) <u (Configⁱᵐᵖˡ);
  #[global] Configⁱᵐᵖˡ_underlying :: (Configⁱᵐᵖˡ) ↓u (Configⁱᵐᵖˡ);
}.

Module Option.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Option.

Class Option_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Option_type_repr  :: go.TypeReprUnderlying Optionⁱᵐᵖˡ Option.t;
  #[global] Option_underlying :: (Option) <u (Optionⁱᵐᵖˡ);
  #[global] Optionⁱᵐᵖˡ_underlying :: (Optionⁱᵐᵖˡ) ↓u (Optionⁱᵐᵖˡ);
}.

Module demux.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End demux.

Class demux_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] demux_type_repr  :: go.TypeReprUnderlying demuxⁱᵐᵖˡ demux.t;
  #[global] demux_underlying :: (demux) <u (demuxⁱᵐᵖˡ);
  #[global] demuxⁱᵐᵖˡ_underlying :: (demuxⁱᵐᵖˡ) ↓u (demuxⁱᵐᵖˡ);
}.

Module notifier.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End notifier.

Class notifier_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] notifier_type_repr  :: go.TypeReprUnderlying notifierⁱᵐᵖˡ notifier.t;
  #[global] notifier_underlying :: (notifier) <u (notifierⁱᵐᵖˡ);
  #[global] notifierⁱᵐᵖˡ_underlying :: (notifierⁱᵐᵖˡ) ↓u (notifierⁱᵐᵖˡ);
}.

Module Prefix.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Prefix.

Class Prefix_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Prefix_type_repr  :: go.TypeReprUnderlying Prefixⁱᵐᵖˡ Prefix.t;
  #[global] Prefix_underlying :: (Prefix) <u (Prefixⁱᵐᵖˡ);
  #[global] Prefixⁱᵐᵖˡ_underlying :: (Prefixⁱᵐᵖˡ) ↓u (Prefixⁱᵐᵖˡ);
}.

Module progressNotifier.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End progressNotifier.

Class progressNotifier_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] progressNotifier_type_repr  :: go.TypeReprUnderlying progressNotifierⁱᵐᵖˡ progressNotifier.t;
  #[global] progressNotifier_underlying :: (progressNotifier) <u (progressNotifierⁱᵐᵖˡ);
  #[global] progressNotifierⁱᵐᵖˡ_underlying :: (progressNotifierⁱᵐᵖˡ) ↓u (progressNotifierⁱᵐᵖˡ);
}.

Module progressRequestor.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End progressRequestor.

Class progressRequestor_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] progressRequestor_type_repr  :: go.TypeReprUnderlying progressRequestorⁱᵐᵖˡ progressRequestor.t;
  #[global] progressRequestor_underlying :: (progressRequestor) <u (progressRequestorⁱᵐᵖˡ);
  #[global] progressRequestorⁱᵐᵖˡ_underlying :: (progressRequestorⁱᵐᵖˡ) ↓u (progressRequestorⁱᵐᵖˡ);
}.

Module conditionalProgressRequestor.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End conditionalProgressRequestor.

Class conditionalProgressRequestor_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] conditionalProgressRequestor_type_repr  :: go.TypeReprUnderlying conditionalProgressRequestorⁱᵐᵖˡ conditionalProgressRequestor.t;
  #[global] conditionalProgressRequestor_underlying :: (conditionalProgressRequestor) <u (conditionalProgressRequestorⁱᵐᵖˡ);
  #[global] conditionalProgressRequestorⁱᵐᵖˡ_underlying :: (conditionalProgressRequestorⁱᵐᵖˡ) ↓u (conditionalProgressRequestorⁱᵐᵖˡ);
}.

Module ready.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ready.

Class ready_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ready_type_repr  :: go.TypeReprUnderlying readyⁱᵐᵖˡ ready.t;
  #[global] ready_underlying :: (ready) <u (readyⁱᵐᵖˡ);
  #[global] readyⁱᵐᵖˡ_underlying :: (readyⁱᵐᵖˡ) ↓u (readyⁱᵐᵖˡ);
}.

Module ringBuffer.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : ∀ (T : Type), Type.
Axiom zero_val : ∀ `{!ZeroVal T}, ZeroVal (t T).
#[global] Existing Instance zero_val.
End def.
End ringBuffer.

Class ringBuffer_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ringBuffer_type_repr T T' `{!ZeroVal T'} `{!TypeRepr T T'} :: go.TypeReprUnderlying (ringBufferⁱᵐᵖˡ T) (ringBuffer.t T');
  #[global] ringBuffer_underlying T :: (ringBuffer T) <u (ringBufferⁱᵐᵖˡ T);
  #[global] ringBufferⁱᵐᵖˡ_underlying T :: (ringBufferⁱᵐᵖˡ T) ↓u (ringBufferⁱᵐᵖˡ T);
}.

Module entry.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : ∀ (T : Type), Type.
Axiom zero_val : ∀ `{!ZeroVal T}, ZeroVal (t T).
#[global] Existing Instance zero_val.
End def.
End entry.

Class entry_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] entry_type_repr T T' `{!ZeroVal T'} `{!TypeRepr T T'} :: go.TypeReprUnderlying (entryⁱᵐᵖˡ T) (entry.t T');
  #[global] entry_underlying T :: (entry T) <u (entryⁱᵐᵖˡ T);
  #[global] entryⁱᵐᵖˡ_underlying T :: (entryⁱᵐᵖˡ T) ↓u (entryⁱᵐᵖˡ T);
}.

Module RevisionOf.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : ∀ (T : Type), Type.
Axiom zero_val : ∀ `{!ZeroVal T}, ZeroVal (t T).
#[global] Existing Instance zero_val.
End def.
End RevisionOf.

Class RevisionOf_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] RevisionOf_type_repr T T' `{!ZeroVal T'} `{!TypeRepr T T'} :: go.TypeReprUnderlying (RevisionOfⁱᵐᵖˡ T) (RevisionOf.t T');
  #[global] RevisionOf_underlying T :: (RevisionOf T) <u (RevisionOfⁱᵐᵖˡ T);
  #[global] RevisionOfⁱᵐᵖˡ_underlying T :: (RevisionOfⁱᵐᵖˡ T) ↓u (RevisionOfⁱᵐᵖˡ T);
}.

Module IterFunc.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : ∀ (T : Type), Type.
Axiom zero_val : ∀ `{!ZeroVal T}, ZeroVal (t T).
#[global] Existing Instance zero_val.
End def.
End IterFunc.

Class IterFunc_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] IterFunc_type_repr T T' `{!ZeroVal T'} `{!TypeRepr T T'} :: go.TypeReprUnderlying (IterFuncⁱᵐᵖˡ T) (IterFunc.t T');
  #[global] IterFunc_underlying T :: (IterFunc T) <u (IterFuncⁱᵐᵖˡ T);
  #[global] IterFuncⁱᵐᵖˡ_underlying T :: (IterFuncⁱᵐᵖˡ T) ↓u (IterFuncⁱᵐᵖˡ T);
}.

Module snapshot.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  rev' : w64;
  tree' : loc;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End snapshot.

Definition snapshot'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "rev"%go go.int64);
  (go.FieldDecl "tree"%go (go.PointerType (btree.BTree (go.PointerType kvItem))))
].
Program Definition snapshot'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (snapshot'fds_unsealed).
Global Instance equals_unfold_snapshot {ext : ffi_syntax} {go_gctx : GoGlobalContext} : snapshot'fds =→ snapshot'fds_unsealed.
Proof. rewrite /snapshot'fds seal_eq //. Qed.

Definition snapshotⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (snapshot'fds).

Class snapshot_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] snapshot_type_repr  :: go.TypeReprUnderlying snapshotⁱᵐᵖˡ snapshot.t;
  #[global] snapshot_underlying :: (snapshot) <u (snapshotⁱᵐᵖˡ);
  #[global] snapshot_get_rev (x : snapshot.t) :: ⟦StructFieldGet (snapshotⁱᵐᵖˡ) "rev", #x⟧ ⤳[under] #x.(snapshot.rev');
  #[global] snapshot_set_rev (x : snapshot.t) y :: ⟦StructFieldSet (snapshotⁱᵐᵖˡ) "rev", (#x, #y)⟧ ⤳[under] #(x <|snapshot.rev' := y|>);
  #[global] snapshot_get_tree (x : snapshot.t) :: ⟦StructFieldGet (snapshotⁱᵐᵖˡ) "tree", #x⟧ ⤳[under] #x.(snapshot.tree');
  #[global] snapshot_set_tree (x : snapshot.t) y :: ⟦StructFieldSet (snapshotⁱᵐᵖˡ) "tree", (#x, #y)⟧ ⤳[under] #(x <|snapshot.tree' := y|>);
}.

Module store.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  mu' : sync.RWMutex.t;
  degree' : w64;
  latest' : cache.snapshot.t;
  history' : (cache.ringBuffer.t loc);
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End store.

Definition store'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "mu"%go sync.RWMutex);
  (go.FieldDecl "degree"%go go.int);
  (go.FieldDecl "latest"%go snapshot);
  (go.FieldDecl "history"%go (ringBuffer (go.PointerType snapshot)))
].
Program Definition store'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (store'fds_unsealed).
Global Instance equals_unfold_store {ext : ffi_syntax} {go_gctx : GoGlobalContext} : store'fds =→ store'fds_unsealed.
Proof. rewrite /store'fds seal_eq //. Qed.

Definition storeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (store'fds).

Class store_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] store_type_repr  :: go.TypeReprUnderlying storeⁱᵐᵖˡ store.t;
  #[global] store_underlying :: (store) <u (storeⁱᵐᵖˡ);
  #[global] store_get_mu (x : store.t) :: ⟦StructFieldGet (storeⁱᵐᵖˡ) "mu", #x⟧ ⤳[under] #x.(store.mu');
  #[global] store_set_mu (x : store.t) y :: ⟦StructFieldSet (storeⁱᵐᵖˡ) "mu", (#x, #y)⟧ ⤳[under] #(x <|store.mu' := y|>);
  #[global] store_get_degree (x : store.t) :: ⟦StructFieldGet (storeⁱᵐᵖˡ) "degree", #x⟧ ⤳[under] #x.(store.degree');
  #[global] store_set_degree (x : store.t) y :: ⟦StructFieldSet (storeⁱᵐᵖˡ) "degree", (#x, #y)⟧ ⤳[under] #(x <|store.degree' := y|>);
  #[global] store_get_latest (x : store.t) :: ⟦StructFieldGet (storeⁱᵐᵖˡ) "latest", #x⟧ ⤳[under] #x.(store.latest');
  #[global] store_set_latest (x : store.t) y :: ⟦StructFieldSet (storeⁱᵐᵖˡ) "latest", (#x, #y)⟧ ⤳[under] #(x <|store.latest' := y|>);
  #[global] store_get_history (x : store.t) :: ⟦StructFieldGet (storeⁱᵐᵖˡ) "history", #x⟧ ⤳[under] #x.(store.history');
  #[global] store_set_history (x : store.t) y :: ⟦StructFieldSet (storeⁱᵐᵖˡ) "history", (#x, #y)⟧ ⤳[under] #(x <|store.history' := y|>);
  #[global] store'ptr_getSnapshot_unfold :: MethodUnfold (go.PointerType (store)) "getSnapshot" (store__getSnapshotⁱᵐᵖˡ);
}.

Module kvItem.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End kvItem.

Class kvItem_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] kvItem_type_repr  :: go.TypeReprUnderlying kvItemⁱᵐᵖˡ kvItem.t;
  #[global] kvItem_underlying :: (kvItem) <u (kvItemⁱᵐᵖˡ);
  #[global] kvItemⁱᵐᵖˡ_underlying :: (kvItemⁱᵐᵖˡ) ↓u (kvItemⁱᵐᵖˡ);
}.

Module watcher.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End watcher.

Class watcher_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] watcher_type_repr  :: go.TypeReprUnderlying watcherⁱᵐᵖˡ watcher.t;
  #[global] watcher_underlying :: (watcher) <u (watcherⁱᵐᵖˡ);
  #[global] watcherⁱᵐᵖˡ_underlying :: (watcherⁱᵐᵖˡ) ↓u (watcherⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Cache_instance :: Cache_Assumptions;
  #[global] Clock_instance :: Clock_Assumptions;
  #[global] Timer_instance :: Timer_Assumptions;
  #[global] realClock_instance :: realClock_Assumptions;
  #[global] realTimer_instance :: realTimer_Assumptions;
  #[global] Config_instance :: Config_Assumptions;
  #[global] Option_instance :: Option_Assumptions;
  #[global] demux_instance :: demux_Assumptions;
  #[global] notifier_instance :: notifier_Assumptions;
  #[global] Prefix_instance :: Prefix_Assumptions;
  #[global] progressNotifier_instance :: progressNotifier_Assumptions;
  #[global] progressRequestor_instance :: progressRequestor_Assumptions;
  #[global] conditionalProgressRequestor_instance :: conditionalProgressRequestor_Assumptions;
  #[global] ready_instance :: ready_Assumptions;
  #[global] ringBuffer_instance :: ringBuffer_Assumptions;
  #[global] entry_instance :: entry_Assumptions;
  #[global] RevisionOf_instance :: RevisionOf_Assumptions;
  #[global] IterFunc_instance :: IterFunc_Assumptions;
  #[global] snapshot_instance :: snapshot_Assumptions;
  #[global] store_instance :: store_Assumptions;
  #[global] kvItem_instance :: kvItem_Assumptions;
  #[global] watcher_instance :: watcher_Assumptions;
  #[global] import_fmt_Assumption :: fmt.Assumptions;
  #[global] import_sync_Assumption :: sync.Assumptions;
  #[global] import_rpctypes_Assumption :: rpctypes.Assumptions;
  #[global] import_btree_Assumption :: btree.Assumptions;
}.
End cache.
