(* autogenerated from github.com/goose-lang/goose/testdata/examples/comments *)
From New.golang Require Import defn.
Module pkg_id.
Definition comments : go_string := "github.com/goose-lang/goose/testdata/examples/comments".

End pkg_id.
Export pkg_id.
Module comments.

Definition Foo {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/goose-lang/goose/testdata/examples/comments.Foo"%go [].

Definition ONE {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 1).

Definition TWO {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 2).

#[global] Instance info' : PkgInfo pkg_id.comments :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.comments (λ: <>,
      exception_do (do:  #())
      ).

Module Foo.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  a' : bool;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.

End Foo.

Definition Fooⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType [
  (go.FieldDecl "a"%go go.bool)
].

Class Foo_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Foo_type_repr  :: go.TypeRepr Foo Foo.t;
  #[global] Foo_underlying :: go.Underlying (Foo) (Fooⁱᵐᵖˡ);
  #[global] Foo_get_a (x : Foo.t) :: go.IsGoStepPureDet (StructFieldGet (Foo) "a") #x #x.(Foo.a');
  #[global] Foo_set_a (x : Foo.t) y :: go.IsGoStepPureDet (StructFieldSet (Foo) "a") (#x, #y) #(x <|Foo.a' := y|>);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Foo_instance :: Foo_Assumptions;
}.
End comments.
