(* autogenerated from github.com/goose-lang/goose/testdata/examples/import *)
Require Export New.code.sync.atomic.

From New.golang Require Import defn.
Definition example : go_string := "github.com/goose-lang/goose/testdata/examples/import".

Module example.

Section code.
Context `{ffi_syntax}.


Definition functions' : list (go_string * val) := [].

#[global] Instance info' : PkgInfo import.example :=
  {|
    pkg_imported_pkgs := [code.sync.atomic.atomic];
  |}.

Definition initialize' : val :=
  λ: <>,
    package.init import.example (λ: <>,
      exception_do (do:  (atomic.initialize' #()))
      ).

End code.
End example.
