(* autogenerated from github.com/goose-lang/goose/testdata/examples/mapliteral *)
From New.golang Require Import defn.
Module pkg_id.
Definition example : go_string := "github.com/goose-lang/goose/testdata/examples/mapliteral".

End pkg_id.
Export pkg_id.
Module example.

Definition mapliteral {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/goose-lang/goose/testdata/examples/mapliteral.mapliteral"%go.

(* go: mapliteral.go:3:6 *)
Definition mapliteralⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (CompositeLiteral (go.MapType go.uint64 go.uint64) (LiteralValue [KeyedElement (Some (KeyExpression #(W64 1))) (ElementExpression #(W64 2))]))).

#[global] Instance info' : PkgInfo pkg_id.example :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.example (λ: <>,
      exception_do (do:  #())
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] mapliteral_unfold :: FuncUnfold mapliteral [] (mapliteralⁱᵐᵖˡ);
}.
End example.
