(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.fmt.
Require Export New.generatedproof.go_etcd_io.etcd.api.v3.v3rpc.rpctypes.
Require Export New.generatedproof.k8s_io.utils.third_party.forked.golang.btree.
Require Export New.generatedproof.sync.
Require Export New.golang.theory.
Require Export New.code.go_etcd_io.etcd.cache.v3.

Set Default Proof Using "Type".

Module cache.
Module Cache.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Cache_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.Cache.t). Admitted.

#[global] Instance Cache_into_val_typed
   :
  IntoValTypedUnderlying (cache.Cache.t) (cache.Cacheⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Cache.

Module Clock.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Clock_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.Clock.t). Admitted.

#[global] Instance Clock_into_val_typed
   :
  IntoValTypedUnderlying (cache.Clock.t) (cache.Clockⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Clock.

Module Timer.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Timer_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.Timer.t). Admitted.

#[global] Instance Timer_into_val_typed
   :
  IntoValTypedUnderlying (cache.Timer.t) (cache.Timerⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Timer.

Module realClock.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance realClock_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.realClock.t). Admitted.

#[global] Instance realClock_into_val_typed
   :
  IntoValTypedUnderlying (cache.realClock.t) (cache.realClockⁱᵐᵖˡ).
Proof. Admitted.

End def.
End realClock.

Module realTimer.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance realTimer_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.realTimer.t). Admitted.

#[global] Instance realTimer_into_val_typed
   :
  IntoValTypedUnderlying (cache.realTimer.t) (cache.realTimerⁱᵐᵖˡ).
Proof. Admitted.

End def.
End realTimer.

Module Config.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Config_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.Config.t). Admitted.

#[global] Instance Config_into_val_typed
   :
  IntoValTypedUnderlying (cache.Config.t) (cache.Configⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Config.

Module Option.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Option_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.Option.t). Admitted.

#[global] Instance Option_into_val_typed
   :
  IntoValTypedUnderlying (cache.Option.t) (cache.Optionⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Option.

Module demux.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance demux_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.demux.t). Admitted.

#[global] Instance demux_into_val_typed
   :
  IntoValTypedUnderlying (cache.demux.t) (cache.demuxⁱᵐᵖˡ).
Proof. Admitted.

End def.
End demux.

Module notifier.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance notifier_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.notifier.t). Admitted.

#[global] Instance notifier_into_val_typed
   :
  IntoValTypedUnderlying (cache.notifier.t) (cache.notifierⁱᵐᵖˡ).
Proof. Admitted.

End def.
End notifier.

Module Prefix.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Prefix_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.Prefix.t). Admitted.

#[global] Instance Prefix_into_val_typed
   :
  IntoValTypedUnderlying (cache.Prefix.t) (cache.Prefixⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Prefix.

Module progressNotifier.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance progressNotifier_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.progressNotifier.t). Admitted.

#[global] Instance progressNotifier_into_val_typed
   :
  IntoValTypedUnderlying (cache.progressNotifier.t) (cache.progressNotifierⁱᵐᵖˡ).
Proof. Admitted.

End def.
End progressNotifier.

Module progressRequestor.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance progressRequestor_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.progressRequestor.t). Admitted.

#[global] Instance progressRequestor_into_val_typed
   :
  IntoValTypedUnderlying (cache.progressRequestor.t) (cache.progressRequestorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End progressRequestor.

Module conditionalProgressRequestor.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance conditionalProgressRequestor_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.conditionalProgressRequestor.t). Admitted.

#[global] Instance conditionalProgressRequestor_into_val_typed
   :
  IntoValTypedUnderlying (cache.conditionalProgressRequestor.t) (cache.conditionalProgressRequestorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End conditionalProgressRequestor.

Module ready.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ready_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.ready.t). Admitted.

#[global] Instance ready_into_val_typed
   :
  IntoValTypedUnderlying (cache.ready.t) (cache.readyⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ready.

Module ringBuffer.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ringBuffer_typed_pointsto `{!TypedPointsto (Σ:=Σ) T'}  :
  TypedPointsto (Σ:=Σ) (cache.ringBuffer.t T'). Admitted.

#[global] Instance ringBuffer_into_val_typed
  `{!ZeroVal T'} `{!TypedPointsto (Σ:=Σ) T'} `{!IntoValTyped T' T}  :
  IntoValTypedUnderlying (cache.ringBuffer.t T') (cache.ringBufferⁱᵐᵖˡ T).
Proof. Admitted.

End def.
End ringBuffer.

Module entry.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance entry_typed_pointsto `{!TypedPointsto (Σ:=Σ) T'}  :
  TypedPointsto (Σ:=Σ) (cache.entry.t T'). Admitted.

#[global] Instance entry_into_val_typed
  `{!ZeroVal T'} `{!TypedPointsto (Σ:=Σ) T'} `{!IntoValTyped T' T}  :
  IntoValTypedUnderlying (cache.entry.t T') (cache.entryⁱᵐᵖˡ T).
Proof. Admitted.

End def.
End entry.

Module RevisionOf.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance RevisionOf_typed_pointsto `{!TypedPointsto (Σ:=Σ) T'}  :
  TypedPointsto (Σ:=Σ) (cache.RevisionOf.t T'). Admitted.

#[global] Instance RevisionOf_into_val_typed
  `{!ZeroVal T'} `{!TypedPointsto (Σ:=Σ) T'} `{!IntoValTyped T' T}  :
  IntoValTypedUnderlying (cache.RevisionOf.t T') (cache.RevisionOfⁱᵐᵖˡ T).
Proof. Admitted.

End def.
End RevisionOf.

Module IterFunc.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance IterFunc_typed_pointsto `{!TypedPointsto (Σ:=Σ) T'}  :
  TypedPointsto (Σ:=Σ) (cache.IterFunc.t T'). Admitted.

#[global] Instance IterFunc_into_val_typed
  `{!ZeroVal T'} `{!TypedPointsto (Σ:=Σ) T'} `{!IntoValTyped T' T}  :
  IntoValTypedUnderlying (cache.IterFunc.t T') (cache.IterFuncⁱᵐᵖˡ T).
Proof. Admitted.

End def.
End IterFunc.

Module snapshot.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance snapshot_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.snapshot.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "rev" ∷ l.[(cache.snapshot.t), "rev"] ↦{dq} v.(cache.snapshot.rev') ∗
      "tree" ∷ l.[(cache.snapshot.t), "tree"] ↦{dq} v.(cache.snapshot.tree') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance snapshot_into_val_typed
   :
  IntoValTypedUnderlying (cache.snapshot.t) (cache.snapshotⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance snapshot_access_load_rev l (v : (cache.snapshot.t)) dq :
  AccessStrict
    (l.[(cache.snapshot.t), "rev"] ↦{dq} (v.(cache.snapshot.rev')))
    (l.[(cache.snapshot.t), "rev"] ↦{dq} (v.(cache.snapshot.rev')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance snapshot_access_store_rev l (v : (cache.snapshot.t)) rev' :
  AccessStrict
    (l.[(cache.snapshot.t), "rev"] ↦ (v.(cache.snapshot.rev')))
    (l.[(cache.snapshot.t), "rev"] ↦ rev')
    (l ↦ v) (l ↦ (v <|(cache.snapshot.rev') := rev'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance snapshot_access_load_tree l (v : (cache.snapshot.t)) dq :
  AccessStrict
    (l.[(cache.snapshot.t), "tree"] ↦{dq} (v.(cache.snapshot.tree')))
    (l.[(cache.snapshot.t), "tree"] ↦{dq} (v.(cache.snapshot.tree')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance snapshot_access_store_tree l (v : (cache.snapshot.t)) tree' :
  AccessStrict
    (l.[(cache.snapshot.t), "tree"] ↦ (v.(cache.snapshot.tree')))
    (l.[(cache.snapshot.t), "tree"] ↦ tree')
    (l ↦ v) (l ↦ (v <|(cache.snapshot.tree') := tree'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End snapshot.

Module store.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance store_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.store.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "mu" ∷ l.[(cache.store.t), "mu"] ↦{dq} v.(cache.store.mu') ∗
      "degree" ∷ l.[(cache.store.t), "degree"] ↦{dq} v.(cache.store.degree') ∗
      "latest" ∷ l.[(cache.store.t), "latest"] ↦{dq} v.(cache.store.latest') ∗
      "history" ∷ l.[(cache.store.t), "history"] ↦{dq} v.(cache.store.history') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance store_into_val_typed
   :
  IntoValTypedUnderlying (cache.store.t) (cache.storeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance store_access_load_mu l (v : (cache.store.t)) dq :
  AccessStrict
    (l.[(cache.store.t), "mu"] ↦{dq} (v.(cache.store.mu')))
    (l.[(cache.store.t), "mu"] ↦{dq} (v.(cache.store.mu')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance store_access_store_mu l (v : (cache.store.t)) mu' :
  AccessStrict
    (l.[(cache.store.t), "mu"] ↦ (v.(cache.store.mu')))
    (l.[(cache.store.t), "mu"] ↦ mu')
    (l ↦ v) (l ↦ (v <|(cache.store.mu') := mu'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance store_access_load_degree l (v : (cache.store.t)) dq :
  AccessStrict
    (l.[(cache.store.t), "degree"] ↦{dq} (v.(cache.store.degree')))
    (l.[(cache.store.t), "degree"] ↦{dq} (v.(cache.store.degree')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance store_access_store_degree l (v : (cache.store.t)) degree' :
  AccessStrict
    (l.[(cache.store.t), "degree"] ↦ (v.(cache.store.degree')))
    (l.[(cache.store.t), "degree"] ↦ degree')
    (l ↦ v) (l ↦ (v <|(cache.store.degree') := degree'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance store_access_load_latest l (v : (cache.store.t)) dq :
  AccessStrict
    (l.[(cache.store.t), "latest"] ↦{dq} (v.(cache.store.latest')))
    (l.[(cache.store.t), "latest"] ↦{dq} (v.(cache.store.latest')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance store_access_store_latest l (v : (cache.store.t)) latest' :
  AccessStrict
    (l.[(cache.store.t), "latest"] ↦ (v.(cache.store.latest')))
    (l.[(cache.store.t), "latest"] ↦ latest')
    (l ↦ v) (l ↦ (v <|(cache.store.latest') := latest'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance store_access_load_history l (v : (cache.store.t)) dq :
  AccessStrict
    (l.[(cache.store.t), "history"] ↦{dq} (v.(cache.store.history')))
    (l.[(cache.store.t), "history"] ↦{dq} (v.(cache.store.history')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance store_access_store_history l (v : (cache.store.t)) history' :
  AccessStrict
    (l.[(cache.store.t), "history"] ↦ (v.(cache.store.history')))
    (l.[(cache.store.t), "history"] ↦ history')
    (l ↦ v) (l ↦ (v <|(cache.store.history') := history'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End store.

Module kvItem.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance kvItem_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.kvItem.t). Admitted.

#[global] Instance kvItem_into_val_typed
   :
  IntoValTypedUnderlying (cache.kvItem.t) (cache.kvItemⁱᵐᵖˡ).
Proof. Admitted.

End def.
End kvItem.

Module watcher.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cache.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance watcher_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cache.watcher.t). Admitted.

#[global] Instance watcher_into_val_typed
   :
  IntoValTypedUnderlying (cache.watcher.t) (cache.watcherⁱᵐᵖˡ).
Proof. Admitted.

End def.
End watcher.

End cache.
